module ParserFeaturesNsssResiduals
using MacroModelling

const normcdf = MacroModelling.SymPyWorkspace.normcdf
const pnorm = MacroModelling.SymPyWorkspace.pnorm
const normpdf = MacroModelling.SymPyWorkspace.normpdf
const dnorm = MacroModelling.SymPyWorkspace.dnorm
const normlogpdf = MacroModelling.SymPyWorkspace.normlogpdf
const norminvcdf = MacroModelling.SymPyWorkspace.norminvcdf
const norminv = MacroModelling.SymPyWorkspace.norminv
const qnorm = MacroModelling.SymPyWorkspace.qnorm
const erfcinv = MacroModelling.SymPyWorkspace.erfcinv
const erfc = MacroModelling.SymPyWorkspace.erfc
const Max = max
const Min = min

const MODEL_NAME = "ParserFeatures"
const SOURCE_MODEL_FILE = "models/ParserFeatures.jl"
const NSSS_SOLUTION_ERROR = 7.194635805153547e-16
const NSSS_RESIDUAL_NORM = 1.3497887713973342e-15

const PARAMETER_NAMES = [
    "rho",
    "sigma",
    "consumption_share",
    "foreign_gap",
    "inflation_bar",
    "inflation_shock",
    "rate_floor",
    "tax_cap",
    "tax_base",
    "tax_rate",
    "ifelse_switch",
    "shock_scale",
    "trade_weight{H}{F}",
    "trade_weight{F}{H}",
    "λ{A}",
    "λ{B}",
    "χ{A}",
    "χ{B}",
    "alpha{F}",
    "output_target",
    "inflation_target",
    "delta",
    "activeᵒᵇᶜshocks",
]
const PARAMETER_VALUES = Float64[
    0.8,
    0.01,
    0.7,
    0.05,
    1.0,
    0.01,
    0.95,
    0.4,
    0.1,
    0.01,
    1.0,
    0.001,
    0.2,
    0.2,
    0.2,
    0.3,
    0.75,
    0.5,
    0.6,
    5.2,
    0.02,
    0.05,
    0.0,
]
const COMPLETE_PARAMETER_NAMES = [
    "rho",
    "sigma",
    "consumption_share",
    "foreign_gap",
    "inflation_bar",
    "inflation_shock",
    "rate_floor",
    "tax_cap",
    "tax_base",
    "tax_rate",
    "ifelse_switch",
    "shock_scale",
    "trade_weight{H}{F}",
    "trade_weight{F}{H}",
    "λ{A}",
    "λ{B}",
    "χ{A}",
    "χ{B}",
    "alpha{F}",
    "output_target",
    "inflation_target",
    "delta",
    "activeᵒᵇᶜshocks",
    "foreign_scale",
    "investment_share",
    "rate_target",
]
const COMPLETE_PARAMETER_VALUES = Float64[
    0.8,
    0.01,
    0.7,
    0.05,
    1.0,
    0.01,
    0.95,
    0.4,
    0.1,
    0.01,
    1.0,
    0.001,
    0.2,
    0.2,
    0.2,
    0.3,
    0.75,
    0.5,
    0.6,
    5.2,
    0.02,
    0.05,
    0.0,
    0.95,
    0.15000000000000002,
    1.02,
]
const ORIGINAL_SOLUTION_NAMES = [
    "a{F}",
    "a{H}",
    "cdf_signal{F}",
    "cdf_signal{H}",
    "c{F}",
    "c{H}",
    "dnorm_signal{F}",
    "dnorm_signal{H}",
    "forward_anchor{F}",
    "forward_anchor{H}",
    "g{F}",
    "g{H}",
    "inflation_product{F}",
    "inflation_product{H}",
    "inflation{F}",
    "inflation{H}",
    "inverse_signal{F}",
    "inverse_signal{H}",
    "i{F}",
    "i{H}",
    "k{F}",
    "k{H}",
    "logpdf_signal{F}",
    "logpdf_signal{H}",
    "net_exports{F}",
    "net_exports{H}",
    "norminv_signal{F}",
    "norminv_signal{H}",
    "pdf_signal{F}",
    "pdf_signal{H}",
    "pnorm_signal{F}",
    "pnorm_signal{H}",
    "probability_signal{F}",
    "probability_signal{H}",
    "qnorm_signal{F}",
    "qnorm_signal{H}",
    "relative_output",
    "r{F}",
    "r{H}",
    "sales_window{F}",
    "sales_window{H}",
    "steady_gap{F}",
    "steady_gap{H}",
    "tax{F}",
    "tax{H}",
    "world_output",
    "y{F}",
    "y{H}",
    "Χᵒᵇᶜ⁺ꜝ³ꜝ",
    "Χᵒᵇᶜ⁺ꜝ¹ꜝ",
    "Χᵒᵇᶜ⁻ꜝ²ꜝ",
    "Χᵒᵇᶜ⁻ꜝ⁴ꜝ",
    "κ{F}{A}",
    "κ{F}{B}",
    "κ{H}{A}",
    "κ{H}{B}",
    "χᵒᵇᶜ⁺ꜝ³ꜝʳ",
    "χᵒᵇᶜ⁺ꜝ³ꜝˡ",
    "χᵒᵇᶜ⁺ꜝ¹ꜝʳ",
    "χᵒᵇᶜ⁺ꜝ¹ꜝˡ",
    "χᵒᵇᶜ⁻ꜝ²ꜝʳ",
    "χᵒᵇᶜ⁻ꜝ²ꜝˡ",
    "χᵒᵇᶜ⁻ꜝ⁴ꜝʳ",
    "χᵒᵇᶜ⁻ꜝ⁴ꜝˡ",
    "ϵᵒᵇᶜ⁺ꜝ³ꜝ",
    "ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻²⁾",
    "ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻³⁾",
    "ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻¹⁾",
    "ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻⁰⁾",
    "ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻⁴⁾",
    "ϵᵒᵇᶜ⁺ꜝ¹ꜝ",
    "ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻²⁾",
    "ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻³⁾",
    "ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻¹⁾",
    "ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻⁰⁾",
    "ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻⁴⁾",
    "ϵᵒᵇᶜ⁻ꜝ²ꜝ",
    "ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻²⁾",
    "ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻³⁾",
    "ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻¹⁾",
    "ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻⁰⁾",
    "ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻⁴⁾",
    "ϵᵒᵇᶜ⁻ꜝ⁴ꜝ",
    "ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻²⁾",
    "ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻³⁾",
    "ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻¹⁾",
    "ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻⁰⁾",
    "ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻⁴⁾",
    "beta",
    "alpha{H}",
]
const ORIGINAL_SOLUTION_VALUES = Float64[
    1.0,
    1.0,
    0.5,
    0.5,
    3.1995502501328206,
    3.6399999999999997,
    0.3989422804014327,
    0.3989422804014327,
    0.0,
    0.0,
    0.6856179107427472,
    0.7800000000000004,
    1.0,
    1.0,
    1.0,
    1.0,
    1.46849953349524e-32,
    -4.1843292356759943e-32,
    0.6856179107427475,
    0.7800000000000001,
    13.712358214854945,
    15.599999999999982,
    -0.9189385332046727,
    -0.9189385332046727,
    -0.12584278567633703,
    0.12584278567633703,
    1.46849953349524e-32,
    -4.1843292356759943e-32,
    0.3989422804014327,
    0.3989422804014327,
    0.5,
    0.5,
    0.5,
    0.5,
    1.46849953349524e-32,
    -4.1843292356759943e-32,
    1.0,
    1.02,
    1.02,
    13.712358214854945,
    15.600000000000001,
    0.0,
    0.0,
    0.14570786071618314,
    0.15200000000000002,
    9.770786071618316,
    4.570786071618315,
    5.2,
    0.0,
    0.0,
    0.0,
    0.0,
    0.30000000000000004,
    0.3,
    0.30000000000000004,
    0.3,
    0.0,
    -0.07000000000000006,
    0.0,
    -0.07000000000000006,
    0.0,
    0.24799999999999997,
    0.0,
    0.25429213928381683,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.9803921568627451,
    0.6001077713277388,
]
const AUXILIARY_SOLUTION_NAMES = [
    "a{F}",
    "a{H}",
    "cdf_signal{F}",
    "cdf_signal{H}",
    "c{F}",
    "c{H}",
    "dnorm_signal{F}",
    "dnorm_signal{H}",
    "forward_anchor{F}",
    "forward_anchor{H}",
    "g{F}",
    "g{H}",
    "inflation_product{F}",
    "inflation_product{H}",
    "inflation{F}",
    "inflation{H}",
    "inverse_signal{F}",
    "inverse_signal{H}",
    "i{F}",
    "i{H}",
    "k{F}",
    "k{H}",
    "logpdf_signal{F}",
    "logpdf_signal{H}",
    "net_exports{F}",
    "net_exports{H}",
    "norminv_signal{F}",
    "norminv_signal{H}",
    "pdf_signal{F}",
    "pdf_signal{H}",
    "pnorm_signal{F}",
    "pnorm_signal{H}",
    "probability_signal{F}",
    "probability_signal{H}",
    "qnorm_signal{F}",
    "qnorm_signal{H}",
    "relative_output",
    "r{F}",
    "r{H}",
    "sales_window{F}",
    "sales_window{H}",
    "steady_gap{F}",
    "steady_gap{H}",
    "tax{F}",
    "tax{H}",
    "world_output",
    "y{F}",
    "y{H}",
    "Χᵒᵇᶜ⁺ꜝ³ꜝ",
    "Χᵒᵇᶜ⁺ꜝ¹ꜝ",
    "Χᵒᵇᶜ⁻ꜝ²ꜝ",
    "Χᵒᵇᶜ⁻ꜝ⁴ꜝ",
    "κ{F}{A}",
    "κ{F}{B}",
    "κ{H}{A}",
    "κ{H}{B}",
    "χᵒᵇᶜ⁺ꜝ³ꜝʳ",
    "χᵒᵇᶜ⁺ꜝ³ꜝˡ",
    "χᵒᵇᶜ⁺ꜝ¹ꜝʳ",
    "χᵒᵇᶜ⁺ꜝ¹ꜝˡ",
    "χᵒᵇᶜ⁻ꜝ²ꜝʳ",
    "χᵒᵇᶜ⁻ꜝ²ꜝˡ",
    "χᵒᵇᶜ⁻ꜝ⁴ꜝʳ",
    "χᵒᵇᶜ⁻ꜝ⁴ꜝˡ",
    "ϵᵒᵇᶜ⁺ꜝ³ꜝ",
    "ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻²⁾",
    "ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻³⁾",
    "ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻¹⁾",
    "ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻⁰⁾",
    "ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻⁴⁾",
    "ϵᵒᵇᶜ⁺ꜝ¹ꜝ",
    "ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻²⁾",
    "ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻³⁾",
    "ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻¹⁾",
    "ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻⁰⁾",
    "ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻⁴⁾",
    "ϵᵒᵇᶜ⁻ꜝ²ꜝ",
    "ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻²⁾",
    "ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻³⁾",
    "ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻¹⁾",
    "ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻⁰⁾",
    "ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻⁴⁾",
    "ϵᵒᵇᶜ⁻ꜝ⁴ꜝ",
    "ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻²⁾",
    "ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻³⁾",
    "ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻¹⁾",
    "ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻⁰⁾",
    "ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻⁴⁾",
    "beta",
    "alpha{H}",
]
const AUXILIARY_SOLUTION_VALUES = Float64[
    1.0,
    1.0,
    0.5,
    0.5,
    3.1995502501328197,
    3.6399999999999997,
    0.398942280401433,
    0.398942280401433,
    0.0,
    0.0,
    0.6856179107427471,
    0.7800000000000002,
    1.0,
    1.0,
    1.0,
    1.0,
    0.0,
    0.0,
    0.6856179107427471,
    0.7800000000000001,
    13.71235821485494,
    15.600000000000001,
    -0.918938533204673,
    -0.918938533204673,
    -0.12584278567633725,
    0.12584278567633725,
    0.0,
    0.0,
    0.398942280401433,
    0.398942280401433,
    0.5,
    0.5,
    0.5,
    0.5,
    0.0,
    0.0,
    1.0,
    1.0199999999999998,
    1.02,
    13.712358214854941,
    15.600000000000001,
    0.0,
    0.0,
    0.14570786071618316,
    0.15200000000000002,
    9.770786071618314,
    4.570786071618314,
    5.2,
    0.0,
    0.0,
    0.0,
    0.0,
    0.1,
    0.3,
    0.1,
    0.3,
    1.6431625272369705e-16,
    -0.06999999999999967,
    0.0,
    -0.07000000000000006,
    -3.2590301201736453e-21,
    0.24799999999999997,
    -3.479470926141543e-21,
    0.25429213928381683,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.9803921568627451,
    0.6001077713277385,
]
const ALL_AUXILIARY_VARIABLE_NAMES = [
    "➕₁",
    "➕₂",
]
const ALL_AUXILIARY_VARIABLE_VALUES = Float64[
    5.2,
    15.600000000000001,
]
const DEFAULTED_NSSS_SOLUTION_NAMES = [
    "ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻²⁾",
    "ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻³⁾",
    "ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻¹⁾",
    "ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻⁰⁾",
    "ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻⁴⁾",
    "ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻²⁾",
    "ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻³⁾",
    "ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻¹⁾",
    "ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻⁰⁾",
    "ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻⁴⁾",
    "ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻²⁾",
    "ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻³⁾",
    "ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻¹⁾",
    "ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻⁰⁾",
    "ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻⁴⁾",
    "ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻²⁾",
    "ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻³⁾",
    "ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻¹⁾",
    "ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻⁰⁾",
    "ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻⁴⁾",
]
const CALIBRATION_PARAMETER_NAMES = [
    "beta",
    "alpha{H}",
]

const ORIGINAL_NSSS_EQUATIONS = Expr[
    :(y◖H◗ - a◖H◗ * k◖H◗ ^ alpha◖H◗),
    :(c◖H◗ - consumption_share * y◖H◗),
    :(i◖H◗ - investment_share * y◖H◗),
    :(((y◖H◗ - c◖H◗) - i◖H◗) - g◖H◗),
    :(k◖H◗ - ((1 - delta) * k◖H◗ + i◖H◗)),
    :(a◖H◗ - ((1 - rho) + rho * a◖H◗ + sigma * 0 + sigma * 0 + sigma * 0 + sigma * 0)),
    :(χᵒᵇᶜ⁺ꜝ¹ꜝˡ - (rate_floor - r◖H◗)),
    :(χᵒᵇᶜ⁺ꜝ¹ꜝʳ - (c◖H◗ / (beta * c◖H◗) - r◖H◗)),
    :(Χᵒᵇᶜ⁺ꜝ¹ꜝ - max(χᵒᵇᶜ⁺ꜝ¹ꜝˡ, χᵒᵇᶜ⁺ꜝ¹ꜝʳ)),
    :(Χᵒᵇᶜ⁺ꜝ¹ꜝ - ϵᵒᵇᶜ⁺ꜝ¹ꜝ),
    :(χᵒᵇᶜ⁻ꜝ²ꜝˡ - (tax_cap - tax◖H◗)),
    :(χᵒᵇᶜ⁻ꜝ²ꜝʳ - ((tax_base + tax_rate * y◖H◗) - tax◖H◗)),
    :(Χᵒᵇᶜ⁻ꜝ²ꜝ - min(χᵒᵇᶜ⁻ꜝ²ꜝˡ, χᵒᵇᶜ⁻ꜝ²ꜝʳ)),
    :(Χᵒᵇᶜ⁻ꜝ²ꜝ - ϵᵒᵇᶜ⁻ꜝ²ꜝ),
    :(sales_window◖H◗ - (y◖H◗ + y◖H◗ + y◖H◗)),
    :(forward_anchor◖H◗ - (y◖H◗ - y◖H◗)),
    :(inflation_product◖H◗ - inflation◖H◗ * inflation◖H◗ * inflation◖H◗),
    :(inflation◖H◗ - (inflation_bar + inflation_shock * 0)),
    :(cdf_signal◖H◗ - normcdf(a◖H◗ - 1)),
    :(pdf_signal◖H◗ - normpdf(a◖H◗ - 1)),
    :(logpdf_signal◖H◗ - normlogpdf(a◖H◗ - 1)),
    :(probability_signal◖H◗ - (0.5 + 0.25 * tanh(a◖H◗ - 1))),
    :(inverse_signal◖H◗ - norminvcdf(probability_signal◖H◗)),
    :(norminv_signal◖H◗ - norminv(probability_signal◖H◗)),
    :(qnorm_signal◖H◗ - qnorm(probability_signal◖H◗)),
    :(pnorm_signal◖H◗ - pnorm(a◖H◗ - 1)),
    :(dnorm_signal◖H◗ - dnorm(a◖H◗ - 1)),
    :(steady_gap◖H◗ - (y◖H◗ - y◖H◗)),
    :(κ◖H◗◖A◗ - (0.25κ◖H◗◖A◗ + 0.25κ◖H◗◖A◗ + λ◖A◗ * ifelse(ifelse_switch > 0.5, χ◖A◗, 1 - χ◖A◗) + shock_scale * 0 + shock_scale * 0)),
    :(κ◖H◗◖B◗ - (0.25κ◖H◗◖B◗ + 0.25κ◖H◗◖B◗ + λ◖B◗ * ifelse(ifelse_switch > 0.5, χ◖B◗, 1 - χ◖B◗) + shock_scale * 0 + shock_scale * 0)),
    :(y◖F◗ - foreign_scale * a◖F◗ * k◖F◗ ^ alpha◖F◗),
    :(c◖F◗ - consumption_share * y◖F◗),
    :(i◖F◗ - investment_share * y◖F◗),
    :(((y◖F◗ - c◖F◗) - i◖F◗) - g◖F◗),
    :(k◖F◗ - ((1 - delta) * k◖F◗ + i◖F◗)),
    :(a◖F◗ - ((1 - rho) + rho * a◖F◗ + sigma * 0 + sigma * 0 + sigma * 0 + sigma * 0)),
    :(χᵒᵇᶜ⁺ꜝ³ꜝˡ - (rate_floor - r◖F◗)),
    :(χᵒᵇᶜ⁺ꜝ³ꜝʳ - (c◖F◗ / (beta * c◖F◗) - r◖F◗)),
    :(Χᵒᵇᶜ⁺ꜝ³ꜝ - max(χᵒᵇᶜ⁺ꜝ³ꜝˡ, χᵒᵇᶜ⁺ꜝ³ꜝʳ)),
    :(Χᵒᵇᶜ⁺ꜝ³ꜝ - ϵᵒᵇᶜ⁺ꜝ³ꜝ),
    :(χᵒᵇᶜ⁻ꜝ⁴ꜝˡ - (tax_cap - tax◖F◗)),
    :(χᵒᵇᶜ⁻ꜝ⁴ꜝʳ - ((tax_base + tax_rate * y◖F◗) - tax◖F◗)),
    :(Χᵒᵇᶜ⁻ꜝ⁴ꜝ - min(χᵒᵇᶜ⁻ꜝ⁴ꜝˡ, χᵒᵇᶜ⁻ꜝ⁴ꜝʳ)),
    :(Χᵒᵇᶜ⁻ꜝ⁴ꜝ - ϵᵒᵇᶜ⁻ꜝ⁴ꜝ),
    :(sales_window◖F◗ - (y◖F◗ + y◖F◗ + y◖F◗)),
    :(forward_anchor◖F◗ - (y◖F◗ - y◖F◗)),
    :(inflation_product◖F◗ - inflation◖F◗ * inflation◖F◗ * inflation◖F◗),
    :(inflation◖F◗ - (inflation_bar + inflation_shock * 0)),
    :(cdf_signal◖F◗ - normcdf(a◖F◗ - 1)),
    :(pdf_signal◖F◗ - normpdf(a◖F◗ - 1)),
    :(logpdf_signal◖F◗ - normlogpdf(a◖F◗ - 1)),
    :(probability_signal◖F◗ - (0.5 + 0.25 * tanh(a◖F◗ - 1))),
    :(inverse_signal◖F◗ - norminvcdf(probability_signal◖F◗)),
    :(norminv_signal◖F◗ - norminv(probability_signal◖F◗)),
    :(qnorm_signal◖F◗ - qnorm(probability_signal◖F◗)),
    :(pnorm_signal◖F◗ - pnorm(a◖F◗ - 1)),
    :(dnorm_signal◖F◗ - dnorm(a◖F◗ - 1)),
    :(steady_gap◖F◗ - (y◖F◗ - y◖F◗)),
    :(κ◖F◗◖A◗ - (0.25κ◖F◗◖A◗ + 0.25κ◖F◗◖A◗ + λ◖A◗ * ifelse(ifelse_switch > 0.5, χ◖A◗, 1 - χ◖A◗) + shock_scale * 0 + shock_scale * 0)),
    :(κ◖F◗◖B◗ - (0.25κ◖F◗◖B◗ + 0.25κ◖F◗◖B◗ + λ◖B◗ * ifelse(ifelse_switch > 0.5, χ◖B◗, 1 - χ◖B◗) + shock_scale * 0 + shock_scale * 0)),
    :(world_output - (y◖H◗ + y◖F◗)),
    :(relative_output - (y◖H◗ / y◖F◗) / (y◖H◗ / y◖F◗)),
    :(net_exports◖H◗ - trade_weight◖H◗◖F◗ * (y◖H◗ - y◖F◗)),
    :(net_exports◖F◗ - trade_weight◖F◗◖H◗ * (y◖F◗ - y◖H◗)),
    :(ϵᵒᵇᶜ⁺ꜝ¹ꜝ - ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻⁴⁾),
    :(ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻⁰⁾ - activeᵒᵇᶜshocks * 0),
    :(ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻¹⁾ - (ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻⁰⁾ + activeᵒᵇᶜshocks * 0)),
    :(ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻²⁾ - (ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻¹⁾ + activeᵒᵇᶜshocks * 0)),
    :(ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻³⁾ - (ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻²⁾ + activeᵒᵇᶜshocks * 0)),
    :(ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻⁴⁾ - (ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻³⁾ + activeᵒᵇᶜshocks * 0)),
    :(ϵᵒᵇᶜ⁻ꜝ²ꜝ - ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻⁴⁾),
    :(ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻⁰⁾ - activeᵒᵇᶜshocks * 0),
    :(ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻¹⁾ - (ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻⁰⁾ + activeᵒᵇᶜshocks * 0)),
    :(ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻²⁾ - (ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻¹⁾ + activeᵒᵇᶜshocks * 0)),
    :(ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻³⁾ - (ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻²⁾ + activeᵒᵇᶜshocks * 0)),
    :(ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻⁴⁾ - (ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻³⁾ + activeᵒᵇᶜshocks * 0)),
    :(ϵᵒᵇᶜ⁺ꜝ³ꜝ - ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻⁴⁾),
    :(ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻⁰⁾ - activeᵒᵇᶜshocks * 0),
    :(ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻¹⁾ - (ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻⁰⁾ + activeᵒᵇᶜshocks * 0)),
    :(ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻²⁾ - (ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻¹⁾ + activeᵒᵇᶜshocks * 0)),
    :(ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻³⁾ - (ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻²⁾ + activeᵒᵇᶜshocks * 0)),
    :(ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻⁴⁾ - (ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻³⁾ + activeᵒᵇᶜshocks * 0)),
    :(ϵᵒᵇᶜ⁻ꜝ⁴ꜝ - ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻⁴⁾),
    :(ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻⁰⁾ - activeᵒᵇᶜshocks * 0),
    :(ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻¹⁾ - (ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻⁰⁾ + activeᵒᵇᶜshocks * 0)),
    :(ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻²⁾ - (ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻¹⁾ + activeᵒᵇᶜshocks * 0)),
    :(ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻³⁾ - (ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻²⁾ + activeᵒᵇᶜshocks * 0)),
    :(ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻⁴⁾ - (ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻³⁾ + activeᵒᵇᶜshocks * 0)),
]
const CALIBRATION_EQUATIONS = Expr[
    :(r◖H◗ - rate_target),
    :(y◖H◗ - output_target),
]
const AUXILIARY_NSSS_EQUATIONS = Expr[
    :(-a◖H◗ * k◖H◗ ^ alpha◖H◗ + y◖H◗),
    :(-consumption_share * y◖H◗ + c◖H◗),
    :(-investment_share * y◖H◗ + i◖H◗),
    :(((-c◖H◗ - g◖H◗) - i◖H◗) + y◖H◗),
    :((-i◖H◗ - k◖H◗ * (1 - delta)) + k◖H◗),
    :((-a◖H◗ * rho + a◖H◗ + rho) - 1),
    :(-rate_floor + r◖H◗ + χᵒᵇᶜ⁺ꜝ¹ꜝˡ),
    :((r◖H◗ + χᵒᵇᶜ⁺ꜝ¹ꜝʳ) - 1 / beta),
    :(Χᵒᵇᶜ⁺ꜝ¹ꜝ - Max(χᵒᵇᶜ⁺ꜝ¹ꜝʳ, χᵒᵇᶜ⁺ꜝ¹ꜝˡ)),
    :(Χᵒᵇᶜ⁺ꜝ¹ꜝ - ϵᵒᵇᶜ⁺ꜝ¹ꜝ),
    :(-tax_cap + tax◖H◗ + χᵒᵇᶜ⁻ꜝ²ꜝˡ),
    :((-tax_base - tax_rate * y◖H◗) + tax◖H◗ + χᵒᵇᶜ⁻ꜝ²ꜝʳ),
    :(Χᵒᵇᶜ⁻ꜝ²ꜝ - Min(χᵒᵇᶜ⁻ꜝ²ꜝʳ, χᵒᵇᶜ⁻ꜝ²ꜝˡ)),
    :(Χᵒᵇᶜ⁻ꜝ²ꜝ - ϵᵒᵇᶜ⁻ꜝ²ꜝ),
    :(sales_window◖H◗ - 3y◖H◗),
    :(forward_anchor◖H◗ - 0),
    :(inflation_product◖H◗ - inflation◖H◗ ^ 3),
    :(-inflation_bar + inflation◖H◗),
    :((cdf_signal◖H◗ + erfc(0.707106781186547a◖H◗ - 0.707106781186547) / 2) - 1),
    :(pdf_signal◖H◗ - 0.398942280401433 * exp(-((a◖H◗ - 1) ^ 2) / 2)),
    :(logpdf_signal◖H◗ + (a◖H◗ - 1) ^ 2 / 2 + 0.918938533204673),
    :((probability_signal◖H◗ - 0.25 * tanh(a◖H◗ - 1)) - 0.5),
    :(inverse_signal◖H◗ + 1.4142135623731 * erfcinv(2probability_signal◖H◗)),
    :(norminv_signal◖H◗ + 1.4142135623731 * erfcinv(2probability_signal◖H◗)),
    :(qnorm_signal◖H◗ + 1.4142135623731 * erfcinv(2probability_signal◖H◗)),
    :((pnorm_signal◖H◗ + erfc(0.707106781186547a◖H◗ - 0.707106781186547) / 2) - 1),
    :(dnorm_signal◖H◗ - 0.398942280401433 * exp(-((a◖H◗ - 1) ^ 2) / 2)),
    :(steady_gap◖H◗ - 0),
    :(0.5κ◖H◗◖A◗ - λ◖A◗ * (1 - χ◖A◗)),
    :(0.5κ◖H◗◖B◗ - λ◖B◗ * (1 - χ◖B◗)),
    :(-a◖F◗ * foreign_scale * k◖F◗ ^ alpha◖F◗ + y◖F◗),
    :(-consumption_share * y◖F◗ + c◖F◗),
    :(-investment_share * y◖F◗ + i◖F◗),
    :(((-c◖F◗ - g◖F◗) - i◖F◗) + y◖F◗),
    :((-i◖F◗ - k◖F◗ * (1 - delta)) + k◖F◗),
    :((-a◖F◗ * rho + a◖F◗ + rho) - 1),
    :(-rate_floor + r◖F◗ + χᵒᵇᶜ⁺ꜝ³ꜝˡ),
    :((r◖F◗ + χᵒᵇᶜ⁺ꜝ³ꜝʳ) - 1 / beta),
    :(Χᵒᵇᶜ⁺ꜝ³ꜝ - Max(χᵒᵇᶜ⁺ꜝ³ꜝʳ, χᵒᵇᶜ⁺ꜝ³ꜝˡ)),
    :(Χᵒᵇᶜ⁺ꜝ³ꜝ - ϵᵒᵇᶜ⁺ꜝ³ꜝ),
    :(-tax_cap + tax◖F◗ + χᵒᵇᶜ⁻ꜝ⁴ꜝˡ),
    :((-tax_base - tax_rate * y◖F◗) + tax◖F◗ + χᵒᵇᶜ⁻ꜝ⁴ꜝʳ),
    :(Χᵒᵇᶜ⁻ꜝ⁴ꜝ - Min(χᵒᵇᶜ⁻ꜝ⁴ꜝʳ, χᵒᵇᶜ⁻ꜝ⁴ꜝˡ)),
    :(Χᵒᵇᶜ⁻ꜝ⁴ꜝ - ϵᵒᵇᶜ⁻ꜝ⁴ꜝ),
    :(sales_window◖F◗ - 3y◖F◗),
    :(forward_anchor◖F◗ - 0),
    :(inflation_product◖F◗ - inflation◖F◗ ^ 3),
    :(-inflation_bar + inflation◖F◗),
    :((cdf_signal◖F◗ + erfc(0.707106781186547a◖F◗ - 0.707106781186547) / 2) - 1),
    :(pdf_signal◖F◗ - 0.398942280401433 * exp(-((a◖F◗ - 1) ^ 2) / 2)),
    :(logpdf_signal◖F◗ + (a◖F◗ - 1) ^ 2 / 2 + 0.918938533204673),
    :((probability_signal◖F◗ - 0.25 * tanh(a◖F◗ - 1)) - 0.5),
    :(inverse_signal◖F◗ + 1.4142135623731 * erfcinv(2probability_signal◖F◗)),
    :(norminv_signal◖F◗ + 1.4142135623731 * erfcinv(2probability_signal◖F◗)),
    :(qnorm_signal◖F◗ + 1.4142135623731 * erfcinv(2probability_signal◖F◗)),
    :((pnorm_signal◖F◗ + erfc(0.707106781186547a◖F◗ - 0.707106781186547) / 2) - 1),
    :(dnorm_signal◖F◗ - 0.398942280401433 * exp(-((a◖F◗ - 1) ^ 2) / 2)),
    :(steady_gap◖F◗ - 0),
    :(0.5κ◖F◗◖A◗ - λ◖A◗ * (1 - χ◖A◗)),
    :(0.5κ◖F◗◖B◗ - λ◖B◗ * (1 - χ◖B◗)),
    :((world_output - y◖F◗) - y◖H◗),
    :(relative_output - 1),
    :(net_exports◖H◗ - trade_weight◖H◗◖F◗ * (-y◖F◗ + y◖H◗)),
    :(net_exports◖F◗ - trade_weight◖F◗◖H◗ * (y◖F◗ - y◖H◗)),
    :(ϵᵒᵇᶜ⁺ꜝ¹ꜝ - ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻⁴⁾),
    :(ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻⁰⁾ - 0),
    :(ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻¹⁾ - ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻⁰⁾),
    :(ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻²⁾ - ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻¹⁾),
    :(-ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻²⁾ + ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻³⁾),
    :(-ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻³⁾ + ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻⁴⁾),
    :(ϵᵒᵇᶜ⁻ꜝ²ꜝ - ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻⁴⁾),
    :(ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻⁰⁾ - 0),
    :(ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻¹⁾ - ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻⁰⁾),
    :(ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻²⁾ - ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻¹⁾),
    :(-ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻²⁾ + ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻³⁾),
    :(-ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻³⁾ + ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻⁴⁾),
    :(ϵᵒᵇᶜ⁺ꜝ³ꜝ - ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻⁴⁾),
    :(ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻⁰⁾ - 0),
    :(ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻¹⁾ - ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻⁰⁾),
    :(ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻²⁾ - ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻¹⁾),
    :(-ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻²⁾ + ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻³⁾),
    :(-ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻³⁾ + ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻⁴⁾),
    :(ϵᵒᵇᶜ⁻ꜝ⁴ꜝ - ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻⁴⁾),
    :(ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻⁰⁾ - 0),
    :(ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻¹⁾ - ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻⁰⁾),
    :(ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻²⁾ - ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻¹⁾),
    :(-ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻²⁾ + ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻³⁾),
    :(-ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻³⁾ + ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻⁴⁾),
]
const ORIGINAL_RESIDUAL_EQUATIONS = Expr[
    :(y◖H◗ - a◖H◗ * k◖H◗ ^ alpha◖H◗),
    :(c◖H◗ - consumption_share * y◖H◗),
    :(i◖H◗ - investment_share * y◖H◗),
    :(((y◖H◗ - c◖H◗) - i◖H◗) - g◖H◗),
    :(k◖H◗ - ((1 - delta) * k◖H◗ + i◖H◗)),
    :(a◖H◗ - ((1 - rho) + rho * a◖H◗ + sigma * 0 + sigma * 0 + sigma * 0 + sigma * 0)),
    :(χᵒᵇᶜ⁺ꜝ¹ꜝˡ - (rate_floor - r◖H◗)),
    :(χᵒᵇᶜ⁺ꜝ¹ꜝʳ - (c◖H◗ / (beta * c◖H◗) - r◖H◗)),
    :(Χᵒᵇᶜ⁺ꜝ¹ꜝ - max(χᵒᵇᶜ⁺ꜝ¹ꜝˡ, χᵒᵇᶜ⁺ꜝ¹ꜝʳ)),
    :(Χᵒᵇᶜ⁺ꜝ¹ꜝ - ϵᵒᵇᶜ⁺ꜝ¹ꜝ),
    :(χᵒᵇᶜ⁻ꜝ²ꜝˡ - (tax_cap - tax◖H◗)),
    :(χᵒᵇᶜ⁻ꜝ²ꜝʳ - ((tax_base + tax_rate * y◖H◗) - tax◖H◗)),
    :(Χᵒᵇᶜ⁻ꜝ²ꜝ - min(χᵒᵇᶜ⁻ꜝ²ꜝˡ, χᵒᵇᶜ⁻ꜝ²ꜝʳ)),
    :(Χᵒᵇᶜ⁻ꜝ²ꜝ - ϵᵒᵇᶜ⁻ꜝ²ꜝ),
    :(sales_window◖H◗ - (y◖H◗ + y◖H◗ + y◖H◗)),
    :(forward_anchor◖H◗ - (y◖H◗ - y◖H◗)),
    :(inflation_product◖H◗ - inflation◖H◗ * inflation◖H◗ * inflation◖H◗),
    :(inflation◖H◗ - (inflation_bar + inflation_shock * 0)),
    :(cdf_signal◖H◗ - normcdf(a◖H◗ - 1)),
    :(pdf_signal◖H◗ - normpdf(a◖H◗ - 1)),
    :(logpdf_signal◖H◗ - normlogpdf(a◖H◗ - 1)),
    :(probability_signal◖H◗ - (0.5 + 0.25 * tanh(a◖H◗ - 1))),
    :(inverse_signal◖H◗ - norminvcdf(probability_signal◖H◗)),
    :(norminv_signal◖H◗ - norminv(probability_signal◖H◗)),
    :(qnorm_signal◖H◗ - qnorm(probability_signal◖H◗)),
    :(pnorm_signal◖H◗ - pnorm(a◖H◗ - 1)),
    :(dnorm_signal◖H◗ - dnorm(a◖H◗ - 1)),
    :(steady_gap◖H◗ - (y◖H◗ - y◖H◗)),
    :(κ◖H◗◖A◗ - (0.25κ◖H◗◖A◗ + 0.25κ◖H◗◖A◗ + λ◖A◗ * ifelse(ifelse_switch > 0.5, χ◖A◗, 1 - χ◖A◗) + shock_scale * 0 + shock_scale * 0)),
    :(κ◖H◗◖B◗ - (0.25κ◖H◗◖B◗ + 0.25κ◖H◗◖B◗ + λ◖B◗ * ifelse(ifelse_switch > 0.5, χ◖B◗, 1 - χ◖B◗) + shock_scale * 0 + shock_scale * 0)),
    :(y◖F◗ - foreign_scale * a◖F◗ * k◖F◗ ^ alpha◖F◗),
    :(c◖F◗ - consumption_share * y◖F◗),
    :(i◖F◗ - investment_share * y◖F◗),
    :(((y◖F◗ - c◖F◗) - i◖F◗) - g◖F◗),
    :(k◖F◗ - ((1 - delta) * k◖F◗ + i◖F◗)),
    :(a◖F◗ - ((1 - rho) + rho * a◖F◗ + sigma * 0 + sigma * 0 + sigma * 0 + sigma * 0)),
    :(χᵒᵇᶜ⁺ꜝ³ꜝˡ - (rate_floor - r◖F◗)),
    :(χᵒᵇᶜ⁺ꜝ³ꜝʳ - (c◖F◗ / (beta * c◖F◗) - r◖F◗)),
    :(Χᵒᵇᶜ⁺ꜝ³ꜝ - max(χᵒᵇᶜ⁺ꜝ³ꜝˡ, χᵒᵇᶜ⁺ꜝ³ꜝʳ)),
    :(Χᵒᵇᶜ⁺ꜝ³ꜝ - ϵᵒᵇᶜ⁺ꜝ³ꜝ),
    :(χᵒᵇᶜ⁻ꜝ⁴ꜝˡ - (tax_cap - tax◖F◗)),
    :(χᵒᵇᶜ⁻ꜝ⁴ꜝʳ - ((tax_base + tax_rate * y◖F◗) - tax◖F◗)),
    :(Χᵒᵇᶜ⁻ꜝ⁴ꜝ - min(χᵒᵇᶜ⁻ꜝ⁴ꜝˡ, χᵒᵇᶜ⁻ꜝ⁴ꜝʳ)),
    :(Χᵒᵇᶜ⁻ꜝ⁴ꜝ - ϵᵒᵇᶜ⁻ꜝ⁴ꜝ),
    :(sales_window◖F◗ - (y◖F◗ + y◖F◗ + y◖F◗)),
    :(forward_anchor◖F◗ - (y◖F◗ - y◖F◗)),
    :(inflation_product◖F◗ - inflation◖F◗ * inflation◖F◗ * inflation◖F◗),
    :(inflation◖F◗ - (inflation_bar + inflation_shock * 0)),
    :(cdf_signal◖F◗ - normcdf(a◖F◗ - 1)),
    :(pdf_signal◖F◗ - normpdf(a◖F◗ - 1)),
    :(logpdf_signal◖F◗ - normlogpdf(a◖F◗ - 1)),
    :(probability_signal◖F◗ - (0.5 + 0.25 * tanh(a◖F◗ - 1))),
    :(inverse_signal◖F◗ - norminvcdf(probability_signal◖F◗)),
    :(norminv_signal◖F◗ - norminv(probability_signal◖F◗)),
    :(qnorm_signal◖F◗ - qnorm(probability_signal◖F◗)),
    :(pnorm_signal◖F◗ - pnorm(a◖F◗ - 1)),
    :(dnorm_signal◖F◗ - dnorm(a◖F◗ - 1)),
    :(steady_gap◖F◗ - (y◖F◗ - y◖F◗)),
    :(κ◖F◗◖A◗ - (0.25κ◖F◗◖A◗ + 0.25κ◖F◗◖A◗ + λ◖A◗ * ifelse(ifelse_switch > 0.5, χ◖A◗, 1 - χ◖A◗) + shock_scale * 0 + shock_scale * 0)),
    :(κ◖F◗◖B◗ - (0.25κ◖F◗◖B◗ + 0.25κ◖F◗◖B◗ + λ◖B◗ * ifelse(ifelse_switch > 0.5, χ◖B◗, 1 - χ◖B◗) + shock_scale * 0 + shock_scale * 0)),
    :(world_output - (y◖H◗ + y◖F◗)),
    :(relative_output - (y◖H◗ / y◖F◗) / (y◖H◗ / y◖F◗)),
    :(net_exports◖H◗ - trade_weight◖H◗◖F◗ * (y◖H◗ - y◖F◗)),
    :(net_exports◖F◗ - trade_weight◖F◗◖H◗ * (y◖F◗ - y◖H◗)),
    :(ϵᵒᵇᶜ⁺ꜝ¹ꜝ - ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻⁴⁾),
    :(ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻⁰⁾ - activeᵒᵇᶜshocks * 0),
    :(ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻¹⁾ - (ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻⁰⁾ + activeᵒᵇᶜshocks * 0)),
    :(ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻²⁾ - (ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻¹⁾ + activeᵒᵇᶜshocks * 0)),
    :(ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻³⁾ - (ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻²⁾ + activeᵒᵇᶜshocks * 0)),
    :(ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻⁴⁾ - (ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻³⁾ + activeᵒᵇᶜshocks * 0)),
    :(ϵᵒᵇᶜ⁻ꜝ²ꜝ - ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻⁴⁾),
    :(ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻⁰⁾ - activeᵒᵇᶜshocks * 0),
    :(ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻¹⁾ - (ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻⁰⁾ + activeᵒᵇᶜshocks * 0)),
    :(ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻²⁾ - (ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻¹⁾ + activeᵒᵇᶜshocks * 0)),
    :(ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻³⁾ - (ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻²⁾ + activeᵒᵇᶜshocks * 0)),
    :(ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻⁴⁾ - (ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻³⁾ + activeᵒᵇᶜshocks * 0)),
    :(ϵᵒᵇᶜ⁺ꜝ³ꜝ - ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻⁴⁾),
    :(ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻⁰⁾ - activeᵒᵇᶜshocks * 0),
    :(ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻¹⁾ - (ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻⁰⁾ + activeᵒᵇᶜshocks * 0)),
    :(ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻²⁾ - (ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻¹⁾ + activeᵒᵇᶜshocks * 0)),
    :(ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻³⁾ - (ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻²⁾ + activeᵒᵇᶜshocks * 0)),
    :(ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻⁴⁾ - (ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻³⁾ + activeᵒᵇᶜshocks * 0)),
    :(ϵᵒᵇᶜ⁻ꜝ⁴ꜝ - ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻⁴⁾),
    :(ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻⁰⁾ - activeᵒᵇᶜshocks * 0),
    :(ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻¹⁾ - (ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻⁰⁾ + activeᵒᵇᶜshocks * 0)),
    :(ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻²⁾ - (ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻¹⁾ + activeᵒᵇᶜshocks * 0)),
    :(ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻³⁾ - (ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻²⁾ + activeᵒᵇᶜshocks * 0)),
    :(ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻⁴⁾ - (ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻³⁾ + activeᵒᵇᶜshocks * 0)),
    :(r◖H◗ - rate_target),
    :(y◖H◗ - output_target),
]
const AUXILIARY_RESIDUAL_EQUATIONS = Expr[
    :(-a◖H◗ * k◖H◗ ^ alpha◖H◗ + y◖H◗),
    :(-consumption_share * y◖H◗ + c◖H◗),
    :(-investment_share * y◖H◗ + i◖H◗),
    :(((-c◖H◗ - g◖H◗) - i◖H◗) + y◖H◗),
    :((-i◖H◗ - k◖H◗ * (1 - delta)) + k◖H◗),
    :((-a◖H◗ * rho + a◖H◗ + rho) - 1),
    :(-rate_floor + r◖H◗ + χᵒᵇᶜ⁺ꜝ¹ꜝˡ),
    :((r◖H◗ + χᵒᵇᶜ⁺ꜝ¹ꜝʳ) - 1 / beta),
    :(Χᵒᵇᶜ⁺ꜝ¹ꜝ - Max(χᵒᵇᶜ⁺ꜝ¹ꜝʳ, χᵒᵇᶜ⁺ꜝ¹ꜝˡ)),
    :(Χᵒᵇᶜ⁺ꜝ¹ꜝ - ϵᵒᵇᶜ⁺ꜝ¹ꜝ),
    :(-tax_cap + tax◖H◗ + χᵒᵇᶜ⁻ꜝ²ꜝˡ),
    :((-tax_base - tax_rate * y◖H◗) + tax◖H◗ + χᵒᵇᶜ⁻ꜝ²ꜝʳ),
    :(Χᵒᵇᶜ⁻ꜝ²ꜝ - Min(χᵒᵇᶜ⁻ꜝ²ꜝʳ, χᵒᵇᶜ⁻ꜝ²ꜝˡ)),
    :(Χᵒᵇᶜ⁻ꜝ²ꜝ - ϵᵒᵇᶜ⁻ꜝ²ꜝ),
    :(sales_window◖H◗ - 3y◖H◗),
    :(forward_anchor◖H◗ - 0),
    :(inflation_product◖H◗ - inflation◖H◗ ^ 3),
    :(-inflation_bar + inflation◖H◗),
    :((cdf_signal◖H◗ + erfc(0.707106781186547a◖H◗ - 0.707106781186547) / 2) - 1),
    :(pdf_signal◖H◗ - 0.398942280401433 * exp(-((a◖H◗ - 1) ^ 2) / 2)),
    :(logpdf_signal◖H◗ + (a◖H◗ - 1) ^ 2 / 2 + 0.918938533204673),
    :((probability_signal◖H◗ - 0.25 * tanh(a◖H◗ - 1)) - 0.5),
    :(inverse_signal◖H◗ + 1.4142135623731 * erfcinv(2probability_signal◖H◗)),
    :(norminv_signal◖H◗ + 1.4142135623731 * erfcinv(2probability_signal◖H◗)),
    :(qnorm_signal◖H◗ + 1.4142135623731 * erfcinv(2probability_signal◖H◗)),
    :((pnorm_signal◖H◗ + erfc(0.707106781186547a◖H◗ - 0.707106781186547) / 2) - 1),
    :(dnorm_signal◖H◗ - 0.398942280401433 * exp(-((a◖H◗ - 1) ^ 2) / 2)),
    :(steady_gap◖H◗ - 0),
    :(0.5κ◖H◗◖A◗ - λ◖A◗ * (1 - χ◖A◗)),
    :(0.5κ◖H◗◖B◗ - λ◖B◗ * (1 - χ◖B◗)),
    :(-a◖F◗ * foreign_scale * k◖F◗ ^ alpha◖F◗ + y◖F◗),
    :(-consumption_share * y◖F◗ + c◖F◗),
    :(-investment_share * y◖F◗ + i◖F◗),
    :(((-c◖F◗ - g◖F◗) - i◖F◗) + y◖F◗),
    :((-i◖F◗ - k◖F◗ * (1 - delta)) + k◖F◗),
    :((-a◖F◗ * rho + a◖F◗ + rho) - 1),
    :(-rate_floor + r◖F◗ + χᵒᵇᶜ⁺ꜝ³ꜝˡ),
    :((r◖F◗ + χᵒᵇᶜ⁺ꜝ³ꜝʳ) - 1 / beta),
    :(Χᵒᵇᶜ⁺ꜝ³ꜝ - Max(χᵒᵇᶜ⁺ꜝ³ꜝʳ, χᵒᵇᶜ⁺ꜝ³ꜝˡ)),
    :(Χᵒᵇᶜ⁺ꜝ³ꜝ - ϵᵒᵇᶜ⁺ꜝ³ꜝ),
    :(-tax_cap + tax◖F◗ + χᵒᵇᶜ⁻ꜝ⁴ꜝˡ),
    :((-tax_base - tax_rate * y◖F◗) + tax◖F◗ + χᵒᵇᶜ⁻ꜝ⁴ꜝʳ),
    :(Χᵒᵇᶜ⁻ꜝ⁴ꜝ - Min(χᵒᵇᶜ⁻ꜝ⁴ꜝʳ, χᵒᵇᶜ⁻ꜝ⁴ꜝˡ)),
    :(Χᵒᵇᶜ⁻ꜝ⁴ꜝ - ϵᵒᵇᶜ⁻ꜝ⁴ꜝ),
    :(sales_window◖F◗ - 3y◖F◗),
    :(forward_anchor◖F◗ - 0),
    :(inflation_product◖F◗ - inflation◖F◗ ^ 3),
    :(-inflation_bar + inflation◖F◗),
    :((cdf_signal◖F◗ + erfc(0.707106781186547a◖F◗ - 0.707106781186547) / 2) - 1),
    :(pdf_signal◖F◗ - 0.398942280401433 * exp(-((a◖F◗ - 1) ^ 2) / 2)),
    :(logpdf_signal◖F◗ + (a◖F◗ - 1) ^ 2 / 2 + 0.918938533204673),
    :((probability_signal◖F◗ - 0.25 * tanh(a◖F◗ - 1)) - 0.5),
    :(inverse_signal◖F◗ + 1.4142135623731 * erfcinv(2probability_signal◖F◗)),
    :(norminv_signal◖F◗ + 1.4142135623731 * erfcinv(2probability_signal◖F◗)),
    :(qnorm_signal◖F◗ + 1.4142135623731 * erfcinv(2probability_signal◖F◗)),
    :((pnorm_signal◖F◗ + erfc(0.707106781186547a◖F◗ - 0.707106781186547) / 2) - 1),
    :(dnorm_signal◖F◗ - 0.398942280401433 * exp(-((a◖F◗ - 1) ^ 2) / 2)),
    :(steady_gap◖F◗ - 0),
    :(0.5κ◖F◗◖A◗ - λ◖A◗ * (1 - χ◖A◗)),
    :(0.5κ◖F◗◖B◗ - λ◖B◗ * (1 - χ◖B◗)),
    :((world_output - y◖F◗) - y◖H◗),
    :(relative_output - 1),
    :(net_exports◖H◗ - trade_weight◖H◗◖F◗ * (-y◖F◗ + y◖H◗)),
    :(net_exports◖F◗ - trade_weight◖F◗◖H◗ * (y◖F◗ - y◖H◗)),
    :(ϵᵒᵇᶜ⁺ꜝ¹ꜝ - ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻⁴⁾),
    :(ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻⁰⁾ - 0),
    :(ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻¹⁾ - ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻⁰⁾),
    :(ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻²⁾ - ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻¹⁾),
    :(-ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻²⁾ + ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻³⁾),
    :(-ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻³⁾ + ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻⁴⁾),
    :(ϵᵒᵇᶜ⁻ꜝ²ꜝ - ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻⁴⁾),
    :(ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻⁰⁾ - 0),
    :(ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻¹⁾ - ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻⁰⁾),
    :(ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻²⁾ - ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻¹⁾),
    :(-ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻²⁾ + ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻³⁾),
    :(-ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻³⁾ + ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻⁴⁾),
    :(ϵᵒᵇᶜ⁺ꜝ³ꜝ - ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻⁴⁾),
    :(ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻⁰⁾ - 0),
    :(ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻¹⁾ - ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻⁰⁾),
    :(ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻²⁾ - ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻¹⁾),
    :(-ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻²⁾ + ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻³⁾),
    :(-ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻³⁾ + ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻⁴⁾),
    :(ϵᵒᵇᶜ⁻ꜝ⁴ꜝ - ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻⁴⁾),
    :(ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻⁰⁾ - 0),
    :(ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻¹⁾ - ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻⁰⁾),
    :(ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻²⁾ - ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻¹⁾),
    :(-ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻²⁾ + ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻³⁾),
    :(-ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻³⁾ + ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻⁴⁾),
    :(r◖H◗ - rate_target),
    :(y◖H◗ - output_target),
]

const PARAMETER_DEFINITION_NAMES = [
    "foreign_scale",
    "investment_share",
    "rate_target",
]
const PARAMETER_DEFINITION_EXPRESSIONS = [
    "1 - foreign_gap",
    "delta * 3",
    "1 + inflation_target",
]
const PARAMETER_BOX_CONSTRAINT_NAMES = [
    "rho",
    "sigma",
    "consumption_share",
    "foreign_gap",
    "inflation_bar",
    "inflation_shock",
    "rate_floor",
    "tax_cap",
    "tax_base",
    "tax_rate",
    "ifelse_switch",
    "shock_scale",
    "trade_weight{H}{F}",
    "trade_weight{F}{H}",
    "λ{A}",
    "λ{B}",
    "χ{A}",
    "χ{B}",
    "alpha{F}",
    "output_target",
    "inflation_target",
    "delta",
    "activeᵒᵇᶜshocks",
]
const PARAMETER_BOX_LOWER_BOUNDS = Float64[
    1.1920928955078125e-7,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    1.1920928955078125e-7,
    -Inf,
    -Inf,
    1.1920928955078125e-7,
    -Inf,
]
const PARAMETER_BOX_UPPER_BOUNDS = Float64[
    0.9999998807907104,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    0.9999998807907104,
    Inf,
    Inf,
    0.9999998807907104,
    Inf,
]
const ORIGINAL_BOX_CONSTRAINT_NAMES = [
    "a{F}",
    "a{H}",
    "cdf_signal{F}",
    "cdf_signal{H}",
    "c{F}",
    "c{H}",
    "dnorm_signal{F}",
    "dnorm_signal{H}",
    "forward_anchor{F}",
    "forward_anchor{H}",
    "g{F}",
    "g{H}",
    "inflation_product{F}",
    "inflation_product{H}",
    "inflation{F}",
    "inflation{H}",
    "inverse_signal{F}",
    "inverse_signal{H}",
    "i{F}",
    "i{H}",
    "k{F}",
    "k{H}",
    "logpdf_signal{F}",
    "logpdf_signal{H}",
    "net_exports{F}",
    "net_exports{H}",
    "norminv_signal{F}",
    "norminv_signal{H}",
    "pdf_signal{F}",
    "pdf_signal{H}",
    "pnorm_signal{F}",
    "pnorm_signal{H}",
    "probability_signal{F}",
    "probability_signal{H}",
    "qnorm_signal{F}",
    "qnorm_signal{H}",
    "relative_output",
    "r{F}",
    "r{H}",
    "sales_window{F}",
    "sales_window{H}",
    "steady_gap{F}",
    "steady_gap{H}",
    "tax{F}",
    "tax{H}",
    "world_output",
    "y{F}",
    "y{H}",
    "Χᵒᵇᶜ⁺ꜝ³ꜝ",
    "Χᵒᵇᶜ⁺ꜝ¹ꜝ",
    "Χᵒᵇᶜ⁻ꜝ²ꜝ",
    "Χᵒᵇᶜ⁻ꜝ⁴ꜝ",
    "κ{F}{A}",
    "κ{F}{B}",
    "κ{H}{A}",
    "κ{H}{B}",
    "χᵒᵇᶜ⁺ꜝ³ꜝʳ",
    "χᵒᵇᶜ⁺ꜝ³ꜝˡ",
    "χᵒᵇᶜ⁺ꜝ¹ꜝʳ",
    "χᵒᵇᶜ⁺ꜝ¹ꜝˡ",
    "χᵒᵇᶜ⁻ꜝ²ꜝʳ",
    "χᵒᵇᶜ⁻ꜝ²ꜝˡ",
    "χᵒᵇᶜ⁻ꜝ⁴ꜝʳ",
    "χᵒᵇᶜ⁻ꜝ⁴ꜝˡ",
    "ϵᵒᵇᶜ⁺ꜝ³ꜝ",
    "ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻²⁾",
    "ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻³⁾",
    "ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻¹⁾",
    "ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻⁰⁾",
    "ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻⁴⁾",
    "ϵᵒᵇᶜ⁺ꜝ¹ꜝ",
    "ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻²⁾",
    "ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻³⁾",
    "ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻¹⁾",
    "ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻⁰⁾",
    "ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻⁴⁾",
    "ϵᵒᵇᶜ⁻ꜝ²ꜝ",
    "ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻²⁾",
    "ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻³⁾",
    "ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻¹⁾",
    "ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻⁰⁾",
    "ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻⁴⁾",
    "ϵᵒᵇᶜ⁻ꜝ⁴ꜝ",
    "ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻²⁾",
    "ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻³⁾",
    "ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻¹⁾",
    "ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻⁰⁾",
    "ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻⁴⁾",
    "beta",
    "alpha{H}",
]
const ORIGINAL_BOX_LOWER_BOUNDS = Float64[
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -1.0e12,
    -Inf,
    2.220446049250313e-16,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -1.0e12,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -1.0e12,
    -1.0e12,
    -Inf,
    -1.0e12,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -1.0e12,
    -1.0e12,
    -1.0e12,
    -Inf,
    -1.0e12,
    -1.0e12,
    -1.0e12,
    -1.0e12,
    -Inf,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    -Inf,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    -Inf,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    -Inf,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    1.1920928955078125e-7,
    1.1920928955078125e-7,
]
const ORIGINAL_BOX_UPPER_BOUNDS = Float64[
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    1.0e12,
    Inf,
    1.0e12,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    1.0e12,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    1.0e12,
    1.0e12,
    Inf,
    1.0e12,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    1.0e12,
    1.0e12,
    1.0e12,
    Inf,
    1.0e12,
    1.0e12,
    1.0e12,
    1.0e12,
    Inf,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    Inf,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    Inf,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    Inf,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.9999998807907104,
    0.9999998807907104,
]
const AUXILIARY_BOX_CONSTRAINT_NAMES = [
    "a{F}",
    "a{H}",
    "cdf_signal{F}",
    "cdf_signal{H}",
    "c{F}",
    "c{H}",
    "dnorm_signal{F}",
    "dnorm_signal{H}",
    "forward_anchor{F}",
    "forward_anchor{H}",
    "g{F}",
    "g{H}",
    "inflation_product{F}",
    "inflation_product{H}",
    "inflation{F}",
    "inflation{H}",
    "inverse_signal{F}",
    "inverse_signal{H}",
    "i{F}",
    "i{H}",
    "k{F}",
    "k{H}",
    "logpdf_signal{F}",
    "logpdf_signal{H}",
    "net_exports{F}",
    "net_exports{H}",
    "norminv_signal{F}",
    "norminv_signal{H}",
    "pdf_signal{F}",
    "pdf_signal{H}",
    "pnorm_signal{F}",
    "pnorm_signal{H}",
    "probability_signal{F}",
    "probability_signal{H}",
    "qnorm_signal{F}",
    "qnorm_signal{H}",
    "relative_output",
    "r{F}",
    "r{H}",
    "sales_window{F}",
    "sales_window{H}",
    "steady_gap{F}",
    "steady_gap{H}",
    "tax{F}",
    "tax{H}",
    "world_output",
    "y{F}",
    "y{H}",
    "Χᵒᵇᶜ⁺ꜝ³ꜝ",
    "Χᵒᵇᶜ⁺ꜝ¹ꜝ",
    "Χᵒᵇᶜ⁻ꜝ²ꜝ",
    "Χᵒᵇᶜ⁻ꜝ⁴ꜝ",
    "κ{F}{A}",
    "κ{F}{B}",
    "κ{H}{A}",
    "κ{H}{B}",
    "χᵒᵇᶜ⁺ꜝ³ꜝʳ",
    "χᵒᵇᶜ⁺ꜝ³ꜝˡ",
    "χᵒᵇᶜ⁺ꜝ¹ꜝʳ",
    "χᵒᵇᶜ⁺ꜝ¹ꜝˡ",
    "χᵒᵇᶜ⁻ꜝ²ꜝʳ",
    "χᵒᵇᶜ⁻ꜝ²ꜝˡ",
    "χᵒᵇᶜ⁻ꜝ⁴ꜝʳ",
    "χᵒᵇᶜ⁻ꜝ⁴ꜝˡ",
    "ϵᵒᵇᶜ⁺ꜝ³ꜝ",
    "ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻²⁾",
    "ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻³⁾",
    "ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻¹⁾",
    "ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻⁰⁾",
    "ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻⁴⁾",
    "ϵᵒᵇᶜ⁺ꜝ¹ꜝ",
    "ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻²⁾",
    "ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻³⁾",
    "ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻¹⁾",
    "ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻⁰⁾",
    "ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻⁴⁾",
    "ϵᵒᵇᶜ⁻ꜝ²ꜝ",
    "ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻²⁾",
    "ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻³⁾",
    "ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻¹⁾",
    "ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻⁰⁾",
    "ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻⁴⁾",
    "ϵᵒᵇᶜ⁻ꜝ⁴ꜝ",
    "ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻²⁾",
    "ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻³⁾",
    "ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻¹⁾",
    "ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻⁰⁾",
    "ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻⁴⁾",
    "beta",
    "alpha{H}",
]
const AUXILIARY_BOX_LOWER_BOUNDS = Float64[
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -1.0e12,
    -Inf,
    2.220446049250313e-16,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -1.0e12,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -1.0e12,
    -1.0e12,
    -Inf,
    -1.0e12,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -1.0e12,
    -1.0e12,
    -1.0e12,
    -Inf,
    -1.0e12,
    -1.0e12,
    -1.0e12,
    -1.0e12,
    -Inf,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    -Inf,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    -Inf,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    -Inf,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    1.1920928955078125e-7,
    1.1920928955078125e-7,
]
const AUXILIARY_BOX_UPPER_BOUNDS = Float64[
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    1.0e12,
    Inf,
    1.0e12,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    1.0e12,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    1.0e12,
    1.0e12,
    Inf,
    1.0e12,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    1.0e12,
    1.0e12,
    1.0e12,
    Inf,
    1.0e12,
    1.0e12,
    1.0e12,
    1.0e12,
    Inf,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    Inf,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    Inf,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    Inf,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.9999998807907104,
    0.9999998807907104,
]
const ALL_AUXILIARY_BOX_CONSTRAINT_NAMES = [
    "➕₁",
    "➕₂",
]
const ALL_AUXILIARY_BOX_LOWER_BOUNDS = Float64[
    2.220446049250313e-16,
    2.220446049250313e-16,
]
const ALL_AUXILIARY_BOX_UPPER_BOUNDS = Float64[
    1.0e12,
    1.0e12,
]

const BLOCKS = [
    (
        index = 1,
        variables = ["alpha{H}"],
        equation_indices = [1],
        equations = Expr[
            :(-a◖H◗ * k◖H◗ ^ alpha◖H◗ + y◖H◗),
        ],
    ),
    (
        index = 2,
        variables = ["κ{H}{B}"],
        equation_indices = [30],
        equations = Expr[
            :(0.5κ◖H◗◖B◗ - λ◖B◗ * (1 - χ◖B◗)),
        ],
    ),
    (
        index = 3,
        variables = ["κ{H}{A}"],
        equation_indices = [29],
        equations = Expr[
            :(0.5κ◖H◗◖A◗ - λ◖A◗ * (1 - χ◖A◗)),
        ],
    ),
    (
        index = 4,
        variables = ["κ{F}{B}"],
        equation_indices = [60],
        equations = Expr[
            :(0.5κ◖F◗◖B◗ - λ◖B◗ * (1 - χ◖B◗)),
        ],
    ),
    (
        index = 5,
        variables = ["κ{F}{A}"],
        equation_indices = [59],
        equations = Expr[
            :(0.5κ◖F◗◖A◗ - λ◖A◗ * (1 - χ◖A◗)),
        ],
    ),
    (
        index = 6,
        variables = ["world_output"],
        equation_indices = [61],
        equations = Expr[
            :((world_output - y◖F◗) - y◖H◗),
        ],
    ),
    (
        index = 7,
        variables = ["tax{H}", "χᵒᵇᶜ⁻ꜝ²ꜝʳ", "χᵒᵇᶜ⁻ꜝ²ꜝˡ"],
        equation_indices = [11, 12, 13],
        equations = Expr[
            :(-tax_cap + tax◖H◗ + χᵒᵇᶜ⁻ꜝ²ꜝˡ),
            :((-tax_base - tax_rate * y◖H◗) + tax◖H◗ + χᵒᵇᶜ⁻ꜝ²ꜝʳ),
            :(Χᵒᵇᶜ⁻ꜝ²ꜝ - Min(χᵒᵇᶜ⁻ꜝ²ꜝʳ, χᵒᵇᶜ⁻ꜝ²ꜝˡ)),
        ],
    ),
    (
        index = 8,
        variables = ["Χᵒᵇᶜ⁻ꜝ²ꜝ"],
        equation_indices = [14],
        equations = Expr[
            :(Χᵒᵇᶜ⁻ꜝ²ꜝ - ϵᵒᵇᶜ⁻ꜝ²ꜝ),
        ],
    ),
    (
        index = 9,
        variables = ["ϵᵒᵇᶜ⁻ꜝ²ꜝ"],
        equation_indices = [71],
        equations = Expr[
            :(ϵᵒᵇᶜ⁻ꜝ²ꜝ - ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻⁴⁾),
        ],
    ),
    (
        index = 10,
        variables = ["ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻⁴⁾"],
        equation_indices = [76],
        equations = Expr[
            :(-ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻³⁾ + ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻⁴⁾),
        ],
    ),
    (
        index = 11,
        variables = ["ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻³⁾"],
        equation_indices = [75],
        equations = Expr[
            :(-ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻²⁾ + ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻³⁾),
        ],
    ),
    (
        index = 12,
        variables = ["ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻²⁾"],
        equation_indices = [74],
        equations = Expr[
            :(ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻²⁾ - ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻¹⁾),
        ],
    ),
    (
        index = 13,
        variables = ["ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻¹⁾"],
        equation_indices = [73],
        equations = Expr[
            :(ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻¹⁾ - ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻⁰⁾),
        ],
    ),
    (
        index = 14,
        variables = ["ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻⁰⁾"],
        equation_indices = [72],
        equations = Expr[
            :(ϵᵒᵇᶜ⁻ꜝ²ꜝᴸ⁽⁻⁰⁾ - 0),
        ],
    ),
    (
        index = 15,
        variables = ["tax{F}", "χᵒᵇᶜ⁻ꜝ⁴ꜝʳ", "χᵒᵇᶜ⁻ꜝ⁴ꜝˡ"],
        equation_indices = [41, 42, 43],
        equations = Expr[
            :(-tax_cap + tax◖F◗ + χᵒᵇᶜ⁻ꜝ⁴ꜝˡ),
            :((-tax_base - tax_rate * y◖F◗) + tax◖F◗ + χᵒᵇᶜ⁻ꜝ⁴ꜝʳ),
            :(Χᵒᵇᶜ⁻ꜝ⁴ꜝ - Min(χᵒᵇᶜ⁻ꜝ⁴ꜝʳ, χᵒᵇᶜ⁻ꜝ⁴ꜝˡ)),
        ],
    ),
    (
        index = 16,
        variables = ["Χᵒᵇᶜ⁻ꜝ⁴ꜝ"],
        equation_indices = [44],
        equations = Expr[
            :(Χᵒᵇᶜ⁻ꜝ⁴ꜝ - ϵᵒᵇᶜ⁻ꜝ⁴ꜝ),
        ],
    ),
    (
        index = 17,
        variables = ["ϵᵒᵇᶜ⁻ꜝ⁴ꜝ"],
        equation_indices = [83],
        equations = Expr[
            :(ϵᵒᵇᶜ⁻ꜝ⁴ꜝ - ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻⁴⁾),
        ],
    ),
    (
        index = 18,
        variables = ["ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻⁴⁾"],
        equation_indices = [88],
        equations = Expr[
            :(-ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻³⁾ + ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻⁴⁾),
        ],
    ),
    (
        index = 19,
        variables = ["ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻³⁾"],
        equation_indices = [87],
        equations = Expr[
            :(-ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻²⁾ + ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻³⁾),
        ],
    ),
    (
        index = 20,
        variables = ["ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻²⁾"],
        equation_indices = [86],
        equations = Expr[
            :(ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻²⁾ - ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻¹⁾),
        ],
    ),
    (
        index = 21,
        variables = ["ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻¹⁾"],
        equation_indices = [85],
        equations = Expr[
            :(ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻¹⁾ - ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻⁰⁾),
        ],
    ),
    (
        index = 22,
        variables = ["ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻⁰⁾"],
        equation_indices = [84],
        equations = Expr[
            :(ϵᵒᵇᶜ⁻ꜝ⁴ꜝᴸ⁽⁻⁰⁾ - 0),
        ],
    ),
    (
        index = 23,
        variables = ["steady_gap{H}"],
        equation_indices = [28],
        equations = Expr[
            :(steady_gap◖H◗ - 0),
        ],
    ),
    (
        index = 24,
        variables = ["steady_gap{F}"],
        equation_indices = [58],
        equations = Expr[
            :(steady_gap◖F◗ - 0),
        ],
    ),
    (
        index = 25,
        variables = ["sales_window{H}"],
        equation_indices = [15],
        equations = Expr[
            :(sales_window◖H◗ - 3y◖H◗),
        ],
    ),
    (
        index = 26,
        variables = ["sales_window{F}"],
        equation_indices = [45],
        equations = Expr[
            :(sales_window◖F◗ - 3y◖F◗),
        ],
    ),
    (
        index = 27,
        variables = ["r{F}", "χᵒᵇᶜ⁺ꜝ³ꜝʳ", "χᵒᵇᶜ⁺ꜝ³ꜝˡ"],
        equation_indices = [37, 38, 39],
        equations = Expr[
            :(-rate_floor + r◖F◗ + χᵒᵇᶜ⁺ꜝ³ꜝˡ),
            :((r◖F◗ + χᵒᵇᶜ⁺ꜝ³ꜝʳ) - 1 / beta),
            :(Χᵒᵇᶜ⁺ꜝ³ꜝ - Max(χᵒᵇᶜ⁺ꜝ³ꜝʳ, χᵒᵇᶜ⁺ꜝ³ꜝˡ)),
        ],
    ),
    (
        index = 28,
        variables = ["beta"],
        equation_indices = [8],
        equations = Expr[
            :((r◖H◗ + χᵒᵇᶜ⁺ꜝ¹ꜝʳ) - 1 / beta),
        ],
    ),
    (
        index = 29,
        variables = ["χᵒᵇᶜ⁺ꜝ¹ꜝʳ"],
        equation_indices = [9],
        equations = Expr[
            :(Χᵒᵇᶜ⁺ꜝ¹ꜝ - Max(χᵒᵇᶜ⁺ꜝ¹ꜝʳ, χᵒᵇᶜ⁺ꜝ¹ꜝˡ)),
        ],
    ),
    (
        index = 30,
        variables = ["χᵒᵇᶜ⁺ꜝ¹ꜝˡ"],
        equation_indices = [7],
        equations = Expr[
            :(-rate_floor + r◖H◗ + χᵒᵇᶜ⁺ꜝ¹ꜝˡ),
        ],
    ),
    (
        index = 31,
        variables = ["Χᵒᵇᶜ⁺ꜝ¹ꜝ"],
        equation_indices = [10],
        equations = Expr[
            :(Χᵒᵇᶜ⁺ꜝ¹ꜝ - ϵᵒᵇᶜ⁺ꜝ¹ꜝ),
        ],
    ),
    (
        index = 32,
        variables = ["ϵᵒᵇᶜ⁺ꜝ¹ꜝ"],
        equation_indices = [65],
        equations = Expr[
            :(ϵᵒᵇᶜ⁺ꜝ¹ꜝ - ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻⁴⁾),
        ],
    ),
    (
        index = 33,
        variables = ["ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻⁴⁾"],
        equation_indices = [70],
        equations = Expr[
            :(-ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻³⁾ + ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻⁴⁾),
        ],
    ),
    (
        index = 34,
        variables = ["ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻³⁾"],
        equation_indices = [69],
        equations = Expr[
            :(-ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻²⁾ + ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻³⁾),
        ],
    ),
    (
        index = 35,
        variables = ["ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻²⁾"],
        equation_indices = [68],
        equations = Expr[
            :(ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻²⁾ - ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻¹⁾),
        ],
    ),
    (
        index = 36,
        variables = ["ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻¹⁾"],
        equation_indices = [67],
        equations = Expr[
            :(ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻¹⁾ - ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻⁰⁾),
        ],
    ),
    (
        index = 37,
        variables = ["ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻⁰⁾"],
        equation_indices = [66],
        equations = Expr[
            :(ϵᵒᵇᶜ⁺ꜝ¹ꜝᴸ⁽⁻⁰⁾ - 0),
        ],
    ),
    (
        index = 38,
        variables = ["r{H}"],
        equation_indices = [89],
        equations = Expr[
            :(r◖H◗ - rate_target),
        ],
    ),
    (
        index = 39,
        variables = ["Χᵒᵇᶜ⁺ꜝ³ꜝ"],
        equation_indices = [40],
        equations = Expr[
            :(Χᵒᵇᶜ⁺ꜝ³ꜝ - ϵᵒᵇᶜ⁺ꜝ³ꜝ),
        ],
    ),
    (
        index = 40,
        variables = ["ϵᵒᵇᶜ⁺ꜝ³ꜝ"],
        equation_indices = [77],
        equations = Expr[
            :(ϵᵒᵇᶜ⁺ꜝ³ꜝ - ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻⁴⁾),
        ],
    ),
    (
        index = 41,
        variables = ["ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻⁴⁾"],
        equation_indices = [82],
        equations = Expr[
            :(-ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻³⁾ + ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻⁴⁾),
        ],
    ),
    (
        index = 42,
        variables = ["ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻³⁾"],
        equation_indices = [81],
        equations = Expr[
            :(-ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻²⁾ + ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻³⁾),
        ],
    ),
    (
        index = 43,
        variables = ["ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻²⁾"],
        equation_indices = [80],
        equations = Expr[
            :(ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻²⁾ - ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻¹⁾),
        ],
    ),
    (
        index = 44,
        variables = ["ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻¹⁾"],
        equation_indices = [79],
        equations = Expr[
            :(ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻¹⁾ - ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻⁰⁾),
        ],
    ),
    (
        index = 45,
        variables = ["ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻⁰⁾"],
        equation_indices = [78],
        equations = Expr[
            :(ϵᵒᵇᶜ⁺ꜝ³ꜝᴸ⁽⁻⁰⁾ - 0),
        ],
    ),
    (
        index = 46,
        variables = ["relative_output"],
        equation_indices = [62],
        equations = Expr[
            :(relative_output - 1),
        ],
    ),
    (
        index = 47,
        variables = ["qnorm_signal{H}"],
        equation_indices = [25],
        equations = Expr[
            :(qnorm_signal◖H◗ + 1.4142135623731 * erfcinv(2probability_signal◖H◗)),
        ],
    ),
    (
        index = 48,
        variables = ["qnorm_signal{F}"],
        equation_indices = [55],
        equations = Expr[
            :(qnorm_signal◖F◗ + 1.4142135623731 * erfcinv(2probability_signal◖F◗)),
        ],
    ),
    (
        index = 49,
        variables = ["pnorm_signal{H}"],
        equation_indices = [26],
        equations = Expr[
            :((pnorm_signal◖H◗ + erfc(0.707106781186547a◖H◗ - 0.707106781186547) / 2) - 1),
        ],
    ),
    (
        index = 50,
        variables = ["pnorm_signal{F}"],
        equation_indices = [56],
        equations = Expr[
            :((pnorm_signal◖F◗ + erfc(0.707106781186547a◖F◗ - 0.707106781186547) / 2) - 1),
        ],
    ),
    (
        index = 51,
        variables = ["pdf_signal{H}"],
        equation_indices = [20],
        equations = Expr[
            :(pdf_signal◖H◗ - 0.398942280401433 * exp(-((a◖H◗ - 1) ^ 2) / 2)),
        ],
    ),
    (
        index = 52,
        variables = ["pdf_signal{F}"],
        equation_indices = [50],
        equations = Expr[
            :(pdf_signal◖F◗ - 0.398942280401433 * exp(-((a◖F◗ - 1) ^ 2) / 2)),
        ],
    ),
    (
        index = 53,
        variables = ["norminv_signal{H}"],
        equation_indices = [24],
        equations = Expr[
            :(norminv_signal◖H◗ + 1.4142135623731 * erfcinv(2probability_signal◖H◗)),
        ],
    ),
    (
        index = 54,
        variables = ["norminv_signal{F}"],
        equation_indices = [54],
        equations = Expr[
            :(norminv_signal◖F◗ + 1.4142135623731 * erfcinv(2probability_signal◖F◗)),
        ],
    ),
    (
        index = 55,
        variables = ["net_exports{H}"],
        equation_indices = [63],
        equations = Expr[
            :(net_exports◖H◗ - trade_weight◖H◗◖F◗ * (-y◖F◗ + y◖H◗)),
        ],
    ),
    (
        index = 56,
        variables = ["net_exports{F}"],
        equation_indices = [64],
        equations = Expr[
            :(net_exports◖F◗ - trade_weight◖F◗◖H◗ * (y◖F◗ - y◖H◗)),
        ],
    ),
    (
        index = 57,
        variables = ["logpdf_signal{H}"],
        equation_indices = [21],
        equations = Expr[
            :(logpdf_signal◖H◗ + (a◖H◗ - 1) ^ 2 / 2 + 0.918938533204673),
        ],
    ),
    (
        index = 58,
        variables = ["logpdf_signal{F}"],
        equation_indices = [51],
        equations = Expr[
            :(logpdf_signal◖F◗ + (a◖F◗ - 1) ^ 2 / 2 + 0.918938533204673),
        ],
    ),
    (
        index = 59,
        variables = ["k{H}"],
        equation_indices = [5],
        equations = Expr[
            :((-i◖H◗ - k◖H◗ * (1 - delta)) + k◖H◗),
        ],
    ),
    (
        index = 60,
        variables = ["inverse_signal{H}"],
        equation_indices = [23],
        equations = Expr[
            :(inverse_signal◖H◗ + 1.4142135623731 * erfcinv(2probability_signal◖H◗)),
        ],
    ),
    (
        index = 61,
        variables = ["probability_signal{H}"],
        equation_indices = [22],
        equations = Expr[
            :((probability_signal◖H◗ - 0.25 * tanh(a◖H◗ - 1)) - 0.5),
        ],
    ),
    (
        index = 62,
        variables = ["inverse_signal{F}"],
        equation_indices = [53],
        equations = Expr[
            :(inverse_signal◖F◗ + 1.4142135623731 * erfcinv(2probability_signal◖F◗)),
        ],
    ),
    (
        index = 63,
        variables = ["probability_signal{F}"],
        equation_indices = [52],
        equations = Expr[
            :((probability_signal◖F◗ - 0.25 * tanh(a◖F◗ - 1)) - 0.5),
        ],
    ),
    (
        index = 64,
        variables = ["inflation_product{H}"],
        equation_indices = [17],
        equations = Expr[
            :(inflation_product◖H◗ - inflation◖H◗ ^ 3),
        ],
    ),
    (
        index = 65,
        variables = ["inflation{H}"],
        equation_indices = [18],
        equations = Expr[
            :(-inflation_bar + inflation◖H◗),
        ],
    ),
    (
        index = 66,
        variables = ["inflation_product{F}"],
        equation_indices = [47],
        equations = Expr[
            :(inflation_product◖F◗ - inflation◖F◗ ^ 3),
        ],
    ),
    (
        index = 67,
        variables = ["inflation{F}"],
        equation_indices = [48],
        equations = Expr[
            :(-inflation_bar + inflation◖F◗),
        ],
    ),
    (
        index = 68,
        variables = ["g{H}"],
        equation_indices = [4],
        equations = Expr[
            :(((-c◖H◗ - g◖H◗) - i◖H◗) + y◖H◗),
        ],
    ),
    (
        index = 69,
        variables = ["i{H}"],
        equation_indices = [3],
        equations = Expr[
            :(-investment_share * y◖H◗ + i◖H◗),
        ],
    ),
    (
        index = 70,
        variables = ["g{F}"],
        equation_indices = [34],
        equations = Expr[
            :(((-c◖F◗ - g◖F◗) - i◖F◗) + y◖F◗),
        ],
    ),
    (
        index = 71,
        variables = ["forward_anchor{H}"],
        equation_indices = [16],
        equations = Expr[
            :(forward_anchor◖H◗ - 0),
        ],
    ),
    (
        index = 72,
        variables = ["forward_anchor{F}"],
        equation_indices = [46],
        equations = Expr[
            :(forward_anchor◖F◗ - 0),
        ],
    ),
    (
        index = 73,
        variables = ["dnorm_signal{H}"],
        equation_indices = [27],
        equations = Expr[
            :(dnorm_signal◖H◗ - 0.398942280401433 * exp(-((a◖H◗ - 1) ^ 2) / 2)),
        ],
    ),
    (
        index = 74,
        variables = ["dnorm_signal{F}"],
        equation_indices = [57],
        equations = Expr[
            :(dnorm_signal◖F◗ - 0.398942280401433 * exp(-((a◖F◗ - 1) ^ 2) / 2)),
        ],
    ),
    (
        index = 75,
        variables = ["c{H}"],
        equation_indices = [2],
        equations = Expr[
            :(-consumption_share * y◖H◗ + c◖H◗),
        ],
    ),
    (
        index = 76,
        variables = ["y{H}"],
        equation_indices = [90],
        equations = Expr[
            :(y◖H◗ - output_target),
        ],
    ),
    (
        index = 77,
        variables = ["c{F}"],
        equation_indices = [32],
        equations = Expr[
            :(-consumption_share * y◖F◗ + c◖F◗),
        ],
    ),
    (
        index = 78,
        variables = ["i{F}", "k{F}", "y{F}"],
        equation_indices = [33, 35, 31],
        equations = Expr[
            :(-investment_share * y◖F◗ + i◖F◗),
            :((-i◖F◗ - k◖F◗ * (1 - delta)) + k◖F◗),
            :(-a◖F◗ * foreign_scale * k◖F◗ ^ alpha◖F◗ + y◖F◗),
        ],
    ),
    (
        index = 79,
        variables = ["cdf_signal{H}"],
        equation_indices = [19],
        equations = Expr[
            :((cdf_signal◖H◗ + erfc(0.707106781186547a◖H◗ - 0.707106781186547) / 2) - 1),
        ],
    ),
    (
        index = 80,
        variables = ["cdf_signal{F}"],
        equation_indices = [49],
        equations = Expr[
            :((cdf_signal◖F◗ + erfc(0.707106781186547a◖F◗ - 0.707106781186547) / 2) - 1),
        ],
    ),
    (
        index = 81,
        variables = ["a{H}"],
        equation_indices = [6],
        equations = Expr[
            :((-a◖H◗ * rho + a◖H◗ + rho) - 1),
        ],
    ),
    (
        index = 82,
        variables = ["a{F}"],
        equation_indices = [36],
        equations = Expr[
            :((-a◖F◗ * rho + a◖F◗ + rho) - 1),
        ],
    ),
]
const BLOCK_EQUATION_ORDER = [1, 30, 29, 60, 59, 61, 11, 12, 13, 14, 71, 76, 75, 74, 73, 72, 41, 42, 43, 44, 83, 88, 87, 86, 85, 84, 28, 58, 15, 45, 37, 38, 39, 8, 9, 7, 10, 65, 70, 69, 68, 67, 66, 89, 40, 77, 82, 81, 80, 79, 78, 62, 25, 55, 26, 56, 20, 50, 24, 54, 63, 64, 21, 51, 5, 23, 22, 53, 52, 17, 18, 47, 48, 4, 3, 34, 16, 46, 27, 57, 2, 90, 32, 33, 35, 31, 19, 49, 6, 36]

function complete_parameter_values(parameters::AbstractVector)
    @assert length(parameters) == length(PARAMETER_NAMES)
    complete_parameters = Vector{eltype(parameters)}(undef, length(COMPLETE_PARAMETER_NAMES))
    complete_parameters[19] = parameters[19]
    complete_parameters[15] = parameters[15]
    complete_parameters[23] = parameters[23]
    complete_parameters[7] = parameters[7]
    complete_parameters[1] = parameters[1]
    complete_parameters[12] = parameters[12]
    complete_parameters[10] = parameters[10]
    complete_parameters[8] = parameters[8]
    complete_parameters[9] = parameters[9]
    complete_parameters[5] = parameters[5]
    complete_parameters[22] = parameters[22]
    complete_parameters[14] = parameters[14]
    complete_parameters[17] = parameters[17]
    complete_parameters[6] = parameters[6]
    complete_parameters[2] = parameters[2]
    complete_parameters[21] = parameters[21]
    complete_parameters[11] = parameters[11]
    complete_parameters[13] = parameters[13]
    complete_parameters[16] = parameters[16]
    complete_parameters[3] = parameters[3]
    complete_parameters[18] = parameters[18]
    complete_parameters[4] = parameters[4]
    complete_parameters[20] = parameters[20]
    complete_parameters[24] = 1 - complete_parameters[4]
    complete_parameters[25] = complete_parameters[22] * 3
    complete_parameters[26] = 1 + complete_parameters[21]
    return complete_parameters
end

function residuals_original(parameters::AbstractVector, solution::AbstractVector)
    @assert length(parameters) == length(PARAMETER_NAMES)
    @assert length(solution) == length(ORIGINAL_SOLUTION_NAMES)
    complete_parameters = complete_parameter_values(parameters)
    return [
        solution[48] - solution[2] * solution[22] ^ solution[90],
        solution[6] - complete_parameters[3] * solution[48],
        solution[20] - complete_parameters[25] * solution[48],
        ((solution[48] - solution[6]) - solution[20]) - solution[12],
        solution[22] - ((1 - complete_parameters[22]) * solution[22] + solution[20]),
        solution[2] - ((1 - complete_parameters[1]) + complete_parameters[1] * solution[2] + complete_parameters[2] * 0 + complete_parameters[2] * 0 + complete_parameters[2] * 0 + complete_parameters[2] * 0),
        solution[60] - (complete_parameters[7] - solution[39]),
        solution[59] - (solution[6] / (solution[89] * solution[6]) - solution[39]),
        solution[50] - max(solution[60], solution[59]),
        solution[50] - solution[71],
        solution[62] - (complete_parameters[8] - solution[45]),
        solution[61] - ((complete_parameters[9] + complete_parameters[10] * solution[48]) - solution[45]),
        solution[51] - min(solution[62], solution[61]),
        solution[51] - solution[77],
        solution[41] - (solution[48] + solution[48] + solution[48]),
        solution[10] - (solution[48] - solution[48]),
        solution[14] - solution[16] * solution[16] * solution[16],
        solution[16] - (complete_parameters[5] + complete_parameters[6] * 0),
        solution[4] - normcdf(solution[2] - 1),
        solution[30] - normpdf(solution[2] - 1),
        solution[24] - normlogpdf(solution[2] - 1),
        solution[34] - (0.5 + 0.25 * tanh(solution[2] - 1)),
        solution[18] - norminvcdf(solution[34]),
        solution[28] - norminv(solution[34]),
        solution[36] - qnorm(solution[34]),
        solution[32] - pnorm(solution[2] - 1),
        solution[8] - dnorm(solution[2] - 1),
        solution[43] - (solution[48] - solution[48]),
        solution[55] - (0.25 * solution[55] + 0.25 * solution[55] + complete_parameters[15] * ifelse(complete_parameters[11] > 0.5, complete_parameters[17], 1 - complete_parameters[17]) + complete_parameters[12] * 0 + complete_parameters[12] * 0),
        solution[56] - (0.25 * solution[56] + 0.25 * solution[56] + complete_parameters[16] * ifelse(complete_parameters[11] > 0.5, complete_parameters[18], 1 - complete_parameters[18]) + complete_parameters[12] * 0 + complete_parameters[12] * 0),
        solution[47] - complete_parameters[24] * solution[1] * solution[21] ^ complete_parameters[19],
        solution[5] - complete_parameters[3] * solution[47],
        solution[19] - complete_parameters[25] * solution[47],
        ((solution[47] - solution[5]) - solution[19]) - solution[11],
        solution[21] - ((1 - complete_parameters[22]) * solution[21] + solution[19]),
        solution[1] - ((1 - complete_parameters[1]) + complete_parameters[1] * solution[1] + complete_parameters[2] * 0 + complete_parameters[2] * 0 + complete_parameters[2] * 0 + complete_parameters[2] * 0),
        solution[58] - (complete_parameters[7] - solution[38]),
        solution[57] - (solution[5] / (solution[89] * solution[5]) - solution[38]),
        solution[49] - max(solution[58], solution[57]),
        solution[49] - solution[65],
        solution[64] - (complete_parameters[8] - solution[44]),
        solution[63] - ((complete_parameters[9] + complete_parameters[10] * solution[47]) - solution[44]),
        solution[52] - min(solution[64], solution[63]),
        solution[52] - solution[83],
        solution[40] - (solution[47] + solution[47] + solution[47]),
        solution[9] - (solution[47] - solution[47]),
        solution[13] - solution[15] * solution[15] * solution[15],
        solution[15] - (complete_parameters[5] + complete_parameters[6] * 0),
        solution[3] - normcdf(solution[1] - 1),
        solution[29] - normpdf(solution[1] - 1),
        solution[23] - normlogpdf(solution[1] - 1),
        solution[33] - (0.5 + 0.25 * tanh(solution[1] - 1)),
        solution[17] - norminvcdf(solution[33]),
        solution[27] - norminv(solution[33]),
        solution[35] - qnorm(solution[33]),
        solution[31] - pnorm(solution[1] - 1),
        solution[7] - dnorm(solution[1] - 1),
        solution[42] - (solution[47] - solution[47]),
        solution[53] - (0.25 * solution[53] + 0.25 * solution[53] + complete_parameters[15] * ifelse(complete_parameters[11] > 0.5, complete_parameters[17], 1 - complete_parameters[17]) + complete_parameters[12] * 0 + complete_parameters[12] * 0),
        solution[54] - (0.25 * solution[54] + 0.25 * solution[54] + complete_parameters[16] * ifelse(complete_parameters[11] > 0.5, complete_parameters[18], 1 - complete_parameters[18]) + complete_parameters[12] * 0 + complete_parameters[12] * 0),
        solution[46] - (solution[48] + solution[47]),
        solution[37] - (solution[48] / solution[47]) / (solution[48] / solution[47]),
        solution[26] - complete_parameters[13] * (solution[48] - solution[47]),
        solution[25] - complete_parameters[14] * (solution[47] - solution[48]),
        solution[71] - solution[76],
        solution[75] - complete_parameters[23] * 0,
        solution[74] - (solution[75] + complete_parameters[23] * 0),
        solution[72] - (solution[74] + complete_parameters[23] * 0),
        solution[73] - (solution[72] + complete_parameters[23] * 0),
        solution[76] - (solution[73] + complete_parameters[23] * 0),
        solution[77] - solution[82],
        solution[81] - complete_parameters[23] * 0,
        solution[80] - (solution[81] + complete_parameters[23] * 0),
        solution[78] - (solution[80] + complete_parameters[23] * 0),
        solution[79] - (solution[78] + complete_parameters[23] * 0),
        solution[82] - (solution[79] + complete_parameters[23] * 0),
        solution[65] - solution[70],
        solution[69] - complete_parameters[23] * 0,
        solution[68] - (solution[69] + complete_parameters[23] * 0),
        solution[66] - (solution[68] + complete_parameters[23] * 0),
        solution[67] - (solution[66] + complete_parameters[23] * 0),
        solution[70] - (solution[67] + complete_parameters[23] * 0),
        solution[83] - solution[88],
        solution[87] - complete_parameters[23] * 0,
        solution[86] - (solution[87] + complete_parameters[23] * 0),
        solution[84] - (solution[86] + complete_parameters[23] * 0),
        solution[85] - (solution[84] + complete_parameters[23] * 0),
        solution[88] - (solution[85] + complete_parameters[23] * 0),
        solution[39] - complete_parameters[26],
        solution[48] - complete_parameters[20],
    ]
end

function residuals_auxiliary(parameters::AbstractVector, solution::AbstractVector)
    @assert length(parameters) == length(PARAMETER_NAMES)
    @assert length(solution) == length(AUXILIARY_SOLUTION_NAMES)
    complete_parameters = complete_parameter_values(parameters)
    return [
        -(solution[2]) * solution[22] ^ solution[90] + solution[48],
        -(complete_parameters[3]) * solution[48] + solution[6],
        -(complete_parameters[25]) * solution[48] + solution[20],
        ((-(solution[6]) - solution[12]) - solution[20]) + solution[48],
        (-(solution[20]) - solution[22] * (1 - complete_parameters[22])) + solution[22],
        (-(solution[2]) * complete_parameters[1] + solution[2] + complete_parameters[1]) - 1,
        -(complete_parameters[7]) + solution[39] + solution[60],
        (solution[39] + solution[59]) - 1 / solution[89],
        solution[50] - Max(solution[59], solution[60]),
        solution[50] - solution[71],
        -(complete_parameters[8]) + solution[45] + solution[62],
        (-(complete_parameters[9]) - complete_parameters[10] * solution[48]) + solution[45] + solution[61],
        solution[51] - Min(solution[61], solution[62]),
        solution[51] - solution[77],
        solution[41] - 3 * solution[48],
        solution[10] - 0,
        solution[14] - solution[16] ^ 3,
        -(complete_parameters[5]) + solution[16],
        (solution[4] + erfc(0.707106781186547 * solution[2] - 0.707106781186547) / 2) - 1,
        solution[30] - 0.398942280401433 * exp(-((solution[2] - 1) ^ 2) / 2),
        solution[24] + (solution[2] - 1) ^ 2 / 2 + 0.918938533204673,
        (solution[34] - 0.25 * tanh(solution[2] - 1)) - 0.5,
        solution[18] + 1.4142135623731 * erfcinv(2 * solution[34]),
        solution[28] + 1.4142135623731 * erfcinv(2 * solution[34]),
        solution[36] + 1.4142135623731 * erfcinv(2 * solution[34]),
        (solution[32] + erfc(0.707106781186547 * solution[2] - 0.707106781186547) / 2) - 1,
        solution[8] - 0.398942280401433 * exp(-((solution[2] - 1) ^ 2) / 2),
        solution[43] - 0,
        0.5 * solution[55] - complete_parameters[15] * (1 - complete_parameters[17]),
        0.5 * solution[56] - complete_parameters[16] * (1 - complete_parameters[18]),
        -(solution[1]) * complete_parameters[24] * solution[21] ^ complete_parameters[19] + solution[47],
        -(complete_parameters[3]) * solution[47] + solution[5],
        -(complete_parameters[25]) * solution[47] + solution[19],
        ((-(solution[5]) - solution[11]) - solution[19]) + solution[47],
        (-(solution[19]) - solution[21] * (1 - complete_parameters[22])) + solution[21],
        (-(solution[1]) * complete_parameters[1] + solution[1] + complete_parameters[1]) - 1,
        -(complete_parameters[7]) + solution[38] + solution[58],
        (solution[38] + solution[57]) - 1 / solution[89],
        solution[49] - Max(solution[57], solution[58]),
        solution[49] - solution[65],
        -(complete_parameters[8]) + solution[44] + solution[64],
        (-(complete_parameters[9]) - complete_parameters[10] * solution[47]) + solution[44] + solution[63],
        solution[52] - Min(solution[63], solution[64]),
        solution[52] - solution[83],
        solution[40] - 3 * solution[47],
        solution[9] - 0,
        solution[13] - solution[15] ^ 3,
        -(complete_parameters[5]) + solution[15],
        (solution[3] + erfc(0.707106781186547 * solution[1] - 0.707106781186547) / 2) - 1,
        solution[29] - 0.398942280401433 * exp(-((solution[1] - 1) ^ 2) / 2),
        solution[23] + (solution[1] - 1) ^ 2 / 2 + 0.918938533204673,
        (solution[33] - 0.25 * tanh(solution[1] - 1)) - 0.5,
        solution[17] + 1.4142135623731 * erfcinv(2 * solution[33]),
        solution[27] + 1.4142135623731 * erfcinv(2 * solution[33]),
        solution[35] + 1.4142135623731 * erfcinv(2 * solution[33]),
        (solution[31] + erfc(0.707106781186547 * solution[1] - 0.707106781186547) / 2) - 1,
        solution[7] - 0.398942280401433 * exp(-((solution[1] - 1) ^ 2) / 2),
        solution[42] - 0,
        0.5 * solution[53] - complete_parameters[15] * (1 - complete_parameters[17]),
        0.5 * solution[54] - complete_parameters[16] * (1 - complete_parameters[18]),
        (solution[46] - solution[47]) - solution[48],
        solution[37] - 1,
        solution[26] - complete_parameters[13] * (-(solution[47]) + solution[48]),
        solution[25] - complete_parameters[14] * (solution[47] - solution[48]),
        solution[71] - solution[76],
        solution[75] - 0,
        solution[74] - solution[75],
        solution[72] - solution[74],
        -(solution[72]) + solution[73],
        -(solution[73]) + solution[76],
        solution[77] - solution[82],
        solution[81] - 0,
        solution[80] - solution[81],
        solution[78] - solution[80],
        -(solution[78]) + solution[79],
        -(solution[79]) + solution[82],
        solution[65] - solution[70],
        solution[69] - 0,
        solution[68] - solution[69],
        solution[66] - solution[68],
        -(solution[66]) + solution[67],
        -(solution[67]) + solution[70],
        solution[83] - solution[88],
        solution[87] - 0,
        solution[86] - solution[87],
        solution[84] - solution[86],
        -(solution[84]) + solution[85],
        -(solution[85]) + solution[88],
        solution[39] - complete_parameters[26],
        solution[48] - complete_parameters[20],
    ]
end

function residuals_blocks(parameters::AbstractVector, solution::AbstractVector)
    return residuals_auxiliary(parameters, solution)[BLOCK_EQUATION_ORDER]
end

export MODEL_NAME, SOURCE_MODEL_FILE, NSSS_SOLUTION_ERROR, NSSS_RESIDUAL_NORM
export PARAMETER_NAMES, PARAMETER_VALUES, COMPLETE_PARAMETER_NAMES, COMPLETE_PARAMETER_VALUES
export ORIGINAL_SOLUTION_NAMES, ORIGINAL_SOLUTION_VALUES
export AUXILIARY_SOLUTION_NAMES, AUXILIARY_SOLUTION_VALUES
export ALL_AUXILIARY_VARIABLE_NAMES, ALL_AUXILIARY_VARIABLE_VALUES
export DEFAULTED_NSSS_SOLUTION_NAMES
export ORIGINAL_NSSS_EQUATIONS, AUXILIARY_NSSS_EQUATIONS, CALIBRATION_EQUATIONS
export BLOCKS, BLOCK_EQUATION_ORDER, residuals_original, residuals_auxiliary, residuals_blocks
end
