module Smets_Wouters_2003NsssResiduals
using MacroModelling

const normcdf = MacroModelling.SymPyWorkspace.normcdf
const pnorm = MacroModelling.SymPyWorkspace.pnorm
const normpdf = MacroModelling.SymPyWorkspace.normpdf
const dnorm = MacroModelling.SymPyWorkspace.dnorm
const normlogpdf = MacroModelling.SymPyWorkspace.normlogpdf
const norminvcdf = MacroModelling.SymPyWorkspace.norminvcdf
const norminv = MacroModelling.SymPyWorkspace.norminv
const qnorm = MacroModelling.SymPyWorkspace.qnorm
const erfcinv = MacroModelling.SymPyWorkspace.erfcinv
const erfc = MacroModelling.SymPyWorkspace.erfc
const Max = max
const Min = min

const MODEL_NAME = "Smets_Wouters_2003"
const SOURCE_MODEL_FILE = "models/Smets_Wouters_2003.jl"
const NSSS_SOLUTION_ERROR = 1.621545761085483e-14
const NSSS_RESIDUAL_NORM = 4.1162194343806383e-13

const PARAMETER_NAMES = [
    "lambda_p",
    "G_bar",
    "lambda_w",
    "Phi",
    "alpha",
    "beta",
    "gamma_w",
    "gamma_p",
    "h",
    "omega",
    "psi",
    "r_pi",
    "r_Y",
    "r_Delta_pi",
    "r_Delta_y",
    "sigma_c",
    "sigma_l",
    "tau",
    "varphi",
    "xi_w",
    "xi_p",
    "rho",
    "rho_b",
    "rho_L",
    "rho_I",
    "rho_a",
    "rho_G",
    "rho_pi_bar",
    "std_scaling_factor",
    "σ_eta_b",
    "σ_eta_L",
    "σ_eta_I",
    "σ_eta_a",
    "σ_eta_w",
    "σ_eta_p",
    "σ_eta_G",
    "σ_eta_R",
    "σ_eta_pi",
]
const PARAMETER_VALUES = Float64[
    0.368,
    0.362,
    0.5,
    0.819,
    0.3,
    0.99,
    0.763,
    0.469,
    0.573,
    1.0,
    0.169,
    1.684,
    0.099,
    0.14,
    0.159,
    1.353,
    2.4,
    0.025,
    6.771,
    0.737,
    0.908,
    0.961,
    0.855,
    0.889,
    0.927,
    0.823,
    0.949,
    0.924,
    10.0,
    0.336,
    3.52,
    0.085,
    0.598,
    0.6853261,
    0.7896512,
    0.325,
    0.081,
    0.017,
]
const COMPLETE_PARAMETER_NAMES = [
    "lambda_p",
    "G_bar",
    "lambda_w",
    "Phi",
    "alpha",
    "beta",
    "gamma_w",
    "gamma_p",
    "h",
    "omega",
    "psi",
    "r_pi",
    "r_Y",
    "r_Delta_pi",
    "r_Delta_y",
    "sigma_c",
    "sigma_l",
    "tau",
    "varphi",
    "xi_w",
    "xi_p",
    "rho",
    "rho_b",
    "rho_L",
    "rho_I",
    "rho_a",
    "rho_G",
    "rho_pi_bar",
    "std_scaling_factor",
    "σ_eta_b",
    "σ_eta_L",
    "σ_eta_I",
    "σ_eta_a",
    "σ_eta_w",
    "σ_eta_p",
    "σ_eta_G",
    "σ_eta_R",
    "σ_eta_pi",
    "std_eta_G",
    "std_eta_I",
    "std_eta_L",
    "std_eta_R",
    "std_eta_a",
    "std_eta_b",
    "std_eta_p",
    "std_eta_pi",
    "std_eta_w",
]
const COMPLETE_PARAMETER_VALUES = Float64[
    0.368,
    0.362,
    0.5,
    0.819,
    0.3,
    0.99,
    0.763,
    0.469,
    0.573,
    1.0,
    0.169,
    1.684,
    0.099,
    0.14,
    0.159,
    1.353,
    2.4,
    0.025,
    6.771,
    0.737,
    0.908,
    0.961,
    0.855,
    0.889,
    0.927,
    0.823,
    0.949,
    0.924,
    10.0,
    0.336,
    3.52,
    0.085,
    0.598,
    0.6853261,
    0.7896512,
    0.325,
    0.081,
    0.017,
    0.0325,
    0.0085,
    0.352,
    0.0081,
    0.0598,
    0.033600000000000005,
    0.07896512,
    0.0017000000000000001,
    0.06853261000000001,
]
const ORIGINAL_SOLUTION_NAMES = [
    "C",
    "C_f",
    "G",
    "G_f",
    "I",
    "I_f",
    "K",
    "K_f",
    "L",
    "L_f",
    "L_s",
    "L_s_f",
    "P_j_f",
    "Pi_ps_f",
    "Pi_ws_f",
    "Q",
    "Q_f",
    "R",
    "R_f",
    "T",
    "T_f",
    "U",
    "U_f",
    "W",
    "W_disutil_f",
    "W_f",
    "W_i_f",
    "Y",
    "Y_f",
    "Y_s",
    "Y_s_f",
    "epsilon_G",
    "epsilon_I",
    "epsilon_L",
    "epsilon_a",
    "epsilon_b",
    "f_1",
    "f_2",
    "g_1",
    "g_2",
    "mc",
    "mc_f",
    "nu_p",
    "nu_w",
    "pi",
    "pi_obj",
    "pi_star",
    "q",
    "q_f",
    "r_k",
    "r_k_f",
    "w_star",
    "z",
    "z_f",
    "calibr_pi_obj",
    "calibr_pi",
]
const ORIGINAL_SOLUTION_VALUES = Float64[
    1.2043777490745406,
    1.2043777490745413,
    0.362,
    0.362,
    0.44153839869564304,
    0.44153839869564676,
    17.661535947825833,
    17.661535947825893,
    1.2891159432112804,
    1.2891159432112813,
    1.2891159432112804,
    1.2891159432112813,
    1.0,
    0.5401411859498753,
    0.48217380688088,
    0.9999999999999999,
    0.9999999999999998,
    1.0101010101010102,
    1.01010101010101,
    0.362,
    0.362,
    -427.98589108172615,
    -427.9858910817262,
    1.1221034292999643,
    0.7480689528666447,
    1.1221034292999668,
    1.1221034292999668,
    2.007916147770183,
    2.007916147770188,
    2.007916147770183,
    2.007916147770188,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    8.770699460488208,
    8.770699460488208,
    48.84717584653678,
    35.70699988781929,
    0.7309941520467829,
    0.7309941520467835,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    2.4590033503396382,
    2.4590033503396365,
    0.03510101010101008,
    0.03510101010101003,
    1.1221034292999643,
    0.9999999999999993,
    1.0000000000000002,
    1.0,
    0.0,
]
const AUXILIARY_SOLUTION_NAMES = [
    "C",
    "C_f",
    "G",
    "G_f",
    "I",
    "I_f",
    "K",
    "K_f",
    "L",
    "L_f",
    "L_s",
    "L_s_f",
    "P_j_f",
    "Pi_ps_f",
    "Pi_ws_f",
    "Q",
    "Q_f",
    "R",
    "R_f",
    "T",
    "T_f",
    "U",
    "U_f",
    "W",
    "W_disutil_f",
    "W_f",
    "W_i_f",
    "Y",
    "Y_f",
    "Y_s",
    "Y_s_f",
    "epsilon_G",
    "epsilon_I",
    "epsilon_L",
    "epsilon_a",
    "epsilon_b",
    "f_1",
    "f_2",
    "g_1",
    "g_2",
    "mc",
    "mc_f",
    "nu_p",
    "nu_w",
    "pi",
    "pi_obj",
    "pi_star",
    "q",
    "q_f",
    "r_k",
    "r_k_f",
    "w_star",
    "z",
    "z_f",
    "➕₁",
    "➕₁₀",
    "➕₁₁",
    "➕₁₂",
    "➕₁₃",
    "➕₁₄",
    "➕₁₅",
    "➕₁₆",
    "➕₁₇",
    "➕₁₈",
    "➕₂",
    "➕₃",
    "➕₄",
    "➕₅",
    "➕₆",
    "➕₇",
    "➕₈",
    "➕₉",
    "calibr_pi_obj",
    "calibr_pi",
]
const AUXILIARY_SOLUTION_VALUES = Float64[
    1.2043777490745406,
    1.2043777490745413,
    0.362,
    0.362,
    0.44153839869564304,
    0.44153839869564676,
    17.661535947825833,
    17.661535947825893,
    1.2891159432112804,
    1.2891159432112813,
    1.2891159432112804,
    1.2891159432112813,
    1.0,
    0.5401411859498753,
    0.48217380688088,
    0.9999999999999999,
    0.9999999999999998,
    1.0101010101010102,
    1.01010101010101,
    0.362,
    0.362,
    -427.98589108172615,
    -427.9858910817262,
    1.1221034292999643,
    0.7480689528666447,
    1.1221034292999668,
    1.1221034292999668,
    2.007916147770183,
    2.007916147770188,
    2.007916147770183,
    2.007916147770188,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    8.770699460488208,
    8.770699460488208,
    48.84717584653678,
    35.70699988781929,
    0.7309941520467829,
    0.7309941520467835,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    2.4590033503396382,
    2.4590033503396365,
    0.03510101010101008,
    0.03510101010101003,
    1.1221034292999643,
    0.9999999999999993,
    1.0000000000000002,
    -1.1257661469699087e-16,
    1.0,
    1.0,
    1.0,
    1.0,
    1.2891159432112804,
    1.0,
    1.0,
    -1.1257661469699087e-16,
    3.7525538232330294e-17,
    0.5142692988548289,
    3.7525538232330294e-17,
    0.5142692988548292,
    17.661535947825822,
    17.661535947825897,
    1.0,
    0.5142692988548289,
    0.5142692988548292,
    1.0,
    0.0,
]
const ALL_AUXILIARY_VARIABLE_NAMES = [
    "➕₁",
    "➕₂",
    "➕₃",
    "➕₄",
    "➕₅",
    "➕₆",
    "➕₇",
    "➕₈",
    "➕₉",
    "➕₁₀",
    "➕₁₁",
    "➕₁₂",
    "➕₁₃",
    "➕₁₄",
    "➕₁₅",
    "➕₁₆",
    "➕₁₇",
    "➕₁₈",
    "➕₁₉",
    "➕₂₀",
    "➕₂₁",
]
const ALL_AUXILIARY_VARIABLE_VALUES = Float64[
    -1.1257661469699087e-16,
    0.5142692988548289,
    3.7525538232330294e-17,
    0.5142692988548292,
    17.661535947825822,
    17.661535947825897,
    1.0,
    0.5142692988548289,
    0.5142692988548292,
    1.0,
    1.0,
    1.0,
    1.0,
    1.2891159432112804,
    1.0,
    1.0,
    -1.1257661469699087e-16,
    3.7525538232330294e-17,
    1.2891159432112804,
    1.0,
    1.2891159432112813,
]
const DEFAULTED_NSSS_SOLUTION_NAMES = [
]
const CALIBRATION_PARAMETER_NAMES = [
    "calibr_pi_obj",
    "calibr_pi",
]

const ORIGINAL_NSSS_EQUATIONS = Expr[
    :(-q + beta * ((1 - tau) * q + epsilon_b * (r_k * z - psi ^ -1 * r_k * (-1 + exp(psi * (-1 + z)))) * (C - h * C) ^ -sigma_c)),
    :(-q_f + beta * ((1 - tau) * q_f + epsilon_b * (r_k_f * z_f - psi ^ -1 * r_k_f * (-1 + exp(psi * (-1 + z_f)))) * (C_f - h * C_f) ^ -sigma_c)),
    :(-r_k + alpha * epsilon_a * mc * L ^ (1 - alpha) * (K * z) ^ (-1 + alpha)),
    :(-r_k_f + alpha * epsilon_a * mc_f * L_f ^ (1 - alpha) * (K_f * z_f) ^ (-1 + alpha)),
    :(-G + T),
    :(-G + G_bar * epsilon_G),
    :(-G_f + T_f),
    :(-G_f + G_bar * epsilon_G),
    :(-L + nu_w ^ -1 * L_s),
    :(-L_s_f + L_f * (W_i_f * W_f ^ -1) ^ (lambda_w ^ -1 * (-1 - lambda_w))),
    :(L_s_f - L_f),
    :(L_s_f + lambda_w ^ -1 * L_f * W_f ^ -1 * (-1 - lambda_w) * (-W_disutil_f + W_i_f) * (W_i_f * W_f ^ -1) ^ (-1 + lambda_w ^ -1 * (-1 - lambda_w))),
    :(Pi_ws_f - L_s_f * (-W_disutil_f + W_i_f)),
    :(Pi_ps_f - Y_f * (-mc_f + P_j_f) * P_j_f ^ (-(lambda_p ^ -1) * (1 + lambda_p))),
    :(-Q + epsilon_b ^ -1 * q * (C - h * C) ^ sigma_c),
    :(-Q_f + epsilon_b ^ -1 * q_f * (C_f - h * C_f) ^ sigma_c),
    :(-W + epsilon_a * mc * (1 - alpha) * L ^ -alpha * (K * z) ^ alpha),
    :(-W_f + epsilon_a * mc_f * (1 - alpha) * L_f ^ -alpha * (K_f * z_f) ^ alpha),
    :(-Y_f + Y_s_f),
    :(Y_s - nu_p * Y),
    :(-Y_s_f + Y_f * P_j_f ^ (-(lambda_p ^ -1) * (1 + lambda_p))),
    :(beta * epsilon_b * (C_f - h * C_f) ^ -sigma_c - epsilon_b * R_f ^ -1 * (C_f - h * C_f) ^ -sigma_c),
    :(beta * epsilon_b * pi ^ -1 * (C - h * C) ^ -sigma_c - epsilon_b * R ^ -1 * (C - h * C) ^ -sigma_c),
    :(Y_f * P_j_f ^ (-(lambda_p ^ -1) * (1 + lambda_p)) - lambda_p ^ -1 * Y_f * (1 + lambda_p) * (-mc_f + P_j_f) * P_j_f ^ (-1 - lambda_p ^ -1 * (1 + lambda_p))),
    :(epsilon_b * W_disutil_f * (C_f - h * C_f) ^ -sigma_c - omega * epsilon_b * epsilon_L * L_s_f ^ sigma_l),
    :(-1 + xi_p * (pi ^ -1 * pi ^ gamma_p) ^ -(lambda_p ^ -1) + (1 - xi_p) * pi_star ^ -(lambda_p ^ -1)),
    :(-1 + (1 - xi_w) * (w_star * W ^ -1) ^ -(lambda_w ^ -1) + xi_w * (W * W ^ -1) ^ -(lambda_w ^ -1) * (pi ^ -1 * pi ^ gamma_w) ^ -(lambda_w ^ -1)),
    :((-Phi - Y_s) + epsilon_a * L ^ (1 - alpha) * (K * z) ^ alpha),
    :((-Phi - Y_f * P_j_f ^ (-(lambda_p ^ -1) * (1 + lambda_p))) + epsilon_a * L_f ^ (1 - alpha) * (K_f * z_f) ^ alpha),
    :((std_eta_b * 0 - log(epsilon_b)) + rho_b * log(epsilon_b)),
    :((-std_eta_L * 0 - log(epsilon_L)) + rho_L * log(epsilon_L)),
    :((std_eta_I * 0 - log(epsilon_I)) + rho_I * log(epsilon_I)),
    :((std_eta_w * 0 - f_1) + f_2),
    :((std_eta_a * 0 - log(epsilon_a)) + rho_a * log(epsilon_a)),
    :((std_eta_p * 0 - g_1) + g_2 * (1 + lambda_p)),
    :((std_eta_G * 0 - log(epsilon_G)) + rho_G * log(epsilon_G)),
    :(-f_1 + beta * xi_w * f_1 * (w_star ^ -1 * w_star) ^ (lambda_w ^ -1) * (pi ^ -1 * pi ^ gamma_w) ^ -(lambda_w ^ -1) + epsilon_b * w_star * L * (1 + lambda_w) ^ -1 * (C - h * C) ^ -sigma_c * (w_star * W ^ -1) ^ (-(lambda_w ^ -1) * (1 + lambda_w))),
    :(-f_2 + beta * xi_w * f_2 * (w_star ^ -1 * w_star) ^ (lambda_w ^ -1 * (1 + lambda_w) * (1 + sigma_l)) * (pi ^ -1 * pi ^ gamma_w) ^ (-(lambda_w ^ -1) * (1 + lambda_w) * (1 + sigma_l)) + omega * epsilon_b * epsilon_L * (L * (w_star * W ^ -1) ^ (-(lambda_w ^ -1) * (1 + lambda_w))) ^ (1 + sigma_l)),
    :(-g_1 + beta * xi_p * pi_star * g_1 * pi_star ^ -1 * (pi ^ -1 * pi ^ gamma_p) ^ -(lambda_p ^ -1) + epsilon_b * pi_star * Y * (C - h * C) ^ -sigma_c),
    :(-g_2 + beta * xi_p * g_2 * (pi ^ -1 * pi ^ gamma_p) ^ (-(lambda_p ^ -1) * (1 + lambda_p)) + epsilon_b * mc * Y * (C - h * C) ^ -sigma_c),
    :(-nu_w + (1 - xi_w) * (w_star * W ^ -1) ^ (-(lambda_w ^ -1) * (1 + lambda_w)) + xi_w * nu_w * (W * pi ^ -1 * W ^ -1 * pi ^ gamma_w) ^ (-(lambda_w ^ -1) * (1 + lambda_w))),
    :(-nu_p + (1 - xi_p) * pi_star ^ (-(lambda_p ^ -1) * (1 + lambda_p)) + xi_p * nu_p * (pi ^ -1 * pi ^ gamma_p) ^ (-(lambda_p ^ -1) * (1 + lambda_p))),
    :(-K + K * (1 - tau) + I * (1 - 0.5 * varphi * (-1 + I ^ -1 * epsilon_I * I) ^ 2)),
    :(-K_f + K_f * (1 - tau) + I_f * (1 - 0.5 * varphi * (-1 + I_f ^ -1 * epsilon_I * I_f) ^ 2)),
    :((U - beta * U) - epsilon_b * ((1 - sigma_c) ^ -1 * (C - h * C) ^ (1 - sigma_c) - omega * epsilon_L * (1 + sigma_l) ^ -1 * L_s ^ (1 + sigma_l))),
    :((U_f - beta * U_f) - epsilon_b * ((1 - sigma_c) ^ -1 * (C_f - h * C_f) ^ (1 - sigma_c) - omega * epsilon_L * (1 + sigma_l) ^ -1 * L_s_f ^ (1 + sigma_l))),
    :(-epsilon_b * (C - h * C) ^ -sigma_c + q * ((1 - 0.5 * varphi * (-1 + I ^ -1 * epsilon_I * I) ^ 2) - varphi * I ^ -1 * epsilon_I * I * (-1 + I ^ -1 * epsilon_I * I)) + beta * varphi * I ^ -2 * epsilon_I * q * I ^ 2 * (-1 + I ^ -1 * epsilon_I * I)),
    :(-epsilon_b * (C_f - h * C_f) ^ -sigma_c + q_f * ((1 - 0.5 * varphi * (-1 + I_f ^ -1 * epsilon_I * I_f) ^ 2) - varphi * I_f ^ -1 * epsilon_I * I_f * (-1 + I_f ^ -1 * epsilon_I * I_f)) + beta * varphi * I_f ^ -2 * epsilon_I * q_f * I_f ^ 2 * (-1 + I_f ^ -1 * epsilon_I * I_f)),
    :((((-C - I) - T) + Y) - psi ^ -1 * r_k * K * (-1 + exp(psi * (-1 + z)))),
    :((((((-C_f - I_f) + Pi_ws_f) - T_f) + Y_f + L_s_f * W_disutil_f) - L_f * W_f) - psi ^ -1 * r_k_f * K_f * (-1 + exp(psi * (-1 + z_f)))),
    :(epsilon_b * (K * r_k - r_k * K * exp(psi * (-1 + z))) * (C - h * C) ^ -sigma_c),
    :(epsilon_b * (K_f * r_k_f - r_k_f * K_f * exp(psi * (-1 + z_f))) * (C_f - h * C_f) ^ -sigma_c),
    :((std_eta_pi * 0 - log(pi_obj)) + rho_pi_bar * log(pi_obj) + log(calibr_pi_obj) * (1 - rho_pi_bar)),
    :(((-calibr_pi + std_eta_R * 0) - log(R ^ -1 * R)) + r_Delta_pi * (-(log(pi ^ -1 * pi)) + log(pi ^ -1 * pi)) + r_Delta_y * ((-(log(Y ^ -1 * Y)) + log(Y ^ -1 * Y) + log(Y_f ^ -1 * Y_f)) - log(Y_f ^ -1 * Y_f)) + rho * log(R ^ -1 * R) + (1 - rho) * (log(pi_obj) + r_pi * (-(log(pi_obj)) + log(pi ^ -1 * pi)) + r_Y * (log(Y ^ -1 * Y) - log(Y_f ^ -1 * Y_f)))),
]
const CALIBRATION_EQUATIONS = Expr[
    :(1 - pi_obj),
    :(pi - pi_obj),
]
const AUXILIARY_NSSS_EQUATIONS = Expr[
    :(➕₁ - psi * (z - 1)),
    :(➕₂ - (-C * h + C)),
    :(beta * ((epsilon_b * (r_k * z - (r_k * (exp(➕₁) - 1)) / psi)) / ➕₂ ^ sigma_c + q * (1 - tau)) - q),
    :(➕₃ - psi * (z_f - 1)),
    :(➕₄ - (-C_f * h + C_f)),
    :(beta * ((epsilon_b * (r_k_f * z_f - (r_k_f * (exp(➕₃) - 1)) / psi)) / ➕₄ ^ sigma_c + q_f * (1 - tau)) - q_f),
    :(➕₅ - K * z),
    :(L ^ (1 - alpha) * alpha * epsilon_a * mc * ➕₅ ^ (alpha - 1) - r_k),
    :(➕₆ - K_f * z_f),
    :(L_f ^ (1 - alpha) * alpha * epsilon_a * mc_f * ➕₆ ^ (alpha - 1) - r_k_f),
    :(-G + T),
    :(-G + G_bar * epsilon_G),
    :(-G_f + T_f),
    :(G_bar * epsilon_G - G_f),
    :(-L + L_s / nu_w),
    :(➕₇ - W_i_f / W_f),
    :(L_f * ➕₇ ^ ((-lambda_w - 1) / lambda_w) - L_s_f),
    :(-L_f + L_s_f),
    :((L_f * ➕₇ ^ (-1 + (-lambda_w - 1) / lambda_w) * (-W_disutil_f + W_i_f) * (-lambda_w - 1)) / (W_f * lambda_w) + L_s_f),
    :(-L_s_f * (-W_disutil_f + W_i_f) + Pi_ws_f),
    :(Pi_ps_f - (Y_f * (P_j_f - mc_f)) / P_j_f ^ ((lambda_p + 1) / lambda_p)),
    :(➕₈ - (-C * h + C)),
    :(-Q + (q * ➕₈ ^ sigma_c) / epsilon_b),
    :(➕₉ - (-C_f * h + C_f)),
    :(-Q_f + (q_f * ➕₉ ^ sigma_c) / epsilon_b),
    :(-W + (epsilon_a * mc * ➕₅ ^ alpha * (1 - alpha)) / L ^ alpha),
    :(-W_f + (epsilon_a * mc_f * ➕₆ ^ alpha * (1 - alpha)) / L_f ^ alpha),
    :(-Y_f + Y_s_f),
    :(-Y * nu_p + Y_s),
    :(-Y_s_f + Y_f / P_j_f ^ ((lambda_p + 1) / lambda_p)),
    :((beta * epsilon_b) / ➕₄ ^ sigma_c - epsilon_b / (R_f * ➕₉ ^ sigma_c)),
    :((beta * epsilon_b) / (pi * ➕₂ ^ sigma_c) - epsilon_b / (R * ➕₈ ^ sigma_c)),
    :((-(P_j_f ^ (-1 - (lambda_p + 1) / lambda_p)) * Y_f * (P_j_f - mc_f) * (lambda_p + 1)) / lambda_p + Y_f / P_j_f ^ ((lambda_p + 1) / lambda_p)),
    :(-(L_s_f ^ sigma_l) * epsilon_L * epsilon_b * omega + (W_disutil_f * epsilon_b) / ➕₉ ^ sigma_c),
    :(➕₁₀ - pi ^ gamma_p / pi),
    :((xi_p / ➕₁₀ ^ (1 / lambda_p) - 1) + (1 - xi_p) / pi_star ^ (1 / lambda_p)),
    :(➕₁₁ - w_star / W),
    :(➕₁₂ - pi ^ gamma_w / pi),
    :((xi_w / ➕₁₂ ^ (1 / lambda_w) - 1) + (1 - xi_w) / ➕₁₁ ^ (1 / lambda_w)),
    :((L ^ (1 - alpha) * epsilon_a * ➕₅ ^ alpha - Phi) - Y_s),
    :((L_f ^ (1 - alpha) * epsilon_a * ➕₆ ^ alpha - Phi) - Y_f / P_j_f ^ ((lambda_p + 1) / lambda_p)),
    :(rho_b * log(epsilon_b) - log(epsilon_b)),
    :(rho_L * log(epsilon_L) - log(epsilon_L)),
    :(rho_I * log(epsilon_I) - log(epsilon_I)),
    :(-f_1 + f_2),
    :(rho_a * log(epsilon_a) - log(epsilon_a)),
    :(-g_1 + g_2 * (lambda_p + 1)),
    :(rho_G * log(epsilon_G) - log(epsilon_G)),
    :(➕₁₃ - pi ^ gamma_w / pi),
    :(((L * epsilon_b * w_star) / (➕₁₁ ^ ((lambda_w + 1) / lambda_w) * ➕₈ ^ sigma_c * (lambda_w + 1)) + (beta * f_1 * xi_w) / ➕₁₃ ^ (1 / lambda_w)) - f_1),
    :(➕₁₄ - L / ➕₁₁ ^ ((lambda_w + 1) / lambda_w)),
    :(((beta * f_2 * xi_w) / ➕₁₃ ^ (((lambda_w + 1) * (sigma_l + 1)) / lambda_w) + epsilon_L * epsilon_b * omega * ➕₁₄ ^ (sigma_l + 1)) - f_2),
    :(➕₁₅ - pi ^ gamma_p / pi),
    :(((Y * epsilon_b * pi_star) / ➕₈ ^ sigma_c + (beta * g_1 * xi_p) / ➕₁₅ ^ (1 / lambda_p)) - g_1),
    :(((Y * epsilon_b * mc) / ➕₈ ^ sigma_c + (beta * g_2 * xi_p) / ➕₁₅ ^ ((lambda_p + 1) / lambda_p)) - g_2),
    :(➕₁₆ - pi ^ gamma_w / pi),
    :(((nu_w * xi_w) / ➕₁₆ ^ ((lambda_w + 1) / lambda_w) - nu_w) + (1 - xi_w) / ➕₁₁ ^ ((lambda_w + 1) / lambda_w)),
    :(((nu_p * xi_p) / ➕₁₀ ^ ((lambda_p + 1) / lambda_p) - nu_p) + (1 - xi_p) / pi_star ^ ((lambda_p + 1) / lambda_p)),
    :((I * (-0.5 * varphi * (epsilon_I - 1) ^ 2 + 1) + K * (1 - tau)) - K),
    :((I_f * (-0.5 * varphi * (epsilon_I - 1) ^ 2 + 1) + K_f * (1 - tau)) - K_f),
    :((-U * beta + U) - epsilon_b * ((-(L_s ^ (sigma_l + 1)) * epsilon_L * omega) / (sigma_l + 1) + ➕₈ ^ (1 - sigma_c) / (1 - sigma_c))),
    :((-U_f * beta + U_f) - epsilon_b * ((-(L_s_f ^ (sigma_l + 1)) * epsilon_L * omega) / (sigma_l + 1) + ➕₉ ^ (1 - sigma_c) / (1 - sigma_c))),
    :((beta * epsilon_I * q * varphi * (epsilon_I - 1) - epsilon_b / ➕₈ ^ sigma_c) + q * ((-epsilon_I * varphi * (epsilon_I - 1) - 0.5 * varphi * (epsilon_I - 1) ^ 2) + 1)),
    :((beta * epsilon_I * q_f * varphi * (epsilon_I - 1) - epsilon_b / ➕₉ ^ sigma_c) + q_f * ((-epsilon_I * varphi * (epsilon_I - 1) - 0.5 * varphi * (epsilon_I - 1) ^ 2) + 1)),
    :(➕₁₇ - psi * (z - 1)),
    :((((-C - I) - (K * r_k * (exp(➕₁₇) - 1)) / psi) - T) + Y),
    :(➕₁₈ - psi * (z_f - 1)),
    :((((((-C_f - I_f) - (K_f * r_k_f * (exp(➕₁₈) - 1)) / psi) - L_f * W_f) + L_s_f * W_disutil_f + Pi_ws_f) - T_f) + Y_f),
    :((epsilon_b * (-K * r_k * exp(➕₁₇) + K * r_k)) / ➕₈ ^ sigma_c),
    :((epsilon_b * (-K_f * r_k_f * exp(➕₁₈) + K_f * r_k_f)) / ➕₉ ^ sigma_c),
    :((rho_pi_bar * log(pi_obj) + (1 - rho_pi_bar) * log(calibr_pi_obj)) - log(pi_obj)),
    :(-calibr_pi + (1 - rho) * (-r_pi * log(pi_obj) + log(pi_obj))),
]
const ORIGINAL_RESIDUAL_EQUATIONS = Expr[
    :(-q + beta * ((1 - tau) * q + epsilon_b * (r_k * z - psi ^ -1 * r_k * (-1 + exp(psi * (-1 + z)))) * (C - h * C) ^ -sigma_c)),
    :(-q_f + beta * ((1 - tau) * q_f + epsilon_b * (r_k_f * z_f - psi ^ -1 * r_k_f * (-1 + exp(psi * (-1 + z_f)))) * (C_f - h * C_f) ^ -sigma_c)),
    :(-r_k + alpha * epsilon_a * mc * L ^ (1 - alpha) * (K * z) ^ (-1 + alpha)),
    :(-r_k_f + alpha * epsilon_a * mc_f * L_f ^ (1 - alpha) * (K_f * z_f) ^ (-1 + alpha)),
    :(-G + T),
    :(-G + G_bar * epsilon_G),
    :(-G_f + T_f),
    :(-G_f + G_bar * epsilon_G),
    :(-L + nu_w ^ -1 * L_s),
    :(-L_s_f + L_f * (W_i_f * W_f ^ -1) ^ (lambda_w ^ -1 * (-1 - lambda_w))),
    :(L_s_f - L_f),
    :(L_s_f + lambda_w ^ -1 * L_f * W_f ^ -1 * (-1 - lambda_w) * (-W_disutil_f + W_i_f) * (W_i_f * W_f ^ -1) ^ (-1 + lambda_w ^ -1 * (-1 - lambda_w))),
    :(Pi_ws_f - L_s_f * (-W_disutil_f + W_i_f)),
    :(Pi_ps_f - Y_f * (-mc_f + P_j_f) * P_j_f ^ (-(lambda_p ^ -1) * (1 + lambda_p))),
    :(-Q + epsilon_b ^ -1 * q * (C - h * C) ^ sigma_c),
    :(-Q_f + epsilon_b ^ -1 * q_f * (C_f - h * C_f) ^ sigma_c),
    :(-W + epsilon_a * mc * (1 - alpha) * L ^ -alpha * (K * z) ^ alpha),
    :(-W_f + epsilon_a * mc_f * (1 - alpha) * L_f ^ -alpha * (K_f * z_f) ^ alpha),
    :(-Y_f + Y_s_f),
    :(Y_s - nu_p * Y),
    :(-Y_s_f + Y_f * P_j_f ^ (-(lambda_p ^ -1) * (1 + lambda_p))),
    :(beta * epsilon_b * (C_f - h * C_f) ^ -sigma_c - epsilon_b * R_f ^ -1 * (C_f - h * C_f) ^ -sigma_c),
    :(beta * epsilon_b * pi ^ -1 * (C - h * C) ^ -sigma_c - epsilon_b * R ^ -1 * (C - h * C) ^ -sigma_c),
    :(Y_f * P_j_f ^ (-(lambda_p ^ -1) * (1 + lambda_p)) - lambda_p ^ -1 * Y_f * (1 + lambda_p) * (-mc_f + P_j_f) * P_j_f ^ (-1 - lambda_p ^ -1 * (1 + lambda_p))),
    :(epsilon_b * W_disutil_f * (C_f - h * C_f) ^ -sigma_c - omega * epsilon_b * epsilon_L * L_s_f ^ sigma_l),
    :(-1 + xi_p * (pi ^ -1 * pi ^ gamma_p) ^ -(lambda_p ^ -1) + (1 - xi_p) * pi_star ^ -(lambda_p ^ -1)),
    :(-1 + (1 - xi_w) * (w_star * W ^ -1) ^ -(lambda_w ^ -1) + xi_w * (W * W ^ -1) ^ -(lambda_w ^ -1) * (pi ^ -1 * pi ^ gamma_w) ^ -(lambda_w ^ -1)),
    :((-Phi - Y_s) + epsilon_a * L ^ (1 - alpha) * (K * z) ^ alpha),
    :((-Phi - Y_f * P_j_f ^ (-(lambda_p ^ -1) * (1 + lambda_p))) + epsilon_a * L_f ^ (1 - alpha) * (K_f * z_f) ^ alpha),
    :((std_eta_b * 0 - log(epsilon_b)) + rho_b * log(epsilon_b)),
    :((-std_eta_L * 0 - log(epsilon_L)) + rho_L * log(epsilon_L)),
    :((std_eta_I * 0 - log(epsilon_I)) + rho_I * log(epsilon_I)),
    :((std_eta_w * 0 - f_1) + f_2),
    :((std_eta_a * 0 - log(epsilon_a)) + rho_a * log(epsilon_a)),
    :((std_eta_p * 0 - g_1) + g_2 * (1 + lambda_p)),
    :((std_eta_G * 0 - log(epsilon_G)) + rho_G * log(epsilon_G)),
    :(-f_1 + beta * xi_w * f_1 * (w_star ^ -1 * w_star) ^ (lambda_w ^ -1) * (pi ^ -1 * pi ^ gamma_w) ^ -(lambda_w ^ -1) + epsilon_b * w_star * L * (1 + lambda_w) ^ -1 * (C - h * C) ^ -sigma_c * (w_star * W ^ -1) ^ (-(lambda_w ^ -1) * (1 + lambda_w))),
    :(-f_2 + beta * xi_w * f_2 * (w_star ^ -1 * w_star) ^ (lambda_w ^ -1 * (1 + lambda_w) * (1 + sigma_l)) * (pi ^ -1 * pi ^ gamma_w) ^ (-(lambda_w ^ -1) * (1 + lambda_w) * (1 + sigma_l)) + omega * epsilon_b * epsilon_L * (L * (w_star * W ^ -1) ^ (-(lambda_w ^ -1) * (1 + lambda_w))) ^ (1 + sigma_l)),
    :(-g_1 + beta * xi_p * pi_star * g_1 * pi_star ^ -1 * (pi ^ -1 * pi ^ gamma_p) ^ -(lambda_p ^ -1) + epsilon_b * pi_star * Y * (C - h * C) ^ -sigma_c),
    :(-g_2 + beta * xi_p * g_2 * (pi ^ -1 * pi ^ gamma_p) ^ (-(lambda_p ^ -1) * (1 + lambda_p)) + epsilon_b * mc * Y * (C - h * C) ^ -sigma_c),
    :(-nu_w + (1 - xi_w) * (w_star * W ^ -1) ^ (-(lambda_w ^ -1) * (1 + lambda_w)) + xi_w * nu_w * (W * pi ^ -1 * W ^ -1 * pi ^ gamma_w) ^ (-(lambda_w ^ -1) * (1 + lambda_w))),
    :(-nu_p + (1 - xi_p) * pi_star ^ (-(lambda_p ^ -1) * (1 + lambda_p)) + xi_p * nu_p * (pi ^ -1 * pi ^ gamma_p) ^ (-(lambda_p ^ -1) * (1 + lambda_p))),
    :(-K + K * (1 - tau) + I * (1 - 0.5 * varphi * (-1 + I ^ -1 * epsilon_I * I) ^ 2)),
    :(-K_f + K_f * (1 - tau) + I_f * (1 - 0.5 * varphi * (-1 + I_f ^ -1 * epsilon_I * I_f) ^ 2)),
    :((U - beta * U) - epsilon_b * ((1 - sigma_c) ^ -1 * (C - h * C) ^ (1 - sigma_c) - omega * epsilon_L * (1 + sigma_l) ^ -1 * L_s ^ (1 + sigma_l))),
    :((U_f - beta * U_f) - epsilon_b * ((1 - sigma_c) ^ -1 * (C_f - h * C_f) ^ (1 - sigma_c) - omega * epsilon_L * (1 + sigma_l) ^ -1 * L_s_f ^ (1 + sigma_l))),
    :(-epsilon_b * (C - h * C) ^ -sigma_c + q * ((1 - 0.5 * varphi * (-1 + I ^ -1 * epsilon_I * I) ^ 2) - varphi * I ^ -1 * epsilon_I * I * (-1 + I ^ -1 * epsilon_I * I)) + beta * varphi * I ^ -2 * epsilon_I * q * I ^ 2 * (-1 + I ^ -1 * epsilon_I * I)),
    :(-epsilon_b * (C_f - h * C_f) ^ -sigma_c + q_f * ((1 - 0.5 * varphi * (-1 + I_f ^ -1 * epsilon_I * I_f) ^ 2) - varphi * I_f ^ -1 * epsilon_I * I_f * (-1 + I_f ^ -1 * epsilon_I * I_f)) + beta * varphi * I_f ^ -2 * epsilon_I * q_f * I_f ^ 2 * (-1 + I_f ^ -1 * epsilon_I * I_f)),
    :((((-C - I) - T) + Y) - psi ^ -1 * r_k * K * (-1 + exp(psi * (-1 + z)))),
    :((((((-C_f - I_f) + Pi_ws_f) - T_f) + Y_f + L_s_f * W_disutil_f) - L_f * W_f) - psi ^ -1 * r_k_f * K_f * (-1 + exp(psi * (-1 + z_f)))),
    :(epsilon_b * (K * r_k - r_k * K * exp(psi * (-1 + z))) * (C - h * C) ^ -sigma_c),
    :(epsilon_b * (K_f * r_k_f - r_k_f * K_f * exp(psi * (-1 + z_f))) * (C_f - h * C_f) ^ -sigma_c),
    :((std_eta_pi * 0 - log(pi_obj)) + rho_pi_bar * log(pi_obj) + log(calibr_pi_obj) * (1 - rho_pi_bar)),
    :(((-calibr_pi + std_eta_R * 0) - log(R ^ -1 * R)) + r_Delta_pi * (-(log(pi ^ -1 * pi)) + log(pi ^ -1 * pi)) + r_Delta_y * ((-(log(Y ^ -1 * Y)) + log(Y ^ -1 * Y) + log(Y_f ^ -1 * Y_f)) - log(Y_f ^ -1 * Y_f)) + rho * log(R ^ -1 * R) + (1 - rho) * (log(pi_obj) + r_pi * (-(log(pi_obj)) + log(pi ^ -1 * pi)) + r_Y * (log(Y ^ -1 * Y) - log(Y_f ^ -1 * Y_f)))),
    :(1 - pi_obj),
    :(pi - pi_obj),
]
const AUXILIARY_RESIDUAL_EQUATIONS = Expr[
    :(➕₁ - psi * (z - 1)),
    :(➕₂ - (-C * h + C)),
    :(beta * ((epsilon_b * (r_k * z - (r_k * (exp(➕₁) - 1)) / psi)) / ➕₂ ^ sigma_c + q * (1 - tau)) - q),
    :(➕₃ - psi * (z_f - 1)),
    :(➕₄ - (-C_f * h + C_f)),
    :(beta * ((epsilon_b * (r_k_f * z_f - (r_k_f * (exp(➕₃) - 1)) / psi)) / ➕₄ ^ sigma_c + q_f * (1 - tau)) - q_f),
    :(➕₅ - K * z),
    :(L ^ (1 - alpha) * alpha * epsilon_a * mc * ➕₅ ^ (alpha - 1) - r_k),
    :(➕₆ - K_f * z_f),
    :(L_f ^ (1 - alpha) * alpha * epsilon_a * mc_f * ➕₆ ^ (alpha - 1) - r_k_f),
    :(-G + T),
    :(-G + G_bar * epsilon_G),
    :(-G_f + T_f),
    :(G_bar * epsilon_G - G_f),
    :(-L + L_s / nu_w),
    :(➕₇ - W_i_f / W_f),
    :(L_f * ➕₇ ^ ((-lambda_w - 1) / lambda_w) - L_s_f),
    :(-L_f + L_s_f),
    :((L_f * ➕₇ ^ (-1 + (-lambda_w - 1) / lambda_w) * (-W_disutil_f + W_i_f) * (-lambda_w - 1)) / (W_f * lambda_w) + L_s_f),
    :(-L_s_f * (-W_disutil_f + W_i_f) + Pi_ws_f),
    :(Pi_ps_f - (Y_f * (P_j_f - mc_f)) / P_j_f ^ ((lambda_p + 1) / lambda_p)),
    :(➕₈ - (-C * h + C)),
    :(-Q + (q * ➕₈ ^ sigma_c) / epsilon_b),
    :(➕₉ - (-C_f * h + C_f)),
    :(-Q_f + (q_f * ➕₉ ^ sigma_c) / epsilon_b),
    :(-W + (epsilon_a * mc * ➕₅ ^ alpha * (1 - alpha)) / L ^ alpha),
    :(-W_f + (epsilon_a * mc_f * ➕₆ ^ alpha * (1 - alpha)) / L_f ^ alpha),
    :(-Y_f + Y_s_f),
    :(-Y * nu_p + Y_s),
    :(-Y_s_f + Y_f / P_j_f ^ ((lambda_p + 1) / lambda_p)),
    :((beta * epsilon_b) / ➕₄ ^ sigma_c - epsilon_b / (R_f * ➕₉ ^ sigma_c)),
    :((beta * epsilon_b) / (pi * ➕₂ ^ sigma_c) - epsilon_b / (R * ➕₈ ^ sigma_c)),
    :((-(P_j_f ^ (-1 - (lambda_p + 1) / lambda_p)) * Y_f * (P_j_f - mc_f) * (lambda_p + 1)) / lambda_p + Y_f / P_j_f ^ ((lambda_p + 1) / lambda_p)),
    :(-(L_s_f ^ sigma_l) * epsilon_L * epsilon_b * omega + (W_disutil_f * epsilon_b) / ➕₉ ^ sigma_c),
    :(➕₁₀ - pi ^ gamma_p / pi),
    :((xi_p / ➕₁₀ ^ (1 / lambda_p) - 1) + (1 - xi_p) / pi_star ^ (1 / lambda_p)),
    :(➕₁₁ - w_star / W),
    :(➕₁₂ - pi ^ gamma_w / pi),
    :((xi_w / ➕₁₂ ^ (1 / lambda_w) - 1) + (1 - xi_w) / ➕₁₁ ^ (1 / lambda_w)),
    :((L ^ (1 - alpha) * epsilon_a * ➕₅ ^ alpha - Phi) - Y_s),
    :((L_f ^ (1 - alpha) * epsilon_a * ➕₆ ^ alpha - Phi) - Y_f / P_j_f ^ ((lambda_p + 1) / lambda_p)),
    :(rho_b * log(epsilon_b) - log(epsilon_b)),
    :(rho_L * log(epsilon_L) - log(epsilon_L)),
    :(rho_I * log(epsilon_I) - log(epsilon_I)),
    :(-f_1 + f_2),
    :(rho_a * log(epsilon_a) - log(epsilon_a)),
    :(-g_1 + g_2 * (lambda_p + 1)),
    :(rho_G * log(epsilon_G) - log(epsilon_G)),
    :(➕₁₃ - pi ^ gamma_w / pi),
    :(((L * epsilon_b * w_star) / (➕₁₁ ^ ((lambda_w + 1) / lambda_w) * ➕₈ ^ sigma_c * (lambda_w + 1)) + (beta * f_1 * xi_w) / ➕₁₃ ^ (1 / lambda_w)) - f_1),
    :(➕₁₄ - L / ➕₁₁ ^ ((lambda_w + 1) / lambda_w)),
    :(((beta * f_2 * xi_w) / ➕₁₃ ^ (((lambda_w + 1) * (sigma_l + 1)) / lambda_w) + epsilon_L * epsilon_b * omega * ➕₁₄ ^ (sigma_l + 1)) - f_2),
    :(➕₁₅ - pi ^ gamma_p / pi),
    :(((Y * epsilon_b * pi_star) / ➕₈ ^ sigma_c + (beta * g_1 * xi_p) / ➕₁₅ ^ (1 / lambda_p)) - g_1),
    :(((Y * epsilon_b * mc) / ➕₈ ^ sigma_c + (beta * g_2 * xi_p) / ➕₁₅ ^ ((lambda_p + 1) / lambda_p)) - g_2),
    :(➕₁₆ - pi ^ gamma_w / pi),
    :(((nu_w * xi_w) / ➕₁₆ ^ ((lambda_w + 1) / lambda_w) - nu_w) + (1 - xi_w) / ➕₁₁ ^ ((lambda_w + 1) / lambda_w)),
    :(((nu_p * xi_p) / ➕₁₀ ^ ((lambda_p + 1) / lambda_p) - nu_p) + (1 - xi_p) / pi_star ^ ((lambda_p + 1) / lambda_p)),
    :((I * (-0.5 * varphi * (epsilon_I - 1) ^ 2 + 1) + K * (1 - tau)) - K),
    :((I_f * (-0.5 * varphi * (epsilon_I - 1) ^ 2 + 1) + K_f * (1 - tau)) - K_f),
    :((-U * beta + U) - epsilon_b * ((-(L_s ^ (sigma_l + 1)) * epsilon_L * omega) / (sigma_l + 1) + ➕₈ ^ (1 - sigma_c) / (1 - sigma_c))),
    :((-U_f * beta + U_f) - epsilon_b * ((-(L_s_f ^ (sigma_l + 1)) * epsilon_L * omega) / (sigma_l + 1) + ➕₉ ^ (1 - sigma_c) / (1 - sigma_c))),
    :((beta * epsilon_I * q * varphi * (epsilon_I - 1) - epsilon_b / ➕₈ ^ sigma_c) + q * ((-epsilon_I * varphi * (epsilon_I - 1) - 0.5 * varphi * (epsilon_I - 1) ^ 2) + 1)),
    :((beta * epsilon_I * q_f * varphi * (epsilon_I - 1) - epsilon_b / ➕₉ ^ sigma_c) + q_f * ((-epsilon_I * varphi * (epsilon_I - 1) - 0.5 * varphi * (epsilon_I - 1) ^ 2) + 1)),
    :(➕₁₇ - psi * (z - 1)),
    :((((-C - I) - (K * r_k * (exp(➕₁₇) - 1)) / psi) - T) + Y),
    :(➕₁₈ - psi * (z_f - 1)),
    :((((((-C_f - I_f) - (K_f * r_k_f * (exp(➕₁₈) - 1)) / psi) - L_f * W_f) + L_s_f * W_disutil_f + Pi_ws_f) - T_f) + Y_f),
    :((epsilon_b * (-K * r_k * exp(➕₁₇) + K * r_k)) / ➕₈ ^ sigma_c),
    :((epsilon_b * (-K_f * r_k_f * exp(➕₁₈) + K_f * r_k_f)) / ➕₉ ^ sigma_c),
    :((rho_pi_bar * log(pi_obj) + (1 - rho_pi_bar) * log(calibr_pi_obj)) - log(pi_obj)),
    :(-calibr_pi + (1 - rho) * (-r_pi * log(pi_obj) + log(pi_obj))),
    :(1 - pi_obj),
    :(pi - pi_obj),
]

const PARAMETER_DEFINITION_NAMES = [
    "std_eta_G",
    "std_eta_I",
    "std_eta_L",
    "std_eta_R",
    "std_eta_a",
    "std_eta_b",
    "std_eta_p",
    "std_eta_pi",
    "std_eta_w",
]
const PARAMETER_DEFINITION_EXPRESSIONS = [
    "σ_eta_G / std_scaling_factor",
    "σ_eta_I / std_scaling_factor",
    "σ_eta_L / std_scaling_factor",
    "σ_eta_R / std_scaling_factor",
    "σ_eta_a / std_scaling_factor",
    "σ_eta_b / std_scaling_factor",
    "σ_eta_p / std_scaling_factor",
    "σ_eta_pi / std_scaling_factor",
    "σ_eta_w / std_scaling_factor",
]
const PARAMETER_BOX_CONSTRAINT_NAMES = [
    "lambda_p",
    "G_bar",
    "lambda_w",
    "Phi",
    "alpha",
    "beta",
    "gamma_w",
    "gamma_p",
    "h",
    "omega",
    "psi",
    "r_pi",
    "r_Y",
    "r_Delta_pi",
    "r_Delta_y",
    "sigma_c",
    "sigma_l",
    "tau",
    "varphi",
    "xi_w",
    "xi_p",
    "rho",
    "rho_b",
    "rho_L",
    "rho_I",
    "rho_a",
    "rho_G",
    "rho_pi_bar",
    "std_scaling_factor",
    "σ_eta_b",
    "σ_eta_L",
    "σ_eta_I",
    "σ_eta_a",
    "σ_eta_w",
    "σ_eta_p",
    "σ_eta_G",
    "σ_eta_R",
    "σ_eta_pi",
]
const PARAMETER_BOX_LOWER_BOUNDS = Float64[
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
]
const PARAMETER_BOX_UPPER_BOUNDS = Float64[
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
]
const ORIGINAL_BOX_CONSTRAINT_NAMES = [
    "C",
    "C_f",
    "G",
    "G_f",
    "I",
    "I_f",
    "K",
    "K_f",
    "L",
    "L_f",
    "L_s",
    "L_s_f",
    "P_j_f",
    "Pi_ps_f",
    "Pi_ws_f",
    "Q",
    "Q_f",
    "R",
    "R_f",
    "T",
    "T_f",
    "U",
    "U_f",
    "W",
    "W_disutil_f",
    "W_f",
    "W_i_f",
    "Y",
    "Y_f",
    "Y_s",
    "Y_s_f",
    "epsilon_G",
    "epsilon_I",
    "epsilon_L",
    "epsilon_a",
    "epsilon_b",
    "f_1",
    "f_2",
    "g_1",
    "g_2",
    "mc",
    "mc_f",
    "nu_p",
    "nu_w",
    "pi",
    "pi_obj",
    "pi_star",
    "q",
    "q_f",
    "r_k",
    "r_k_f",
    "w_star",
    "z",
    "z_f",
    "calibr_pi_obj",
    "calibr_pi",
]
const ORIGINAL_BOX_LOWER_BOUNDS = Float64[
    -1.0e12,
    -1.0e12,
    -Inf,
    -Inf,
    -1.0e12,
    -1.0e12,
    -1.0e12,
    -1.0e12,
    2.220446049250313e-16,
    2.220446049250313e-16,
    -Inf,
    2.220446049250313e-16,
    2.220446049250313e-16,
    -Inf,
    -1.0e12,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -1.0e12,
    -1.0e12,
    -1.0e12,
    -1.0e12,
    -1.0e12,
    -1.0e12,
    -1.0e12,
    -1.0e12,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -1.0e12,
    -1.0e12,
    -1.0e12,
    -1.0e12,
    -1.0e12,
    -1.0e12,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -1.0e12,
    -1.0e12,
    -1.0e12,
    -1.0e12,
    -1.0e12,
    -1.0e12,
    -1.0e12,
    -Inf,
    -Inf,
]
const ORIGINAL_BOX_UPPER_BOUNDS = Float64[
    1.0e12,
    1.0e12,
    Inf,
    Inf,
    1.0e12,
    1.0e12,
    1.0e12,
    1.0e12,
    1.0e12,
    1.0e12,
    Inf,
    1.0e12,
    1.0e12,
    Inf,
    1.0e12,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    1.0e12,
    1.0e12,
    1.0e12,
    1.0e12,
    1.0e12,
    1.0e12,
    1.0e12,
    1.0e12,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    1.0e12,
    1.0e12,
    1.0e12,
    1.0e12,
    1.0e12,
    1.0e12,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    1.0e12,
    1.0e12,
    1.0e12,
    1.0e12,
    1.0e12,
    1.0e12,
    1.0e12,
    Inf,
    Inf,
]
const AUXILIARY_BOX_CONSTRAINT_NAMES = [
    "C",
    "C_f",
    "G",
    "G_f",
    "I",
    "I_f",
    "K",
    "K_f",
    "L",
    "L_f",
    "L_s",
    "L_s_f",
    "P_j_f",
    "Pi_ps_f",
    "Pi_ws_f",
    "Q",
    "Q_f",
    "R",
    "R_f",
    "T",
    "T_f",
    "U",
    "U_f",
    "W",
    "W_disutil_f",
    "W_f",
    "W_i_f",
    "Y",
    "Y_f",
    "Y_s",
    "Y_s_f",
    "epsilon_G",
    "epsilon_I",
    "epsilon_L",
    "epsilon_a",
    "epsilon_b",
    "f_1",
    "f_2",
    "g_1",
    "g_2",
    "mc",
    "mc_f",
    "nu_p",
    "nu_w",
    "pi",
    "pi_obj",
    "pi_star",
    "q",
    "q_f",
    "r_k",
    "r_k_f",
    "w_star",
    "z",
    "z_f",
    "➕₁",
    "➕₁₀",
    "➕₁₁",
    "➕₁₂",
    "➕₁₃",
    "➕₁₄",
    "➕₁₅",
    "➕₁₆",
    "➕₁₇",
    "➕₁₈",
    "➕₂",
    "➕₃",
    "➕₄",
    "➕₅",
    "➕₆",
    "➕₇",
    "➕₈",
    "➕₉",
    "calibr_pi_obj",
    "calibr_pi",
]
const AUXILIARY_BOX_LOWER_BOUNDS = Float64[
    -1.0e12,
    -1.0e12,
    -Inf,
    -Inf,
    -1.0e12,
    -1.0e12,
    -1.0e12,
    -1.0e12,
    2.220446049250313e-16,
    2.220446049250313e-16,
    -Inf,
    2.220446049250313e-16,
    2.220446049250313e-16,
    -Inf,
    -1.0e12,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -1.0e12,
    -1.0e12,
    -1.0e12,
    -1.0e12,
    -1.0e12,
    -1.0e12,
    -1.0e12,
    -1.0e12,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -1.0e12,
    -1.0e12,
    -1.0e12,
    -1.0e12,
    -1.0e12,
    -1.0e12,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    -1.0e12,
    -1.0e12,
    -1.0e12,
    -1.0e12,
    -1.0e12,
    -1.0e12,
    -1.0e12,
    -1.0e12,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    2.220446049250313e-16,
    -Inf,
    -Inf,
    -1.0e12,
    -1.0e12,
    2.220446049250313e-16,
    -1.0e12,
    2.220446049250313e-16,
    2.220446049250313e-16,
    2.220446049250313e-16,
    2.220446049250313e-16,
    2.220446049250313e-16,
    2.220446049250313e-16,
    -Inf,
    -Inf,
]
const AUXILIARY_BOX_UPPER_BOUNDS = Float64[
    1.0e12,
    1.0e12,
    Inf,
    Inf,
    1.0e12,
    1.0e12,
    1.0e12,
    1.0e12,
    1.0e12,
    1.0e12,
    Inf,
    1.0e12,
    1.0e12,
    Inf,
    1.0e12,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    1.0e12,
    1.0e12,
    1.0e12,
    1.0e12,
    1.0e12,
    1.0e12,
    1.0e12,
    1.0e12,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    1.0e12,
    1.0e12,
    1.0e12,
    1.0e12,
    1.0e12,
    1.0e12,
    Inf,
    Inf,
    Inf,
    Inf,
    Inf,
    1.0e12,
    1.0e12,
    1.0e12,
    1.0e12,
    1.0e12,
    1.0e12,
    1.0e12,
    600.0,
    Inf,
    Inf,
    Inf,
    Inf,
    1.0e12,
    Inf,
    Inf,
    600.0,
    600.0,
    1.0e12,
    600.0,
    1.0e12,
    1.0e12,
    1.0e12,
    1.0e12,
    1.0e12,
    1.0e12,
    Inf,
    Inf,
]
const ALL_AUXILIARY_BOX_CONSTRAINT_NAMES = [
    "➕₁",
    "➕₂",
    "➕₃",
    "➕₄",
    "➕₅",
    "➕₆",
    "➕₇",
    "➕₈",
    "➕₉",
    "➕₁₀",
    "➕₁₁",
    "➕₁₂",
    "➕₁₃",
    "➕₁₄",
    "➕₁₅",
    "➕₁₆",
    "➕₁₇",
    "➕₁₈",
    "➕₁₉",
    "➕₂₀",
    "➕₂₁",
]
const ALL_AUXILIARY_BOX_LOWER_BOUNDS = Float64[
    -1.0e12,
    2.220446049250313e-16,
    -1.0e12,
    2.220446049250313e-16,
    2.220446049250313e-16,
    2.220446049250313e-16,
    2.220446049250313e-16,
    2.220446049250313e-16,
    2.220446049250313e-16,
    -Inf,
    -Inf,
    -Inf,
    -Inf,
    2.220446049250313e-16,
    -Inf,
    -Inf,
    -1.0e12,
    -1.0e12,
    2.220446049250313e-16,
    2.220446049250313e-16,
    2.220446049250313e-16,
]
const ALL_AUXILIARY_BOX_UPPER_BOUNDS = Float64[
    600.0,
    1.0e12,
    600.0,
    1.0e12,
    1.0e12,
    1.0e12,
    1.0e12,
    1.0e12,
    1.0e12,
    Inf,
    Inf,
    Inf,
    Inf,
    1.0e12,
    Inf,
    Inf,
    600.0,
    600.0,
    1.0e12,
    1.0e12,
    1.0e12,
]

const BLOCKS = [
    (
        index = 1,
        variables = ["calibr_pi"],
        equation_indices = [72],
        equations = Expr[
            :(-calibr_pi + (1 - rho) * (-r_pi * log(pi_obj) + log(pi_obj))),
        ],
    ),
    (
        index = 2,
        variables = ["calibr_pi_obj"],
        equation_indices = [71],
        equations = Expr[
            :((rho_pi_bar * log(pi_obj) + (1 - rho_pi_bar) * log(calibr_pi_obj)) - log(pi_obj)),
        ],
    ),
    (
        index = 3,
        variables = ["U_f"],
        equation_indices = [62],
        equations = Expr[
            :((-U_f * beta + U_f) - epsilon_b * ((-(L_s_f ^ (sigma_l + 1)) * epsilon_L * omega) / (sigma_l + 1) + ➕₉ ^ (1 - sigma_c) / (1 - sigma_c))),
        ],
    ),
    (
        index = 4,
        variables = ["U"],
        equation_indices = [61],
        equations = Expr[
            :((-U * beta + U) - epsilon_b * ((-(L_s ^ (sigma_l + 1)) * epsilon_L * omega) / (sigma_l + 1) + ➕₈ ^ (1 - sigma_c) / (1 - sigma_c))),
        ],
    ),
    (
        index = 5,
        variables = ["R_f"],
        equation_indices = [31],
        equations = Expr[
            :((beta * epsilon_b) / ➕₄ ^ sigma_c - epsilon_b / (R_f * ➕₉ ^ sigma_c)),
        ],
    ),
    (
        index = 6,
        variables = ["R"],
        equation_indices = [32],
        equations = Expr[
            :((beta * epsilon_b) / (pi * ➕₂ ^ sigma_c) - epsilon_b / (R * ➕₈ ^ sigma_c)),
        ],
    ),
    (
        index = 7,
        variables = ["Q_f"],
        equation_indices = [25],
        equations = Expr[
            :(-Q_f + (q_f * ➕₉ ^ sigma_c) / epsilon_b),
        ],
    ),
    (
        index = 8,
        variables = ["Q"],
        equation_indices = [23],
        equations = Expr[
            :(-Q + (q * ➕₈ ^ sigma_c) / epsilon_b),
        ],
    ),
    (
        index = 9,
        variables = ["Pi_ps_f"],
        equation_indices = [21],
        equations = Expr[
            :(Pi_ps_f - (Y_f * (P_j_f - mc_f)) / P_j_f ^ ((lambda_p + 1) / lambda_p)),
        ],
    ),
    (
        index = 10,
        variables = ["L_s"],
        equation_indices = [15],
        equations = Expr[
            :(-L + L_s / nu_w),
        ],
    ),
    (
        index = 11,
        variables = ["nu_w"],
        equation_indices = [57],
        equations = Expr[
            :(((nu_w * xi_w) / ➕₁₆ ^ ((lambda_w + 1) / lambda_w) - nu_w) + (1 - xi_w) / ➕₁₁ ^ ((lambda_w + 1) / lambda_w)),
        ],
    ),
    (
        index = 12,
        variables = ["➕₁₆"],
        equation_indices = [56],
        equations = Expr[
            :(➕₁₆ - pi ^ gamma_w / pi),
        ],
    ),
    (
        index = 13,
        variables = ["C_f", "I_f", "K_f", "L_f", "L_s_f", "P_j_f", "Pi_ws_f", "W_disutil_f", "W_f", "W_i_f", "Y_f", "Y_s_f", "mc_f", "q_f", "r_k_f", "z_f", "➕₁₈", "➕₃", "➕₄", "➕₆", "➕₇", "➕₉"],
        equation_indices = [24, 60, 70, 68, 18, 33, 20, 34, 16, 19, 28, 30, 27, 6, 10, 9, 67, 4, 5, 41, 17, 64],
        equations = Expr[
            :(➕₉ - (-C_f * h + C_f)),
            :((I_f * (-0.5 * varphi * (epsilon_I - 1) ^ 2 + 1) + K_f * (1 - tau)) - K_f),
            :((epsilon_b * (-K_f * r_k_f * exp(➕₁₈) + K_f * r_k_f)) / ➕₉ ^ sigma_c),
            :((((((-C_f - I_f) - (K_f * r_k_f * (exp(➕₁₈) - 1)) / psi) - L_f * W_f) + L_s_f * W_disutil_f + Pi_ws_f) - T_f) + Y_f),
            :(-L_f + L_s_f),
            :((-(P_j_f ^ (-1 - (lambda_p + 1) / lambda_p)) * Y_f * (P_j_f - mc_f) * (lambda_p + 1)) / lambda_p + Y_f / P_j_f ^ ((lambda_p + 1) / lambda_p)),
            :(-L_s_f * (-W_disutil_f + W_i_f) + Pi_ws_f),
            :(-(L_s_f ^ sigma_l) * epsilon_L * epsilon_b * omega + (W_disutil_f * epsilon_b) / ➕₉ ^ sigma_c),
            :(➕₇ - W_i_f / W_f),
            :((L_f * ➕₇ ^ (-1 + (-lambda_w - 1) / lambda_w) * (-W_disutil_f + W_i_f) * (-lambda_w - 1)) / (W_f * lambda_w) + L_s_f),
            :(-Y_f + Y_s_f),
            :(-Y_s_f + Y_f / P_j_f ^ ((lambda_p + 1) / lambda_p)),
            :(-W_f + (epsilon_a * mc_f * ➕₆ ^ alpha * (1 - alpha)) / L_f ^ alpha),
            :(beta * ((epsilon_b * (r_k_f * z_f - (r_k_f * (exp(➕₃) - 1)) / psi)) / ➕₄ ^ sigma_c + q_f * (1 - tau)) - q_f),
            :(L_f ^ (1 - alpha) * alpha * epsilon_a * mc_f * ➕₆ ^ (alpha - 1) - r_k_f),
            :(➕₆ - K_f * z_f),
            :(➕₁₈ - psi * (z_f - 1)),
            :(➕₃ - psi * (z_f - 1)),
            :(➕₄ - (-C_f * h + C_f)),
            :((L_f ^ (1 - alpha) * epsilon_a * ➕₆ ^ alpha - Phi) - Y_f / P_j_f ^ ((lambda_p + 1) / lambda_p)),
            :(L_f * ➕₇ ^ ((-lambda_w - 1) / lambda_w) - L_s_f),
            :((beta * epsilon_I * q_f * varphi * (epsilon_I - 1) - epsilon_b / ➕₉ ^ sigma_c) + q_f * ((-epsilon_I * varphi * (epsilon_I - 1) - 0.5 * varphi * (epsilon_I - 1) ^ 2) + 1)),
        ],
    ),
    (
        index = 14,
        variables = ["T_f"],
        equation_indices = [13],
        equations = Expr[
            :(-G_f + T_f),
        ],
    ),
    (
        index = 15,
        variables = ["G_f"],
        equation_indices = [14],
        equations = Expr[
            :(G_bar * epsilon_G - G_f),
        ],
    ),
    (
        index = 16,
        variables = ["C", "I", "K", "L", "W", "Y", "Y_s", "f_1", "f_2", "g_1", "g_2", "mc", "q", "r_k", "w_star", "z", "➕₁", "➕₁₄", "➕₁₇", "➕₂", "➕₅", "➕₈"],
        equation_indices = [66, 59, 7, 8, 37, 29, 40, 45, 52, 54, 47, 55, 63, 69, 50, 1, 3, 51, 65, 2, 26, 22],
        equations = Expr[
            :((((-C - I) - (K * r_k * (exp(➕₁₇) - 1)) / psi) - T) + Y),
            :((I * (-0.5 * varphi * (epsilon_I - 1) ^ 2 + 1) + K * (1 - tau)) - K),
            :(➕₅ - K * z),
            :(L ^ (1 - alpha) * alpha * epsilon_a * mc * ➕₅ ^ (alpha - 1) - r_k),
            :(➕₁₁ - w_star / W),
            :(-Y * nu_p + Y_s),
            :((L ^ (1 - alpha) * epsilon_a * ➕₅ ^ alpha - Phi) - Y_s),
            :(-f_1 + f_2),
            :(((beta * f_2 * xi_w) / ➕₁₃ ^ (((lambda_w + 1) * (sigma_l + 1)) / lambda_w) + epsilon_L * epsilon_b * omega * ➕₁₄ ^ (sigma_l + 1)) - f_2),
            :(((Y * epsilon_b * pi_star) / ➕₈ ^ sigma_c + (beta * g_1 * xi_p) / ➕₁₅ ^ (1 / lambda_p)) - g_1),
            :(-g_1 + g_2 * (lambda_p + 1)),
            :(((Y * epsilon_b * mc) / ➕₈ ^ sigma_c + (beta * g_2 * xi_p) / ➕₁₅ ^ ((lambda_p + 1) / lambda_p)) - g_2),
            :((beta * epsilon_I * q * varphi * (epsilon_I - 1) - epsilon_b / ➕₈ ^ sigma_c) + q * ((-epsilon_I * varphi * (epsilon_I - 1) - 0.5 * varphi * (epsilon_I - 1) ^ 2) + 1)),
            :((epsilon_b * (-K * r_k * exp(➕₁₇) + K * r_k)) / ➕₈ ^ sigma_c),
            :(((L * epsilon_b * w_star) / (➕₁₁ ^ ((lambda_w + 1) / lambda_w) * ➕₈ ^ sigma_c * (lambda_w + 1)) + (beta * f_1 * xi_w) / ➕₁₃ ^ (1 / lambda_w)) - f_1),
            :(➕₁ - psi * (z - 1)),
            :(beta * ((epsilon_b * (r_k * z - (r_k * (exp(➕₁) - 1)) / psi)) / ➕₂ ^ sigma_c + q * (1 - tau)) - q),
            :(➕₁₄ - L / ➕₁₁ ^ ((lambda_w + 1) / lambda_w)),
            :(➕₁₇ - psi * (z - 1)),
            :(➕₂ - (-C * h + C)),
            :(-W + (epsilon_a * mc * ➕₅ ^ alpha * (1 - alpha)) / L ^ alpha),
            :(➕₈ - (-C * h + C)),
        ],
    ),
    (
        index = 17,
        variables = ["T"],
        equation_indices = [11],
        equations = Expr[
            :(-G + T),
        ],
    ),
    (
        index = 18,
        variables = ["G"],
        equation_indices = [12],
        equations = Expr[
            :(-G + G_bar * epsilon_G),
        ],
    ),
    (
        index = 19,
        variables = ["epsilon_G"],
        equation_indices = [48],
        equations = Expr[
            :(rho_G * log(epsilon_G) - log(epsilon_G)),
        ],
    ),
    (
        index = 20,
        variables = ["➕₁₁"],
        equation_indices = [39],
        equations = Expr[
            :((xi_w / ➕₁₂ ^ (1 / lambda_w) - 1) + (1 - xi_w) / ➕₁₁ ^ (1 / lambda_w)),
        ],
    ),
    (
        index = 21,
        variables = ["➕₁₂"],
        equation_indices = [38],
        equations = Expr[
            :(➕₁₂ - pi ^ gamma_w / pi),
        ],
    ),
    (
        index = 22,
        variables = ["➕₁₃"],
        equation_indices = [49],
        equations = Expr[
            :(➕₁₃ - pi ^ gamma_w / pi),
        ],
    ),
    (
        index = 23,
        variables = ["epsilon_L"],
        equation_indices = [43],
        equations = Expr[
            :(rho_L * log(epsilon_L) - log(epsilon_L)),
        ],
    ),
    (
        index = 24,
        variables = ["➕₁₅"],
        equation_indices = [53],
        equations = Expr[
            :(➕₁₅ - pi ^ gamma_p / pi),
        ],
    ),
    (
        index = 25,
        variables = ["nu_p"],
        equation_indices = [58],
        equations = Expr[
            :(((nu_p * xi_p) / ➕₁₀ ^ ((lambda_p + 1) / lambda_p) - nu_p) + (1 - xi_p) / pi_star ^ ((lambda_p + 1) / lambda_p)),
        ],
    ),
    (
        index = 26,
        variables = ["pi_star"],
        equation_indices = [36],
        equations = Expr[
            :((xi_p / ➕₁₀ ^ (1 / lambda_p) - 1) + (1 - xi_p) / pi_star ^ (1 / lambda_p)),
        ],
    ),
    (
        index = 27,
        variables = ["➕₁₀"],
        equation_indices = [35],
        equations = Expr[
            :(➕₁₀ - pi ^ gamma_p / pi),
        ],
    ),
    (
        index = 28,
        variables = ["pi"],
        equation_indices = [74],
        equations = Expr[
            :(pi - pi_obj),
        ],
    ),
    (
        index = 29,
        variables = ["pi_obj"],
        equation_indices = [73],
        equations = Expr[
            :(1 - pi_obj),
        ],
    ),
    (
        index = 30,
        variables = ["epsilon_a"],
        equation_indices = [46],
        equations = Expr[
            :(rho_a * log(epsilon_a) - log(epsilon_a)),
        ],
    ),
    (
        index = 31,
        variables = ["epsilon_I"],
        equation_indices = [44],
        equations = Expr[
            :(rho_I * log(epsilon_I) - log(epsilon_I)),
        ],
    ),
    (
        index = 32,
        variables = ["epsilon_b"],
        equation_indices = [42],
        equations = Expr[
            :(rho_b * log(epsilon_b) - log(epsilon_b)),
        ],
    ),
]
const BLOCK_EQUATION_ORDER = [72, 71, 62, 61, 31, 32, 25, 23, 21, 15, 57, 56, 24, 60, 70, 68, 18, 33, 20, 34, 16, 19, 28, 30, 27, 6, 10, 9, 67, 4, 5, 41, 17, 64, 13, 14, 66, 59, 7, 8, 37, 29, 40, 45, 52, 54, 47, 55, 63, 69, 50, 1, 3, 51, 65, 2, 26, 22, 11, 12, 48, 39, 38, 49, 43, 53, 58, 36, 35, 74, 73, 46, 44, 42]

function complete_parameter_values(parameters::AbstractVector)
    @assert length(parameters) == length(PARAMETER_NAMES)
    complete_parameters = Vector{eltype(parameters)}(undef, length(COMPLETE_PARAMETER_NAMES))
    complete_parameters[32] = parameters[32]
    complete_parameters[5] = parameters[5]
    complete_parameters[36] = parameters[36]
    complete_parameters[38] = parameters[38]
    complete_parameters[17] = parameters[17]
    complete_parameters[22] = parameters[22]
    complete_parameters[28] = parameters[28]
    complete_parameters[3] = parameters[3]
    complete_parameters[9] = parameters[9]
    complete_parameters[19] = parameters[19]
    complete_parameters[12] = parameters[12]
    complete_parameters[21] = parameters[21]
    complete_parameters[23] = parameters[23]
    complete_parameters[27] = parameters[27]
    complete_parameters[30] = parameters[30]
    complete_parameters[13] = parameters[13]
    complete_parameters[31] = parameters[31]
    complete_parameters[37] = parameters[37]
    complete_parameters[14] = parameters[14]
    complete_parameters[15] = parameters[15]
    complete_parameters[34] = parameters[34]
    complete_parameters[11] = parameters[11]
    complete_parameters[35] = parameters[35]
    complete_parameters[16] = parameters[16]
    complete_parameters[7] = parameters[7]
    complete_parameters[8] = parameters[8]
    complete_parameters[1] = parameters[1]
    complete_parameters[18] = parameters[18]
    complete_parameters[24] = parameters[24]
    complete_parameters[20] = parameters[20]
    complete_parameters[10] = parameters[10]
    complete_parameters[6] = parameters[6]
    complete_parameters[29] = parameters[29]
    complete_parameters[33] = parameters[33]
    complete_parameters[4] = parameters[4]
    complete_parameters[25] = parameters[25]
    complete_parameters[2] = parameters[2]
    complete_parameters[26] = parameters[26]
    complete_parameters[39] = complete_parameters[36] / complete_parameters[29]
    complete_parameters[40] = complete_parameters[32] / complete_parameters[29]
    complete_parameters[41] = complete_parameters[31] / complete_parameters[29]
    complete_parameters[42] = complete_parameters[37] / complete_parameters[29]
    complete_parameters[43] = complete_parameters[33] / complete_parameters[29]
    complete_parameters[44] = complete_parameters[30] / complete_parameters[29]
    complete_parameters[45] = complete_parameters[35] / complete_parameters[29]
    complete_parameters[46] = complete_parameters[38] / complete_parameters[29]
    complete_parameters[47] = complete_parameters[34] / complete_parameters[29]
    return complete_parameters
end

function residuals_original(parameters::AbstractVector, solution::AbstractVector)
    @assert length(parameters) == length(PARAMETER_NAMES)
    @assert length(solution) == length(ORIGINAL_SOLUTION_NAMES)
    complete_parameters = complete_parameter_values(parameters)
    return [
        -(solution[48]) + complete_parameters[6] * ((1 - complete_parameters[18]) * solution[48] + solution[36] * (solution[50] * solution[53] - complete_parameters[11] ^ -1 * solution[50] * (-1 + exp(complete_parameters[11] * (-1 + solution[53])))) * (solution[1] - complete_parameters[9] * solution[1]) ^ -(complete_parameters[16])),
        -(solution[49]) + complete_parameters[6] * ((1 - complete_parameters[18]) * solution[49] + solution[36] * (solution[51] * solution[54] - complete_parameters[11] ^ -1 * solution[51] * (-1 + exp(complete_parameters[11] * (-1 + solution[54])))) * (solution[2] - complete_parameters[9] * solution[2]) ^ -(complete_parameters[16])),
        -(solution[50]) + complete_parameters[5] * solution[35] * solution[41] * solution[9] ^ (1 - complete_parameters[5]) * (solution[7] * solution[53]) ^ (-1 + complete_parameters[5]),
        -(solution[51]) + complete_parameters[5] * solution[35] * solution[42] * solution[10] ^ (1 - complete_parameters[5]) * (solution[8] * solution[54]) ^ (-1 + complete_parameters[5]),
        -(solution[3]) + solution[20],
        -(solution[3]) + complete_parameters[2] * solution[32],
        -(solution[4]) + solution[21],
        -(solution[4]) + complete_parameters[2] * solution[32],
        -(solution[9]) + solution[44] ^ -1 * solution[11],
        -(solution[12]) + solution[10] * (solution[27] * solution[26] ^ -1) ^ (complete_parameters[3] ^ -1 * (-1 - complete_parameters[3])),
        solution[12] - solution[10],
        solution[12] + complete_parameters[3] ^ -1 * solution[10] * solution[26] ^ -1 * (-1 - complete_parameters[3]) * (-(solution[25]) + solution[27]) * (solution[27] * solution[26] ^ -1) ^ (-1 + complete_parameters[3] ^ -1 * (-1 - complete_parameters[3])),
        solution[15] - solution[12] * (-(solution[25]) + solution[27]),
        solution[14] - solution[29] * (-(solution[42]) + solution[13]) * solution[13] ^ (-(complete_parameters[1] ^ -1) * (1 + complete_parameters[1])),
        -(solution[16]) + solution[36] ^ -1 * solution[48] * (solution[1] - complete_parameters[9] * solution[1]) ^ complete_parameters[16],
        -(solution[17]) + solution[36] ^ -1 * solution[49] * (solution[2] - complete_parameters[9] * solution[2]) ^ complete_parameters[16],
        -(solution[24]) + solution[35] * solution[41] * (1 - complete_parameters[5]) * solution[9] ^ -(complete_parameters[5]) * (solution[7] * solution[53]) ^ complete_parameters[5],
        -(solution[26]) + solution[35] * solution[42] * (1 - complete_parameters[5]) * solution[10] ^ -(complete_parameters[5]) * (solution[8] * solution[54]) ^ complete_parameters[5],
        -(solution[29]) + solution[31],
        solution[30] - solution[43] * solution[28],
        -(solution[31]) + solution[29] * solution[13] ^ (-(complete_parameters[1] ^ -1) * (1 + complete_parameters[1])),
        complete_parameters[6] * solution[36] * (solution[2] - complete_parameters[9] * solution[2]) ^ -(complete_parameters[16]) - solution[36] * solution[19] ^ -1 * (solution[2] - complete_parameters[9] * solution[2]) ^ -(complete_parameters[16]),
        complete_parameters[6] * solution[36] * solution[45] ^ -1 * (solution[1] - complete_parameters[9] * solution[1]) ^ -(complete_parameters[16]) - solution[36] * solution[18] ^ -1 * (solution[1] - complete_parameters[9] * solution[1]) ^ -(complete_parameters[16]),
        solution[29] * solution[13] ^ (-(complete_parameters[1] ^ -1) * (1 + complete_parameters[1])) - complete_parameters[1] ^ -1 * solution[29] * (1 + complete_parameters[1]) * (-(solution[42]) + solution[13]) * solution[13] ^ (-1 - complete_parameters[1] ^ -1 * (1 + complete_parameters[1])),
        solution[36] * solution[25] * (solution[2] - complete_parameters[9] * solution[2]) ^ -(complete_parameters[16]) - complete_parameters[10] * solution[36] * solution[34] * solution[12] ^ complete_parameters[17],
        -1 + complete_parameters[21] * (solution[45] ^ -1 * solution[45] ^ complete_parameters[8]) ^ -(complete_parameters[1] ^ -1) + (1 - complete_parameters[21]) * solution[47] ^ -(complete_parameters[1] ^ -1),
        -1 + (1 - complete_parameters[20]) * (solution[52] * solution[24] ^ -1) ^ -(complete_parameters[3] ^ -1) + complete_parameters[20] * (solution[24] * solution[24] ^ -1) ^ -(complete_parameters[3] ^ -1) * (solution[45] ^ -1 * solution[45] ^ complete_parameters[7]) ^ -(complete_parameters[3] ^ -1),
        (-(complete_parameters[4]) - solution[30]) + solution[35] * solution[9] ^ (1 - complete_parameters[5]) * (solution[7] * solution[53]) ^ complete_parameters[5],
        (-(complete_parameters[4]) - solution[29] * solution[13] ^ (-(complete_parameters[1] ^ -1) * (1 + complete_parameters[1]))) + solution[35] * solution[10] ^ (1 - complete_parameters[5]) * (solution[8] * solution[54]) ^ complete_parameters[5],
        (complete_parameters[44] * 0 - log(solution[36])) + complete_parameters[23] * log(solution[36]),
        (-(complete_parameters[41]) * 0 - log(solution[34])) + complete_parameters[24] * log(solution[34]),
        (complete_parameters[40] * 0 - log(solution[33])) + complete_parameters[25] * log(solution[33]),
        (complete_parameters[47] * 0 - solution[37]) + solution[38],
        (complete_parameters[43] * 0 - log(solution[35])) + complete_parameters[26] * log(solution[35]),
        (complete_parameters[45] * 0 - solution[39]) + solution[40] * (1 + complete_parameters[1]),
        (complete_parameters[39] * 0 - log(solution[32])) + complete_parameters[27] * log(solution[32]),
        -(solution[37]) + complete_parameters[6] * complete_parameters[20] * solution[37] * (solution[52] ^ -1 * solution[52]) ^ (complete_parameters[3] ^ -1) * (solution[45] ^ -1 * solution[45] ^ complete_parameters[7]) ^ -(complete_parameters[3] ^ -1) + solution[36] * solution[52] * solution[9] * (1 + complete_parameters[3]) ^ -1 * (solution[1] - complete_parameters[9] * solution[1]) ^ -(complete_parameters[16]) * (solution[52] * solution[24] ^ -1) ^ (-(complete_parameters[3] ^ -1) * (1 + complete_parameters[3])),
        -(solution[38]) + complete_parameters[6] * complete_parameters[20] * solution[38] * (solution[52] ^ -1 * solution[52]) ^ (complete_parameters[3] ^ -1 * (1 + complete_parameters[3]) * (1 + complete_parameters[17])) * (solution[45] ^ -1 * solution[45] ^ complete_parameters[7]) ^ (-(complete_parameters[3] ^ -1) * (1 + complete_parameters[3]) * (1 + complete_parameters[17])) + complete_parameters[10] * solution[36] * solution[34] * (solution[9] * (solution[52] * solution[24] ^ -1) ^ (-(complete_parameters[3] ^ -1) * (1 + complete_parameters[3]))) ^ (1 + complete_parameters[17]),
        -(solution[39]) + complete_parameters[6] * complete_parameters[21] * solution[47] * solution[39] * solution[47] ^ -1 * (solution[45] ^ -1 * solution[45] ^ complete_parameters[8]) ^ -(complete_parameters[1] ^ -1) + solution[36] * solution[47] * solution[28] * (solution[1] - complete_parameters[9] * solution[1]) ^ -(complete_parameters[16]),
        -(solution[40]) + complete_parameters[6] * complete_parameters[21] * solution[40] * (solution[45] ^ -1 * solution[45] ^ complete_parameters[8]) ^ (-(complete_parameters[1] ^ -1) * (1 + complete_parameters[1])) + solution[36] * solution[41] * solution[28] * (solution[1] - complete_parameters[9] * solution[1]) ^ -(complete_parameters[16]),
        -(solution[44]) + (1 - complete_parameters[20]) * (solution[52] * solution[24] ^ -1) ^ (-(complete_parameters[3] ^ -1) * (1 + complete_parameters[3])) + complete_parameters[20] * solution[44] * (solution[24] * solution[45] ^ -1 * solution[24] ^ -1 * solution[45] ^ complete_parameters[7]) ^ (-(complete_parameters[3] ^ -1) * (1 + complete_parameters[3])),
        -(solution[43]) + (1 - complete_parameters[21]) * solution[47] ^ (-(complete_parameters[1] ^ -1) * (1 + complete_parameters[1])) + complete_parameters[21] * solution[43] * (solution[45] ^ -1 * solution[45] ^ complete_parameters[8]) ^ (-(complete_parameters[1] ^ -1) * (1 + complete_parameters[1])),
        -(solution[7]) + solution[7] * (1 - complete_parameters[18]) + solution[5] * (1 - 0.5 * complete_parameters[19] * (-1 + solution[5] ^ -1 * solution[33] * solution[5]) ^ 2),
        -(solution[8]) + solution[8] * (1 - complete_parameters[18]) + solution[6] * (1 - 0.5 * complete_parameters[19] * (-1 + solution[6] ^ -1 * solution[33] * solution[6]) ^ 2),
        (solution[22] - complete_parameters[6] * solution[22]) - solution[36] * ((1 - complete_parameters[16]) ^ -1 * (solution[1] - complete_parameters[9] * solution[1]) ^ (1 - complete_parameters[16]) - complete_parameters[10] * solution[34] * (1 + complete_parameters[17]) ^ -1 * solution[11] ^ (1 + complete_parameters[17])),
        (solution[23] - complete_parameters[6] * solution[23]) - solution[36] * ((1 - complete_parameters[16]) ^ -1 * (solution[2] - complete_parameters[9] * solution[2]) ^ (1 - complete_parameters[16]) - complete_parameters[10] * solution[34] * (1 + complete_parameters[17]) ^ -1 * solution[12] ^ (1 + complete_parameters[17])),
        -(solution[36]) * (solution[1] - complete_parameters[9] * solution[1]) ^ -(complete_parameters[16]) + solution[48] * ((1 - 0.5 * complete_parameters[19] * (-1 + solution[5] ^ -1 * solution[33] * solution[5]) ^ 2) - complete_parameters[19] * solution[5] ^ -1 * solution[33] * solution[5] * (-1 + solution[5] ^ -1 * solution[33] * solution[5])) + complete_parameters[6] * complete_parameters[19] * solution[5] ^ -2 * solution[33] * solution[48] * solution[5] ^ 2 * (-1 + solution[5] ^ -1 * solution[33] * solution[5]),
        -(solution[36]) * (solution[2] - complete_parameters[9] * solution[2]) ^ -(complete_parameters[16]) + solution[49] * ((1 - 0.5 * complete_parameters[19] * (-1 + solution[6] ^ -1 * solution[33] * solution[6]) ^ 2) - complete_parameters[19] * solution[6] ^ -1 * solution[33] * solution[6] * (-1 + solution[6] ^ -1 * solution[33] * solution[6])) + complete_parameters[6] * complete_parameters[19] * solution[6] ^ -2 * solution[33] * solution[49] * solution[6] ^ 2 * (-1 + solution[6] ^ -1 * solution[33] * solution[6]),
        (((-(solution[1]) - solution[5]) - solution[20]) + solution[28]) - complete_parameters[11] ^ -1 * solution[50] * solution[7] * (-1 + exp(complete_parameters[11] * (-1 + solution[53]))),
        (((((-(solution[2]) - solution[6]) + solution[15]) - solution[21]) + solution[29] + solution[12] * solution[25]) - solution[10] * solution[26]) - complete_parameters[11] ^ -1 * solution[51] * solution[8] * (-1 + exp(complete_parameters[11] * (-1 + solution[54]))),
        solution[36] * (solution[7] * solution[50] - solution[50] * solution[7] * exp(complete_parameters[11] * (-1 + solution[53]))) * (solution[1] - complete_parameters[9] * solution[1]) ^ -(complete_parameters[16]),
        solution[36] * (solution[8] * solution[51] - solution[51] * solution[8] * exp(complete_parameters[11] * (-1 + solution[54]))) * (solution[2] - complete_parameters[9] * solution[2]) ^ -(complete_parameters[16]),
        (complete_parameters[46] * 0 - log(solution[46])) + complete_parameters[28] * log(solution[46]) + log(solution[55]) * (1 - complete_parameters[28]),
        ((-(solution[56]) + complete_parameters[42] * 0) - log(solution[18] ^ -1 * solution[18])) + complete_parameters[14] * (-(log(solution[45] ^ -1 * solution[45])) + log(solution[45] ^ -1 * solution[45])) + complete_parameters[15] * ((-(log(solution[28] ^ -1 * solution[28])) + log(solution[28] ^ -1 * solution[28]) + log(solution[29] ^ -1 * solution[29])) - log(solution[29] ^ -1 * solution[29])) + complete_parameters[22] * log(solution[18] ^ -1 * solution[18]) + (1 - complete_parameters[22]) * (log(solution[46]) + complete_parameters[12] * (-(log(solution[46])) + log(solution[45] ^ -1 * solution[45])) + complete_parameters[13] * (log(solution[28] ^ -1 * solution[28]) - log(solution[29] ^ -1 * solution[29]))),
        1 - solution[46],
        solution[45] - solution[46],
    ]
end

function residuals_auxiliary(parameters::AbstractVector, solution::AbstractVector)
    @assert length(parameters) == length(PARAMETER_NAMES)
    @assert length(solution) == length(AUXILIARY_SOLUTION_NAMES)
    complete_parameters = complete_parameter_values(parameters)
    return [
        solution[55] - complete_parameters[11] * (solution[53] - 1),
        solution[65] - (-(solution[1]) * complete_parameters[9] + solution[1]),
        complete_parameters[6] * ((solution[36] * (solution[50] * solution[53] - (solution[50] * (exp(solution[55]) - 1)) / complete_parameters[11])) / solution[65] ^ complete_parameters[16] + solution[48] * (1 - complete_parameters[18])) - solution[48],
        solution[66] - complete_parameters[11] * (solution[54] - 1),
        solution[67] - (-(solution[2]) * complete_parameters[9] + solution[2]),
        complete_parameters[6] * ((solution[36] * (solution[51] * solution[54] - (solution[51] * (exp(solution[66]) - 1)) / complete_parameters[11])) / solution[67] ^ complete_parameters[16] + solution[49] * (1 - complete_parameters[18])) - solution[49],
        solution[68] - solution[7] * solution[53],
        solution[9] ^ (1 - complete_parameters[5]) * complete_parameters[5] * solution[35] * solution[41] * solution[68] ^ (complete_parameters[5] - 1) - solution[50],
        solution[69] - solution[8] * solution[54],
        solution[10] ^ (1 - complete_parameters[5]) * complete_parameters[5] * solution[35] * solution[42] * solution[69] ^ (complete_parameters[5] - 1) - solution[51],
        -(solution[3]) + solution[20],
        -(solution[3]) + complete_parameters[2] * solution[32],
        -(solution[4]) + solution[21],
        complete_parameters[2] * solution[32] - solution[4],
        -(solution[9]) + solution[11] / solution[44],
        solution[70] - solution[27] / solution[26],
        solution[10] * solution[70] ^ ((-(complete_parameters[3]) - 1) / complete_parameters[3]) - solution[12],
        -(solution[10]) + solution[12],
        (solution[10] * solution[70] ^ (-1 + (-(complete_parameters[3]) - 1) / complete_parameters[3]) * (-(solution[25]) + solution[27]) * (-(complete_parameters[3]) - 1)) / (solution[26] * complete_parameters[3]) + solution[12],
        -(solution[12]) * (-(solution[25]) + solution[27]) + solution[15],
        solution[14] - (solution[29] * (solution[13] - solution[42])) / solution[13] ^ ((complete_parameters[1] + 1) / complete_parameters[1]),
        solution[71] - (-(solution[1]) * complete_parameters[9] + solution[1]),
        -(solution[16]) + (solution[48] * solution[71] ^ complete_parameters[16]) / solution[36],
        solution[72] - (-(solution[2]) * complete_parameters[9] + solution[2]),
        -(solution[17]) + (solution[49] * solution[72] ^ complete_parameters[16]) / solution[36],
        -(solution[24]) + (solution[35] * solution[41] * solution[68] ^ complete_parameters[5] * (1 - complete_parameters[5])) / solution[9] ^ complete_parameters[5],
        -(solution[26]) + (solution[35] * solution[42] * solution[69] ^ complete_parameters[5] * (1 - complete_parameters[5])) / solution[10] ^ complete_parameters[5],
        -(solution[29]) + solution[31],
        -(solution[28]) * solution[43] + solution[30],
        -(solution[31]) + solution[29] / solution[13] ^ ((complete_parameters[1] + 1) / complete_parameters[1]),
        (complete_parameters[6] * solution[36]) / solution[67] ^ complete_parameters[16] - solution[36] / (solution[19] * solution[72] ^ complete_parameters[16]),
        (complete_parameters[6] * solution[36]) / (solution[45] * solution[65] ^ complete_parameters[16]) - solution[36] / (solution[18] * solution[71] ^ complete_parameters[16]),
        (-(solution[13] ^ (-1 - (complete_parameters[1] + 1) / complete_parameters[1])) * solution[29] * (solution[13] - solution[42]) * (complete_parameters[1] + 1)) / complete_parameters[1] + solution[29] / solution[13] ^ ((complete_parameters[1] + 1) / complete_parameters[1]),
        -(solution[12] ^ complete_parameters[17]) * solution[34] * solution[36] * complete_parameters[10] + (solution[25] * solution[36]) / solution[72] ^ complete_parameters[16],
        solution[56] - solution[45] ^ complete_parameters[8] / solution[45],
        (complete_parameters[21] / solution[56] ^ (1 / complete_parameters[1]) - 1) + (1 - complete_parameters[21]) / solution[47] ^ (1 / complete_parameters[1]),
        solution[57] - solution[52] / solution[24],
        solution[58] - solution[45] ^ complete_parameters[7] / solution[45],
        (complete_parameters[20] / solution[58] ^ (1 / complete_parameters[3]) - 1) + (1 - complete_parameters[20]) / solution[57] ^ (1 / complete_parameters[3]),
        (solution[9] ^ (1 - complete_parameters[5]) * solution[35] * solution[68] ^ complete_parameters[5] - complete_parameters[4]) - solution[30],
        (solution[10] ^ (1 - complete_parameters[5]) * solution[35] * solution[69] ^ complete_parameters[5] - complete_parameters[4]) - solution[29] / solution[13] ^ ((complete_parameters[1] + 1) / complete_parameters[1]),
        complete_parameters[23] * log(solution[36]) - log(solution[36]),
        complete_parameters[24] * log(solution[34]) - log(solution[34]),
        complete_parameters[25] * log(solution[33]) - log(solution[33]),
        -(solution[37]) + solution[38],
        complete_parameters[26] * log(solution[35]) - log(solution[35]),
        -(solution[39]) + solution[40] * (complete_parameters[1] + 1),
        complete_parameters[27] * log(solution[32]) - log(solution[32]),
        solution[59] - solution[45] ^ complete_parameters[7] / solution[45],
        ((solution[9] * solution[36] * solution[52]) / (solution[57] ^ ((complete_parameters[3] + 1) / complete_parameters[3]) * solution[71] ^ complete_parameters[16] * (complete_parameters[3] + 1)) + (complete_parameters[6] * solution[37] * complete_parameters[20]) / solution[59] ^ (1 / complete_parameters[3])) - solution[37],
        solution[60] - solution[9] / solution[57] ^ ((complete_parameters[3] + 1) / complete_parameters[3]),
        ((complete_parameters[6] * solution[38] * complete_parameters[20]) / solution[59] ^ (((complete_parameters[3] + 1) * (complete_parameters[17] + 1)) / complete_parameters[3]) + solution[34] * solution[36] * complete_parameters[10] * solution[60] ^ (complete_parameters[17] + 1)) - solution[38],
        solution[61] - solution[45] ^ complete_parameters[8] / solution[45],
        ((solution[28] * solution[36] * solution[47]) / solution[71] ^ complete_parameters[16] + (complete_parameters[6] * solution[39] * complete_parameters[21]) / solution[61] ^ (1 / complete_parameters[1])) - solution[39],
        ((solution[28] * solution[36] * solution[41]) / solution[71] ^ complete_parameters[16] + (complete_parameters[6] * solution[40] * complete_parameters[21]) / solution[61] ^ ((complete_parameters[1] + 1) / complete_parameters[1])) - solution[40],
        solution[62] - solution[45] ^ complete_parameters[7] / solution[45],
        ((solution[44] * complete_parameters[20]) / solution[62] ^ ((complete_parameters[3] + 1) / complete_parameters[3]) - solution[44]) + (1 - complete_parameters[20]) / solution[57] ^ ((complete_parameters[3] + 1) / complete_parameters[3]),
        ((solution[43] * complete_parameters[21]) / solution[56] ^ ((complete_parameters[1] + 1) / complete_parameters[1]) - solution[43]) + (1 - complete_parameters[21]) / solution[47] ^ ((complete_parameters[1] + 1) / complete_parameters[1]),
        (solution[5] * (-0.5 * complete_parameters[19] * (solution[33] - 1) ^ 2 + 1) + solution[7] * (1 - complete_parameters[18])) - solution[7],
        (solution[6] * (-0.5 * complete_parameters[19] * (solution[33] - 1) ^ 2 + 1) + solution[8] * (1 - complete_parameters[18])) - solution[8],
        (-(solution[22]) * complete_parameters[6] + solution[22]) - solution[36] * ((-(solution[11] ^ (complete_parameters[17] + 1)) * solution[34] * complete_parameters[10]) / (complete_parameters[17] + 1) + solution[71] ^ (1 - complete_parameters[16]) / (1 - complete_parameters[16])),
        (-(solution[23]) * complete_parameters[6] + solution[23]) - solution[36] * ((-(solution[12] ^ (complete_parameters[17] + 1)) * solution[34] * complete_parameters[10]) / (complete_parameters[17] + 1) + solution[72] ^ (1 - complete_parameters[16]) / (1 - complete_parameters[16])),
        (complete_parameters[6] * solution[33] * solution[48] * complete_parameters[19] * (solution[33] - 1) - solution[36] / solution[71] ^ complete_parameters[16]) + solution[48] * ((-(solution[33]) * complete_parameters[19] * (solution[33] - 1) - 0.5 * complete_parameters[19] * (solution[33] - 1) ^ 2) + 1),
        (complete_parameters[6] * solution[33] * solution[49] * complete_parameters[19] * (solution[33] - 1) - solution[36] / solution[72] ^ complete_parameters[16]) + solution[49] * ((-(solution[33]) * complete_parameters[19] * (solution[33] - 1) - 0.5 * complete_parameters[19] * (solution[33] - 1) ^ 2) + 1),
        solution[63] - complete_parameters[11] * (solution[53] - 1),
        (((-(solution[1]) - solution[5]) - (solution[7] * solution[50] * (exp(solution[63]) - 1)) / complete_parameters[11]) - solution[20]) + solution[28],
        solution[64] - complete_parameters[11] * (solution[54] - 1),
        (((((-(solution[2]) - solution[6]) - (solution[8] * solution[51] * (exp(solution[64]) - 1)) / complete_parameters[11]) - solution[10] * solution[26]) + solution[12] * solution[25] + solution[15]) - solution[21]) + solution[29],
        (solution[36] * (-(solution[7]) * solution[50] * exp(solution[63]) + solution[7] * solution[50])) / solution[71] ^ complete_parameters[16],
        (solution[36] * (-(solution[8]) * solution[51] * exp(solution[64]) + solution[8] * solution[51])) / solution[72] ^ complete_parameters[16],
        (complete_parameters[28] * log(solution[46]) + (1 - complete_parameters[28]) * log(solution[73])) - log(solution[46]),
        -(solution[74]) + (1 - complete_parameters[22]) * (-(complete_parameters[12]) * log(solution[46]) + log(solution[46])),
        1 - solution[46],
        solution[45] - solution[46],
    ]
end

function residuals_blocks(parameters::AbstractVector, solution::AbstractVector)
    return residuals_auxiliary(parameters, solution)[BLOCK_EQUATION_ORDER]
end

export MODEL_NAME, SOURCE_MODEL_FILE, NSSS_SOLUTION_ERROR, NSSS_RESIDUAL_NORM
export PARAMETER_NAMES, PARAMETER_VALUES, COMPLETE_PARAMETER_NAMES, COMPLETE_PARAMETER_VALUES
export ORIGINAL_SOLUTION_NAMES, ORIGINAL_SOLUTION_VALUES
export AUXILIARY_SOLUTION_NAMES, AUXILIARY_SOLUTION_VALUES
export ALL_AUXILIARY_VARIABLE_NAMES, ALL_AUXILIARY_VARIABLE_VALUES
export DEFAULTED_NSSS_SOLUTION_NAMES
export ORIGINAL_NSSS_EQUATIONS, AUXILIARY_NSSS_EQUATIONS, CALIBRATION_EQUATIONS
export BLOCKS, BLOCK_EQUATION_ORDER, residuals_original, residuals_auxiliary, residuals_blocks
end
