# commonly used DocStrings
const MODEL® = "`𝓂`: object created by [`@model`](@ref) and [`@parameters`](@ref)."
const PARAMETER_VALUES® = "`parameters` [Type: `Vector`]: Parameter values in alphabetical order (sorted by parameter name)."
const PARAMETERS® = "`parameters` [Default: `nothing`]: If `nothing` is provided, the solution is calculated for the parameters defined previously. Acceptable inputs are a `Vector` of parameter values, a `Vector` or `Tuple` of `Pair`s of the parameter `Symbol` or `String` and value. If the new parameter values differ from the previously defined the solution will be recalculated."
const STEADY_STATE_FUNCTION® = "`steady_state_function` [Default: `missing`, Type: `Union{Function, Symbol, Nothing, Missing}`]: Custom steady state routine applied instead of the internal solver when provided; accepts either `f(parameters)` returning `[variables; calibrated parameters]` or `f!(out, parameters)` filling an output vector in the same order. Use `nothing` to clear any previously set function and rely on the internal solver; `missing` keeps the current setting."
# const VARIABLES® = "`variables` [Default: `$(DEFAULT_VARIABLES_EXCLUDING_OBC)`]: variables for which to show the results. Inputs can be a variable name passed on as either a `Symbol` or `String` (e.g. `:y` or `\"y\"`), or `Tuple`, `Matrix` or `Vector` of `String` or `Symbol`. Any variables not part of the model will trigger a warning. `$(DEFAULT_VARIABLES_EXCLUDING_AUX_AND_OBC)` contains all shocks less those related to auxiliary variables and related to occasionally binding constraints (obc). `$(DEFAULT_VARIABLES_EXCLUDING_OBC)` contains all shocks less those related to auxiliary variables. `$(DEFAULT_VARIABLE_SELECTION)` will contain all variables."
VARIABLES® = x -> "`variables` [Default: `$x`]: variables for which to show the results. Inputs can be a variable name passed on as either a `Symbol` or `String` (e.g. `:y` or `\"y\"`), or `Tuple`, `Matrix` or `Vector` of `String` or `Symbol`. Any variables not part of the model will trigger a warning. `$(DEFAULT_VARIABLES_EXCLUDING_AUX_AND_OBC)` contains all shocks less those related to auxiliary variables and related to occasionally binding constraints (obc). `$(DEFAULT_VARIABLES_EXCLUDING_OBC)` contains all shocks less those related to auxiliary variables. `$(DEFAULT_VARIABLE_SELECTION)` will contain all variables."
const SHOCKS® = "`shocks` [Default: `$(DEFAULT_SHOCKS_EXCLUDING_OBC)`]: shocks for which to calculate the IRFs. Inputs can be a shock name passed on as either a `Symbol` or `String` (e.g. `:y`, or `\"y\"`), or `Tuple`, `Matrix` or `Vector` of `String` or `Symbol`. `:simulate` triggers random draws of all shocks (excluding occasionally binding constraints (obc) related shocks). `$(DEFAULT_SHOCKS_EXCLUDING_OBC)` will contain all shocks but not the obc related ones. `$(DEFAULT_SHOCK_SELECTION)` will contain also the obc related shocks. A series of shocks can be passed on using either a `Matrix{Float64}`, or a `KeyedArray{Float64}` as input with shocks (`Symbol` or `String`) in rows and periods in columns. The `KeyedArray` type is provided by the `AxisKeys` package. The period of the simulation will correspond to the length of the input in the period dimension + the number of periods defined in `periods`. If the series of shocks is input as a `KeyedArray{Float64}` make sure to name the rows with valid shock names of type `Symbol`. Any shocks not part of the model will trigger a warning. `:none` in combination with an `initial_state` can be used for deterministic simulations."
const DERIVATIVES® = "`derivatives` [Default: `$(DEFAULT_DERIVATIVES_FLAG)`, Type: `Bool`]: calculate derivatives with respect to the parameters."
const PERIODS® = "`periods` [Default: `$(DEFAULT_PERIODS)`, Type: `Int`]: number of periods for which to calculate the output. In case a matrix of shocks was provided, periods defines how many periods after the series of shocks the output continues."
const NEGATIVE_SHOCK® = "`negative_shock` [Default: `$(DEFAULT_NEGATIVE_SHOCK)`, Type: `Bool`]: if true, calculates IRFs for a negative shock. Only affects shocks that are not passed on as a `Matrix` or `KeyedArray` or set to `:none`."
const GENERALISED_IRF® = "`generalised_irf` [Default: `$(DEFAULT_GENERALISED_IRF)`, Type: `Bool`]: calculate generalised IRFs. Relevant for nonlinear (higher order perturbation) solutions only. Reference steady state for deviations is the stochastic steady state. `initial_state` has no effect on generalised IRFs. Occasionally binding constraint are not respected for generalised IRF."
const GENERALISED_IRF_WARMUP_ITERATIONS® = "`generalised_irf_warmup_iterations` [Default: `$(DEFAULT_GENERALISED_IRF_WARMUP)`, Type: `Int`]: number of warm-up iterations used to draw the baseline paths in the generalised IRF simulation. Only applied when `generalised_irf = true`."
const GENERALISED_IRF_DRAWS® = "`generalised_irf_draws` [Default: `$(DEFAULT_GENERALISED_IRF_DRAWS)`, Type: `Int`]: number of Monte Carlo draws used to compute the generalised IRF. Only applied when `generalised_irf = true`."
const ALGORITHM® = "`algorithm` [Default: `$(DEFAULT_ALGORITHM)`, Type: `Symbol`]: algorithm to solve for the dynamics of the model. Available algorithms: `:first_order`, `:second_order`, `:pruned_second_order`, `:third_order`, `:pruned_third_order`"
const FILTER® = "`filter` [Default: selector that chooses `$(DEFAULT_FILTER_SELECTOR(DEFAULT_ALGORITHM))` in case `algorithm = $(DEFAULT_ALGORITHM)` and `:inversion` otherwise, Type: `Symbol`]: filter used to compute the variables and shocks given the data, model, and parameters. The Kalman filter (`:kalman`) is exact but only valid for linear problems. The inversion filter (`:inversion`) works for linear and nonlinear models and backs out the structural shocks that reproduce the data exactly (so it admits no measurement error and needs at least as many shocks as observables). It is by far the fastest of the nonlinear options, but it can fail: at higher order it solves a nonlinear system per period, and if no shock reproduces the observation — or the solver does not converge to one — the whole likelihood is rejected rather than merely degraded. Because it pins the state down exactly, its smoothed and filtered estimates are the same object. The particle filters integrate the shocks out by Monte Carlo and work for linear and nonlinear models: `:bootstrap_particle` (sequential importance resampling), `:auxiliary_particle` (look-ahead proposal), `:tempered_particle` (bridges from the prior) and `:guided_particle` (conditionally optimal proposal). `:guided_particle` draws each shock from its own conditional given the ancestor and the observation, rather than blindly, and is usually both the cheapest and the most accurate of the four. They require measurement error (see `measurement_error`) and are stochastic, non-differentiable estimators suited to gradient-free samplers; `:particle` is an alias for `:guided_particle`. Smoothing (`smooth = true`) is available for the Kalman filter (Durbin-Koopman) and the particle filters (fixed-interval smoothing along the filter genealogy), but not for the inversion filter. If a nonlinear solution algorithm is selected and the default is used, the inversion filter is applied automatically. See the Filters section of the documentation for guidance on choosing between them."
const LEVELS® = "return levels or absolute deviations from the relevant steady state corresponding to the solution algorithm (e.g. stochastic steady state for higher order solution algorithms)."
const CONDITIONS® = "`conditions` [Type: `Union{Matrix{Union{Nothing,Float64}}, SparseMatrixCSC{Float64}, KeyedArray{Union{Nothing,Float64}}, KeyedArray{Float64}}`]: conditions for which to find the corresponding shocks. The input can have multiple formats, but for all types of entries, the first dimension corresponds to variables and the second dimension to the number of periods. The conditions can be specified using a matrix of type `Matrix{Union{Nothing,Float64}}`. In this case the conditions are matrix elements of type `Float64` and all remaining (free) entries are `nothing`. A `SparseMatrixCSC{Float64}` can also be used as input. In this case only non-zero elements are taken as conditions. Note that conditioning variables to be zero using a `SparseMatrixCSC{Float64}` as input is not possible (use other input formats to do so). Another possibility to input conditions is by using a `KeyedArray`. The `KeyedArray` type is provided by the `AxisKeys` package. A `KeyedArray{Union{Nothing,Float64}}` can be used where, similar to `Matrix{Union{Nothing,Float64}}`, all entries of type `Float64` are recognised as conditions and all other entries have to be `nothing`. Furthermore, in the primary axis a subset of variables (of type `Symbol` or `String`) for which conditions are specified can be included and all other variables are considered free. The same goes for the case when using `KeyedArray{Float64}}` as input, whereas in this case the conditions for the specified variables bind for all periods specified in the `KeyedArray`, because there are no `nothing` entries permitted with this type."
const SHOCK_CONDITIONS® = "`shocks` [Default: `nothing`, Type: `Union{Matrix{Union{Nothing,Float64}}, SparseMatrixCSC{Float64}, KeyedArray{Union{Nothing,Float64}}, KeyedArray{Float64}, Nothing}`]: known values of shocks. This argument allows including certain shock values. By entering restrictions on the shocks in this way the problem to match the conditions on endogenous variables is restricted to the remaining free shocks in the respective period. The input can have multiple formats, but for all types of entries, the first dimension corresponds to shocks and the second dimension to the number of periods. `shocks` can be specified using a matrix of type `Matrix{Union{Nothing,Float64}}`. In this case the shocks are matrix elements of type `Float64` and all remaining (free) entries are `nothing`. A `SparseMatrixCSC{Float64}` can also be used as input. In this case only non-zero elements are taken as certain shock values. Note that conditioning shocks to be zero using a `SparseMatrixCSC{Float64}` as input is not possible (use other input formats to do so). Another possibility to input known shocks is by using a `KeyedArray`. The `KeyedArray` type is provided by the `AxisKeys` package. A `KeyedArray{Union{Nothing,Float64}}` can be used where, similar to `Matrix{Union{Nothing,Float64}}`, all entries of type `Float64` are recognised as known shocks and all other entries have to be `nothing`. Furthermore, in the primary axis a subset of shocks (of type `Symbol` or `String`) for which values are specified can be included and all other shocks are considered free. The same goes for the case when using `KeyedArray{Float64}}` as input, whereas in this case the values for the specified shocks bind for all periods specified in the `KeyedArray`, because there are no `nothing` entries permitted with this type."
const PARAMETER_DERIVATIVES® = "`parameter_derivatives` [Default: :all]: parameters for which to calculate partial derivatives. Inputs can be a parameter name passed on as either a `Symbol` or `String` (e.g. `:alpha`, or \"alpha\"), or `Tuple`, `Matrix` or `Vector` of `String` or `Symbol`. `:all` will include all parameters."
const DATA® = "`data` [Type: `KeyedArray`]: data matrix with variables (`String` or `Symbol`) in rows and periods in columns. Periods can have any format and will be used for the output. `missing` and `nothing` entries are treated as unobserved observations, and non-finite numeric entries are handled the same way. Interior unobserved entries remain in the sample and are handled period by period using only the available observations, while fully unobserved leading and trailing periods are removed automatically with an informational message. `KeyedArray` is provided by the `AxisKeys` package."
const SMOOTH® = "`smooth` [Default: selector that enables smoothing when `filter = $(DEFAULT_FILTER_SELECTOR(DEFAULT_ALGORITHM))` and disables it otherwise, Type: `Bool`]: whether to return smoothed (`true`) or filtered (`false`) shocks/variables. Smoothing is available for the Kalman filter (Durbin-Koopman) and for the particle filters (fixed-interval smoothing along the filter genealogy). The inversion filter identifies the state exactly, so its smoothed and filtered estimates coincide and the default turns smoothing off in that case."

# ── Measurement error and particle-filter keywords ───────────────────────────
# These appear on every function that takes a `filter`, so they live here rather
# than being restated in each docstring. `PARTICLE_FILTER_KEYWORDS®` is the whole
# block as consecutive bullet points, for functions that accept all of them.
const MEASUREMENT_ERROR® = "`measurement_error` [Default: `$(repr(DEFAULT_MEASUREMENT_ERROR))`, Type: `Union{Symbol,Real,AbstractVector{<:Real},AbstractMatrix{<:Real}}`]: covariance `H` of the Gaussian measurement error on the observables, `yₜ = C xₜ + ηₜ` with `ηₜ ~ N(0, H)`. This is a **variance**, not a standard deviation: a scalar is the common variance of every observable, a vector supplies one variance per observable, and a matrix is the full (possibly correlated) covariance. `:auto` resolves per filter: no measurement error for the Kalman and inversion filters, and `($(DEFAULT_PARTICLE_MEASUREMENT_ERROR_FRACTION) * sᵢ)^2` per observable — `sᵢ` being that observable's sample standard deviation — for the particle filters, which are degenerate without it. Measurement error is supported by the Kalman filter and required by the particle filters; it is not available for the inversion filter, which reproduces the observables exactly."
const N_PARTICLES® = "`n_particles` [Default: `$(DEFAULT_N_PARTICLES)`, Type: `Int`]: number of particles used by the particle filters. More particles reduce the Monte-Carlo variance of the likelihood at roughly linear cost."
const PARTICLE_RESAMPLING® = "`particle_resampling` [Default: `:$(DEFAULT_PARTICLE_RESAMPLING)`, Type: `Symbol`]: resampling scheme. One of `:systematic`, `:stratified`, `:multinomial`, `:residual`."
const PARTICLE_RESAMPLING_THRESHOLD® = "`particle_resampling_threshold` [Default: `$(DEFAULT_PARTICLE_RESAMPLING_THRESHOLD)`, Type: `Real`]: resample whenever the effective sample size falls below `particle_resampling_threshold * n_particles`."
const PARTICLE_INITIAL_STATE_SCALING® = "`particle_initial_state_scaling` [Default: `$(DEFAULT_PARTICLE_INITIAL_STATE_SCALING)`, Type: `Real`]: scales the covariance of the initial particle cloud around the initial state."
const PARTICLE_RNG® = "`particle_rng` [Default: `Random.default_rng()`, Type: `AbstractRNG`]: random number generator used by the particle filters (pass a seeded RNG for reproducible results)."
const PARTICLE_TARGET_RATIO® = "`particle_target_ratio` [Default: `$(DEFAULT_PARTICLE_TARGET_RATIO)`, Type: `Real`]: target inefficiency ratio that sets the bridging schedule of `:tempered_particle` and `:guided_particle` — how much weight degeneracy one intermediate step may add, which is what picks the step sizes. Lower means more, gentler bridging steps: each one then discards fewer particles at its resampling, which is the main thing limiting the accuracy of the filtered estimates. It is a more effective use of compute than raising `n_particles`, at the cost of more stages per period."
const PARTICLE_MH_STEPS® = "`particle_mh_steps` [Default: `$(DEFAULT_GUIDED_MH_STEPS)` for `filter = :guided_particle`, `$(DEFAULT_TEMPERED_MH_STEPS)` otherwise, Type: `Int`]: number of Metropolis-Hastings mutation steps per bridging stage, for `:tempered_particle` and `:guided_particle`. This is what rejuvenates the particle cloud. For `:tempered_particle`, which bridges all the way from the prior, it rather than `n_particles` is what limits accuracy — raise it first when estimates look seed-sensitive. The guided filter bridges from a proposal that is already close to the target and needs far less of it, which is why its default is lower."
const PARTICLE_MAX_STAGES® = "`particle_max_stages` [Default: `$(DEFAULT_PARTICLE_MAX_STAGES)`, Type: `Int`]: cap on the number of bridging stages per period, for `:tempered_particle` and `:guided_particle` alike. The tempered filter typically uses of the order of ten; the guided filter reaches its target in a single stage in an ordinary period and spends more only where its proposal fits badly."
const PARTICLE_MH_SCALE® = "`particle_mh_scale` [Default: `$(DEFAULT_PARTICLE_MH_SCALE)`, Type: `Real`]: starting scale of the random-walk Metropolis-Hastings proposal used in the mutation step of `:tempered_particle` and `:guided_particle`. The proposal is preconditioned by the stage's own posterior scale — which changes with the stage for the tempered filter and is the proposal covariance for the guided one — so a value near one is appropriate whatever the model, and the filter adapts the scale during the run towards a $(round(Int, 100 * DEFAULT_PARTICLE_MH_TARGET_ACCEPTANCE))% acceptance rate."
const PARTICLE_BRIDGING_KEYWORDS® = join(("- " * PARTICLE_TARGET_RATIO®,
                                  "- " * PARTICLE_MH_STEPS®,
                                  "- " * PARTICLE_MAX_STAGES®,
                                  "- " * PARTICLE_MH_SCALE®), "\n")
const PARTICLE_FILTER_KEYWORDS® = join(("- " * MEASUREMENT_ERROR®,
                                        "- " * N_PARTICLES®,
                                        "- " * PARTICLE_RESAMPLING®,
                                        "- " * PARTICLE_RESAMPLING_THRESHOLD®,
                                        "- " * PARTICLE_INITIAL_STATE_SCALING®,
                                        "- " * PARTICLE_RNG®,
                                        PARTICLE_BRIDGING_KEYWORDS®), "\n")
const ON_FAILURE_LOGLIKELIHOOD® = "`on_failure_loglikelihood` [Default: selector that returns `-1e6` for the particle filters and `-Inf` otherwise, Type: `AbstractFloat`]: value to return if the loglikelihood calculation fails (e.g. the solution did not converge). The particle filters default to a large finite penalty rather than `-Inf` because they can fail for purely stochastic reasons, and `-Inf` would kill a sampler's chain state instead of rejecting a single proposal."
const INITIAL_COVARIANCE® = "`initial_covariance` [Default: `:theoretical`, Type: `Union{Symbol,AbstractMatrix{<:Real}}`]: how to initialise the filter's state covariance (for the particle filters, the covariance the initial cloud is drawn from). `:theoretical` uses the first-order ergodic values from the Lyapunov equation, `:diagonal` starts diffuse with 10.0 along the diagonal, or supply a matrix of the appropriate size."
const DATA_IN_LEVELS® = "`data_in_levels` [Default: `$(DEFAULT_DATA_IN_LEVELS)`, Type: `Bool`]: indicator whether the data is provided in levels. If `true` the input to the data argument will have the non-stochastic steady state subtracted."
const LYAPUNOV® = "`lyapunov_algorithm` [Default: `$(DEFAULT_LYAPUNOV_ALGORITHM)`, Type: `Symbol`]: algorithm to solve Lyapunov equation (`A * X * A' + C = X`). Available algorithms: `:doubling`, `:bartels_stewart`, `:bicgstab`, `:gmres`, `:dqgmres`"
const SYLVESTER® = "`sylvester_algorithm` [Default: selector that uses `$(DEFAULT_SYLVESTER_ALGORITHM)` for smaller problems and switches to `$(DEFAULT_LARGE_SYLVESTER_ALGORITHM)` for larger problems, Type: `Union{Symbol,Vector{Symbol},Tuple{Symbol,Vararg{Symbol}}}`]: algorithm to solve the Sylvester equation (`A * X * B + C = X`). Available algorithms: `:doubling`, `:bartels_stewart`, `:bicgstab`, `:dqgmres`, `:gmres`. Input argument can contain up to two elements in a `Vector` or `Tuple`. The first (second) element corresponds to the second (third) order perturbation solutions' Sylvester equation. If only one element is provided it corresponds to the second order perturbation solutions' Sylvester equation."
const QME® = "`quadratic_matrix_equation_algorithm` [Default: selector that uses `$(DEFAULT_QME_ALGORITHM)` for smaller problems and switches to `$(DEFAULT_LARGE_QME_ALGORITHM)` when the QME problem size exceeds `$(DEFAULT_QME_THRESHOLD)`, Type: `Symbol`]: algorithm to solve quadratic matrix equation (`A * X ^ 2 + B * X + C = 0`). Available algorithms: `:schur`, `:doubling`"
const VERBOSE® = "`verbose` [Default: `$(DEFAULT_VERBOSE)`, Type: `Bool`]: print information about results of the different solvers used to solve the model (non-stochastic steady state solver, Sylvester equations, Lyapunov equation, and quadratic matrix equation)."
const TOLERANCES® = "`tol` [Default: `Tolerances()`, Type: `Tolerances`]: define various tolerances for the algorithm used to solve the model. See documentation of [`Tolerances`](@ref) for more details: `?Tolerances`."
const PLOT_ATTRIBUTES® = "`plot_attributes` [Default: `$(DEFAULT_PLOT_ATTRIBUTES)`, Type: `Dict`]: pass on plot attributes for the top-level plot (see https://docs.juliaplots.org/latest/generated/attributes_plot/). E.g. Dict(:plot_titlefontcolor => :red)."
# const PLOTS_PER_PAGE® = "`plots_per_page` [Default: `$(DEFAULT_PLOTS_PER_PAGE_LARGE)`, Type: `Int`]: how many plots to show per page"
PLOTS_PER_PAGE® = x -> "`plots_per_page` [Default: `$(x)`, Type: `Int`]: how many plots to show per page"
const SAVE_PLOTS_PATH® = "`save_plots_path` [Default: `$(DEFAULT_SAVE_PLOTS_PATH)`, Type: `String`]: path where to save plots. If the path does not exist it will be created automatically."
const SAVE_PLOTS_FORMAT® = "`save_plots_format` [Default: `$(DEFAULT_SAVE_PLOTS_FORMAT)`, Type: `Symbol`]: output format of saved plots. See [input formats compatible with GR](https://docs.juliaplots.org/latest/output/#Supported-output-file-formats) for valid formats."
const SAVE_PLOTS® = "`save_plots` [Default: `$(DEFAULT_SAVE_PLOTS)`, Type: `Bool`]: switch to save plots using path and extension from `save_plots_path` and `save_plots_format`. Each plot is saved as a separate file with a name that indicates the model name, shocks, and a running number per shock."
SAVE_PLOTS_NAME® = x -> "`save_plots_name` [Default: `$x`, Type: `Union{String, Symbol}`]: prefix used when saving plots to disk."
const SHOW_PLOTS® = "`show_plots` [Default: `$(DEFAULT_SHOW_PLOTS)`, Type: `Bool`]: show plots. Separate plots per shocks and variables depending on number of variables and `plots_per_page`."
const EXTRA_LEGEND_SPACE® = "`extra_legend_space` [Default: `$(DEFAULT_EXTRA_LEGEND_SPACE)`, Type: `Float64`]: space between the plots and the legend (useful if the plots overlap the legend)."
const MAX_ELEMENTS_PER_LEGENDS_ROW® = "`max_elements_per_legend_row` [Default: `$(DEFAULT_MAX_ELEMENTS_PER_LEGEND_ROW)`, Type: `Int`]: maximum number of elements per legend row. In other words, number of columns in legend."
const WARMUP_ITERATIONS® = "`warmup_iterations` [Default: `$(DEFAULT_WARMUP_ITERATIONS)`, Type: `Int`]: number of warmup periods added before the first observation, used to reduce sensitivity to the initial state. For the inversion filter, values greater than `1` add hidden warmup shocks before the first observation; `warmup_iterations = 1` leaves the result unchanged (same as `0`). Ignored for the Kalman filter (forced to `0`)."
const SHOCK_SIZE® = "`shock_size` [Default: `$(DEFAULT_SHOCK_SIZE)`, Type: `Real`]: size of the shocks in standard deviations. Only affects shocks that are not passed on as a `Matrix` or `KeyedArray` or set to `:none`. A negative value will flip the sign of the shock."
const IGNORE_OBC® = "`ignore_obc` [Default: `$(DEFAULT_IGNORE_OBC)`, Type: `Bool`]: solve the model ignoring the occasionally binding constraints."
const INITIAL_STATE® = "`initial_state` [Default: `$(DEFAULT_INITIAL_STATE)`, Type: `Union{Vector{Vector{Float64}},Vector{Float64}}`]: The initial state defines the starting point for the model. In the case of pruned solution algorithms the initial state can be given as multiple state vectors (`Vector{Vector{Float64}}`). For multiple state vectors the initial state vectors must be given in deviations from the non-stochastic steady state. In all other cases (incl. for pruned solutions) the initial state must be given in levels. If a pruned solution algorithm is selected and `initial_state` is a `Vector{Float64}` then it impacts the first order initial state vector only. The state includes all variables as well as exogenous variables in leads or lags if present. `get_irf(𝓂, shocks = :none, variables = :all, periods = 1, levels = true)` returns a `KeyedArray` with all variables in levels. The `KeyedArray` type is provided by the `AxisKeys` package."
const INITIAL_STATE®1 = "`initial_state` [Default: `$(DEFAULT_INITIAL_STATE)`, Type: `Vector{Float64}`]: The initial state defines the starting point for the model (in levels, not deviations). The state includes all variables as well as exogenous variables in leads or lags if present. `get_irf(𝓂, shocks = :none, variables = :all, periods = 1)` returns a `KeyedArray` with all variables. The `KeyedArray` type is provided by the `AxisKeys` package."
const LABEL® = "`label` [Type: `Union{Real, String, Symbol}`]: label to attribute to this function call in the plots. The default is the number of previous function calls since the last call to the function version with ! + 1."
const RENAME_DICTIONARY® = "`rename_dictionary` [Default: `Dict()`, Type: `Dict{Symbol, String}`]: dictionary mapping variable or shock symbols to custom display names in plots. For example: `Dict(:dinve => \"Investment growth\", :c => \"Consumption\")`. Variables/shocks not in the dictionary will use their default names."
const CONDITIONS_IN_LEVELS® = "`conditions_in_levels` [Default: `true`, Type: `Bool`]: indicator whether the conditions are provided in levels. If `true` the input to the conditions argument will have the relevant steady state subtracted (non-stochastic or stochastic steady state depending on the solution algorithm)."
const CACHING® = "`caching` [Default: `$(DEFAULT_CACHING)`, Type: `Bool`]: use cached intermediate results from previous calls to speed up computation. Set to `false` to force full recomputation."
const USE_WORKSPACES® = "`use_workspaces` [Default: `$(DEFAULT_USE_WORKSPACES)`, Type: `Bool`]: use pre-allocated workspace buffers for intermediate computations. Set to `false` to allocate fresh buffers, leaving the model's workspace state unchanged."
