# Non-stochastic steady state (NSSS) solver
# 
# This file contains wrapper functions for the NSSS solver.
# get_NSSS_and_parameters now calls solve_nsss_wrapper (a normal Julia function)
# instead of calling 𝓂.functions.NSSS_solve directly.

"""
    solve_nsss_wrapper(
        parameter_values::Vector{<:Real},
        𝓂::ℳ,
        tol::Tolerances,
        verbose::Bool,
        cold_start::Bool,
        solver_parameters::Vector{solver_parameters}
    )::Tuple{Vector{Float64}, Tuple{Float64, Int}}

Normal Julia function wrapper for NSSS solving.

This function is called by `get_NSSS_and_parameters` and other parts of the codebase
that need to solve for the non-stochastic steady state. It delegates to the 
model-specific RTGF `𝓂.functions.NSSS_solve`.

# Arguments
- `parameter_values`: Parameter values to solve at
- `𝓂`: Model structure
- `tol`: Tolerance settings
- `verbose`: Whether to print verbose output
- `cold_start`: Whether this is a cold start
- `solver_parameters`: Solver configuration

# Returns
- Tuple of (solution_vector, (solution_error, iterations))
"""
function solve_nsss_wrapper(
    parameter_values::Vector{<:Real},
    𝓂::ℳ,
    tol::Tolerances,
    verbose::Bool,
    cold_start::Bool,
    solver_parameters::Vector{solver_parameters}
)::Tuple{Vector, Tuple{Real, Int}}
    
    # Call the model-specific RTGF
    # The RTGF is generated by write_steady_state_solver_function!
    # and contains the model equations interpolated into the solving logic
    return 𝓂.functions.NSSS_solve(
        parameter_values,
        𝓂,
        tol,
        verbose,
        cold_start,
        solver_parameters
    )
end
